### ISSUE TITLE
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/http/impl/conn/PoolingHttpClientConnectionManager

### ISSUE THREAD

**Issue by ifourvimal** [spotify/docker-client#1010]
## Description
I am trying to use a docker-clinet and i have start with the demo example given in the readme file.
 and using the same dependency given over their which is as per below

           
 ```
<dependency>
        <groupId>com.spotify</groupId>
	<artifactId>docker-client</artifactId>
	<classifier>shaded</classifier>
	<version>3.5.12</version>
</dependency>
```

### code:

```
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.spotify.docker.client.DefaultDockerClient;
import com.spotify.docker.client.DockerCertificateException;
import com.spotify.docker.client.DockerClient;
import com.spotify.docker.client.DockerException;
import com.spotify.docker.client.LogStream;
import com.spotify.docker.client.messages.ContainerConfig;
import com.spotify.docker.client.messages.ContainerCreation;
import com.spotify.docker.client.messages.ContainerInfo;
import com.spotify.docker.client.messages.HostConfig;
import com.spotify.docker.client.messages.PortBinding;

public class dockertask {
		
		public static void main(String[] args) {

			        try {
			        	// Create a client based on DOCKER_HOST and DOCKER_CERT_PATH env vars
			        	final DockerClient docker = DefaultDockerClient.fromEnv().build();

			        	// Pull an image
			        	docker.pull("busybox");

			        	// Bind container ports to host ports
			        	final String[] ports = {"80", "22"};
			        	final Map<String, List<PortBinding>> portBindings = new HashMap<>();
			        	for (String port : ports) {
			        	    List<PortBinding> hostPorts = new ArrayList<>();
			        	    hostPorts.add(PortBinding.of("0.0.0.0", port));
			        	    portBindings.put(port, hostPorts);
			        	}

			        	// Bind container port 443 to an automatically allocated available host port.
			        	List<PortBinding> randomPort = new ArrayList<>();
			        	randomPort.add(PortBinding.randomPort("0.0.0.0"));
			        	portBindings.put("443", randomPort);

			        	final HostConfig hostConfig = HostConfig.builder().portBindings(portBindings).build();

			        	// Create container with exposed ports
			        	final ContainerConfig containerConfig = ContainerConfig.builder()
			        	    .hostConfig(hostConfig)
			        	    .image("busybox").exposedPorts(ports)
			        	    .cmd("sh", "-c", "while :; do sleep 1; done")
			        	    .build();

			        	final ContainerCreation creation = docker.createContainer(containerConfig);
			        	final String id = creation.id();

			        	// Inspect container
			        	final ContainerInfo info = docker.inspectContainer(id);

			        	// Start container
			        	docker.startContainer(id);

			        	// Exec command inside running container with attached STDOUT and STDERR
			        	final String[] command = {"sh", "-c", "ls"};
			        	final ExecCreation execCreation = docker.execCreate(
			        	    id, command, DockerClient.ExecCreateParam.attachStdout(),
			        	    DockerClient.ExecCreateParam.attachStderr());
			        	final LogStream output = docker.execStart(execCreation.id());
			        	final String execOutput = output.readFully();

			        	// Kill container
			        	docker.killContainer(id);

			        	// Remove container
			        	docker.removeContainer(id);

			        	// Close the docker client
			        	docker.close();
					} catch (DockerCertificateException e) {
						// TODO Auto-generated catch block
						e.printStackTrace();
					} catch (DockerException e) {
						// TODO Auto-generated catch block
						e.printStackTrace();
					} catch (InterruptedException e) {
						// TODO Auto-generated catch block
						e.printStackTrace();
					}
			    }
}
`
```

## Software:

- `docker version`:
```
Client:         18.01.0-ce
 API version:   go1.9.2
 Git comThu Jan 11 22:29:41 2018
 OS/Arch:       falsews/amd64
 Orchestrator:  swarm

Server:
 Engine:        18.03.0-ce
  API version:  go1.9.4inimum version 1.12)
  Git commit:   Wed Mar 21 23:14:54 2018
  OS/Arch:      false/amd64
  Experimental:
```
- Spotify's docker-client version: [3.5.12]

## Full backtrace

```text
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/http/impl/conn/PoolingHttpClientConnectionManager
	at com.spotify.docker.client.DefaultDockerClient.getConnectionManager(DefaultDockerClient.java:291)
	at com.spotify.docker.client.DefaultDockerClient.<init>(DefaultDockerClient.java:255)
	at com.spotify.docker.client.DefaultDockerClient$Builder.build(DefaultDockerClient.java:1555)
	at com.ifour.testdata.test.dockertask.main(dockertask.java:25)
Caused by: java.lang.ClassNotFoundException: org.apache.http.impl.conn.PoolingHttpClientConnectionManager
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 4 more

```

**Comment by davidxia** [comment]
What version of java are you running and does this still happen on the latest docker-client version? Is there a difference between using the shaded and non-shaded artifacts?
