### ISSUE TITLE
Clean placement Constraints

### ISSUE THREAD

**Issue by ViniciusDeAndrade** [spotify/docker-client#1022]
Hello everybody.
I am trying to clean the placement constrains but for some reason I am getting this:

`Exception in thread "main" java.lang.UnsupportedOperationException
	at com.google.common.collect.ImmutableCollection.clear(ImmutableCollection.java:266)
	at br.ufpe.cin.gfads.docker.DockerController.cleanConstraints(DockerController.java:90)
	at br.ufpe.cin.gfads.docker.DockerController.chooseHosts(DockerController.java:79)
	at br.ufpe.cin.gfads.main.Main.main(Main.java:41)`

and the line of code is this one:

`service.spec().taskTemplate().placement().constraints().clear();`

I know that the constraints() returns a Immutable list, but if acts like so, why does it has a clear method?

Thanks 

![clear](https://user-images.githubusercontent.com/4364432/40270980-3b3c4ebe-5b6d-11e8-9297-2fa65a3673eb.png)

**Comment by davidxia** [comment]
Since all the value classes use immutable collections, you'll have to use builders or static factory methods to create new instances with the values you want.

**Comment by ViniciusDeAndrade** [comment]
I think I got what went wrong.
I was moving using a loop. But if I do it without set a Time to the next call (Thread.sleep()), It will get a scheduling error.

**Comment by ViniciusDeAndrade** [comment]
And I was using a Placement.create()
