### ISSUE TITLE
Is there a method to check if the dockerClient has been closed?

### ISSUE THREAD

**Issue by jiajiantao** [spotify/docker-client#1031]
I need to check if the dockerClient has been closed, but this does not work.

        public void run() {
            try {
                logStream = dockerClient.logs(containerId, DockerClient.LogsParam.stdout(), DockerClient.LogsParam.stderr(),
                        DockerClient.LogsParam.follow(), DockerClient.LogsParam.tail(200));
                while (dockerClient != null & logStream.hasNext()) {

                    LogMessage logMessage = logStream.next();
                    ByteBuffer content = logMessage.content();
                    String mes = StandardCharsets.UTF_8.decode(content).toString();
                    Message message = new Message();
                    message.setMessage(mes);
                    message.setId(containerId);
                    logger.info("msg:{}", mes);
                    containerWebSocketHandler.sendMessage(message);
                }
            } catch (DockerException | InterruptedException e) {
                e.printStackTrace();
            } finally {
                close();
                threadMap.remove(sessionId);
            }
        }

**Comment by davidxia** [comment]
There's no way to check if `DockerClient` is already closed, but it extends `Closeable` so you can just call `DockerClient.close()` as many times as you want and it should be idempotent.

What's the error you get? What does `close()` do?

**Comment by jiajiantao** [comment]
The close() method is this


```java
        @Override
        public void close() {
            if (isClosed.compareAndSet(false, true)) {
                if (dockerClient != null) {
                    dockerClient.close();
                }
            }
        }
```

And the error is 

```java
2018-05-30 22:02:50,278 [com.demo.service.impl.ServiceManagerImpl$LogRunnable.run(ServiceManagerImpl.java:556)] INFO 日志线程执行结束
Exception in thread "Thread-31" java.lang.RuntimeException: java.net.SocketException: Socket closed
	at com.google.common.base.Throwables.propagate(Throwables.java:240)
	at com.spotify.docker.client.DefaultLogStream.computeNext(DefaultLogStream.java:58)
	at com.spotify.docker.client.DefaultLogStream.computeNext(DefaultLogStream.java:35)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:145)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:140)
	at com.demo.service.impl.ServiceManagerImpl$LogRunnable.run(ServiceManagerImpl.java:540)
Caused by: java.net.SocketException: Socket closed
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137)
	at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:153)
	at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:282)
	at org.apache.http.impl.io.ChunkedInputStream.getChunkSize(ChunkedInputStream.java:264)
	at org.apache.http.impl.io.ChunkedInputStream.nextChunk(ChunkedInputStream.java:225)
	at org.apache.http.impl.io.ChunkedInputStream.read(ChunkedInputStream.java:184)
	at org.apache.http.conn.EofSensorInputStream.read(EofSensorInputStream.java:135)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
	at java.io.FilterInputStream.read(FilterInputStream.java:133)
	at java.io.FilterInputStream.read(FilterInputStream.java:133)
	at org.glassfish.jersey.message.internal.EntityInputStream.read(EntityInputStream.java:102)
	at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream.read(ReaderInterceptorExecutor.java:296)
	at com.google.common.io.ByteStreams.read(ByteStreams.java:859)
	at com.spotify.docker.client.LogReader.nextMessage(LogReader.java:49)
	at com.spotify.docker.client.DefaultLogStream.computeNext(DefaultLogStream.java:56)
	... 4 more
```
When the dockerClient was closed, the ```logStream.hasNext()``` will throw this error
