### ISSUE TITLE
Unable to use InputStream from archiveContainer() 

### ISSUE THREAD

**Issue by hapatch** [spotify/docker-client#1072]
**Is this a BUG REPORT or FEATURE REQUEST?**:
Bug Report

## Description

When trying to archive a container using: 
`docker.archiveContainer(String containerID, String path)`

The returning inputstream results in, javax.ws.rs.ProcessingException, and a org.apache.http.ConnectionClosedException

It seems unable to close the input stream created by the archiveContainer() function, showing in the stack trace: 

7. ProcessingException: javax.ws.rs.ProcessingException: Error closing message content input stream.
8. ConnectionClosedException: org.apache.http.ConnectionClosedException: Premature end of chunk coded message body: closing chunk expected

## How to reproduce

In my case: 
``` 
Set<String> paths ... ;

for (String path : paths) {
	try (TarArchiveInputStream is = new TarArchiveInputStream(docker.archiveContainer(containerID, path) {
	}
}
```

Where paths are some paths within the container, I have been able to reproduce this without needing to use the input stream, but I am attempting to copy these files into an identical container that has those folders mounted to the local filesystem:

`docker.copyToContainer(is, container.id(), destinationPath);`

## What do you expect

As with previous versions of docker for windows that were used, I was expecting the files/folders to be archived into an input stream, and then be cleanly copied to the other container.

## What happened instead

A Processing and ConnectionClosed Exception is thrown by the program:

7. ProcessingException: javax.ws.rs.ProcessingException: Error closing message content input stream.
8. ConnectionClosedException: org.apache.http.ConnectionClosedException: Premature end of chunk coded message body: closing chunk expected

## Software:

- `docker version`: Version 18.06.1-ce-win73 (19507)
- Spotify's docker-client version: 8.13.0

## Full backtrace

```text
7. ProcessingException: javax.ws.rs.ProcessingException: Error closing message content input stream.
8. ConnectionClosedException: org.apache.http.ConnectionClosedException: Premature end of chunk coded message body: closing chunk expected
	at org.apache.http.impl.io.ChunkedInputStream.getChunkSize(ChunkedInputStream.java:266)
	at org.apache.http.impl.io.ChunkedInputStream.nextChunk(ChunkedInputStream.java:225)
	at org.apache.http.impl.io.ChunkedInputStream.read(ChunkedInputStream.java:184)
	at org.apache.http.impl.io.ChunkedInputStream.read(ChunkedInputStream.java:213)
	at org.apache.http.impl.io.ChunkedInputStream.close(ChunkedInputStream.java:315)
	at org.apache.http.impl.execchain.ResponseEntityProxy.streamClosed(ResponseEntityProxy.java:143)
	at org.apache.http.conn.EofSensorInputStream.checkClose(EofSensorInputStream.java:228)
	at org.apache.http.conn.EofSensorInputStream.close(EofSensorInputStream.java:172)
	at org.apache.http.client.entity.LazyDecompressingInputStream.close(LazyDecompressingInputStream.java:97)
	at java.io.BufferedInputStream.close(BufferedInputStream.java:483)
	at java.io.FilterInputStream.close(FilterInputStream.java:181)
	at org.glassfish.jersey.apache.connector.ApacheConnector$3.close(ApacheConnector.java:644)
	at java.io.FilterInputStream.close(FilterInputStream.java:181)
	at org.glassfish.jersey.apache.connector.ApacheConnector$HttpClientResponseInputStream.close(ApacheConnector.java:621)
	at org.glassfish.jersey.message.internal.EntityInputStream.close(EntityInputStream.java:158)
	at org.apache.commons.compress.archivers.tar.TarArchiveInputStream.close(TarArchiveInputStream.java:151)
```

Let me know if you need more information, or if there is a better work around. 

Currently creating two containers from the same image, creating bind mounts for one and using the second to copy the removed files/folders back into the first container. Weirdly, this same code works with this version of docker for windows: 18.03.1-ce-win65

**Comment by Galorhallen** [comment]
Hello,
 I'm experiencing the same issue.

### Software
- OS: Ubuntu 18.04.1 LTS
- docker version: 18.09.0
- docker API version: 1.39
- Spotify's docker-client version: 8.14.3

### Full backtrace
java.io.IOException: Bad file descriptor
    at jnr.enxio.channels.Common.read(Common.java:67) ~[jnr-unixsocket-0.18.jar!/:na]
    at jnr.enxio.channels.AbstractNativeSocketChannel.read(AbstractNativeSocketChannel.java:62) ~[jnr-unixsocket-0.18.jar!/:na]
    at jnr.unixsocket.UnixSocketChannel.read(UnixSocketChannel.java:250) ~[jnr-unixsocket-0.18.jar!/:na]
    at sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:59) ~[na:1.8.0_181]
    at sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:109) ~[na:1.8.0_181]
    at sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:103) ~[na:1.8.0_181]
    at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137) ~[httpcore-4.4.10.jar!/:4.4.10]
    at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:153) ~[httpcore-4.4.10.jar!/:4.4.10]
    at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:282) ~[httpcore-4.4.10.jar!/:4.4.10]
    at org.apache.http.impl.io.ChunkedInputStream.getChunkSize(ChunkedInputStream.java:251) ~[httpcore-4.4.10.jar!/:4.4.10]
    at org.apache.http.impl.io.ChunkedInputStream.nextChunk(ChunkedInputStream.java:225) ~[httpcore-4.4.10.jar!/:4.4.10]
    at org.apache.http.impl.io.ChunkedInputStream.read(ChunkedInputStream.java:184) ~[httpcore-4.4.10.jar!/:4.4.10]
    at org.apache.http.impl.io.ChunkedInputStream.read(ChunkedInputStream.java:213) ~[httpcore-4.4.10.jar!/:4.4.10]
    at org.apache.http.impl.io.ChunkedInputStream.close(ChunkedInputStream.java:315) ~[httpcore-4.4.10.jar!/:4.4.10]
    at org.apache.http.impl.execchain.ResponseEntityProxy.streamClosed(ResponseEntityProxy.java:143) ~[httpclient-4.5.6.jar!/:4.5.6]
    at org.apache.http.conn.EofSensorInputStream.checkClose(EofSensorInputStream.java:228) ~[httpclient-4.5.6.jar!/:4.5.6]
    at org.apache.http.conn.EofSensorInputStream.close(EofSensorInputStream.java:172) ~[httpclient-4.5.6.jar!/:4.5.6]
    at java.util.zip.InflaterInputStream.close(InflaterInputStream.java:227) ~[na:1.8.0_181]
    at java.util.zip.GZIPInputStream.close(GZIPInputStream.java:136) ~[na:1.8.0_181]
    at org.apache.http.client.entity.LazyDecompressingInputStream.close(LazyDecompressingInputStream.java:94) ~[httpclient-4.5.6.jar!/:4.5.6]
    at java.io.BufferedInputStream.close(BufferedInputStream.java:483) ~[na:1.8.0_181]
    at java.io.FilterInputStream.close(FilterInputStream.java:181) ~[na:1.8.0_181]
    at org.glassfish.jersey.apache.connector.ApacheConnector$3.close(ApacheConnector.java:644) ~[jersey-apache-connector-2.22.2.jar!/:na]
    at java.io.FilterInputStream.close(FilterInputStream.java:181) ~[na:1.8.0_181]
    at org.glassfish.jersey.apache.connector.ApacheConnector$HttpClientResponseInputStream.close(ApacheConnector.java:621) ~[jersey-apache-connector-2.22.2.jar!/:na]
    at org.glassfish.jersey.message.internal.EntityInputStream.close(EntityInputStream.java:159) ~[jersey-common-2.26.jar!/:na]
    at org.apache.commons.compress.archivers.tar.TarArchiveInputStream.close(TarArchiveInputStream.java:157) ~[commons-compress-1.18.jar!/:1.18]
