### ISSUE TITLE
'Connection closed by peer' exception after execStart()

### ISSUE THREAD

**Issue by smirnp** [spotify/docker-client#1098]
## Description

When execute an execStart command for any running container getting the 'Connection closed by peer' error  in around 50% of runs. The result stream cannot be readed because of the error.

## How to reproduce
String containerId = "someRunningContainerId"
String[] command = new String[]{"/usr/bin/date"};
DockerClient dedicatedDockerClient = DefaultDockerClient.fromEnv().build();
                ExecCreation execCreation = dedicatedDockerClient.execCreate(containerId, command, DockerClient.ExecCreateParam.attachStdout(), DockerClient.ExecCreateParam.attachStderr());
                LogStream stream = dedicatedDockerClient.execStart((execCreation.id()));
                execOutput = stream.readFully();
                dedicatedDockerClient.close();

## What do you expect

Result of the executed command. 

## What happened instead

From time to time there is an error 'Connection closed by peer' at 'stream.readFully()' line

## Software:

- `docker version`: 
Client:
 Version:	17.12.1-ce
 API version:	1.35
 Go version:	go1.9.4
 Git commit:	7390fc6
 Built:	Tue Feb 27 22:20:00 2018
 OS/Arch:	linux/amd64

Server:
 Engine:
  Version:	17.12.1-ce
  API version:	1.35 (minimum version 1.12)
  Go version:	go1.9.4
  Git commit:	7390fc6
  Built:	Tue Feb 27 22:22:34 2018
  OS/Arch:	linux/amd64
  Experimental:	false

- Spotify's docker-client version: 8.11.7

## Full backtrace
java.lang.RuntimeException: java.io.IOException: Connection reset by peer
	at com.google.common.base.Throwables.propagate(Throwables.java:241)
	at com.spotify.docker.client.DefaultLogStream.computeNext(DefaultLogStream.java:58)
	at com.spotify.docker.client.DefaultLogStream.computeNext(DefaultLogStream.java:35)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:145)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:140)
	at com.spotify.docker.client.DefaultLogStream.readFully(DefaultLogStream.java:77)
Caused by: java.io.IOException: Connection reset by peer
	at jnr.enxio.channels.Common.read(Common.java:67)
	at jnr.enxio.channels.AbstractNativeSocketChannel.read(AbstractNativeSocketChannel.java:62)
	at jnr.unixsocket.UnixSocketChannel.read(UnixSocketChannel.java:250)
	at sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:59)
	at sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:109)
	at sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:103)
	at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137)
	at org.apache.http.impl.io.SessionInputBufferImpl.read(SessionInputBufferImpl.java:198)
	at org.apache.http.impl.io.IdentityInputStream.read(IdentityInputStream.java:93)
	at org.apache.http.conn.EofSensorInputStream.read(EofSensorInputStream.java:137)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
	at java.io.FilterInputStream.read(FilterInputStream.java:133)
	at java.io.FilterInputStream.read(FilterInputStream.java:133)
	at org.glassfish.jersey.message.internal.EntityInputStream.read(EntityInputStream.java:102)
	at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream.read(ReaderInterceptorExecutor.java:296)
	at com.google.common.io.ByteStreams.read(ByteStreams.java:859)
	at com.spotify.docker.client.LogReader.nextMessage(LogReader.java:49)
	at com.spotify.docker.client.DefaultLogStream.computeNext(DefaultLogStream.java:56)
	... 16 more
```

**Comment by jkbbwr** [comment]
Any progress on this or do we need to switch to a different docker client

**Comment by jkbbwr** [comment]
This is an active issue. You can't just stale close it.

**Comment by bnzishan** [comment]
I am having the same problem. Any solution available? Would appreciate that.

# How to produce

`final String[] command = { "/bin/bash", "-c", scriptContent};
				DockerClient dockerClient = DefaultDockerClient.fromEnv().build();
				ExecCreation execCreation = dockerClient.execCreate(
											containerId, command, DockerClient.ExecCreateParam.attachStdout(),
											DockerClient.ExecCreateParam.attachStderr());
				LogStream output = dockerClient.execStart(execCreation.id());
				execOutput = output.readFully();
`
# Software 
docker version
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:42:38 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:41:20 2017
 OS/Arch:      linux/amd64
 Experimental: false

# Backtrace 
java.lang.RuntimeException: java.io.IOException: Connection reset by peer
	at com.google.common.base.Throwables.propagate(Throwables.java:240)
	at com.spotify.docker.client.DefaultLogStream.computeNext(DefaultLogStream.java:58)
	at com.spotify.docker.client.DefaultLogStream.computeNext(DefaultLogStream.java:35)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:145)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:140)
	at com.spotify.docker.client.DefaultLogStream.readFully(DefaultLogStream.java:77)
	at org.hobbit.sdk.sensemark2.system.SystemAdapter.internalInit(SystemAdapter.java:531)
	at org.hobbit.sdk.sensemark2.system.SystemAdapter.init(SystemAdapter.java:68)
	at org.hobbit.sdk.utils.ComponentsExecutor.lambda$submit$0(ComponentsExecutor.java:75)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Connection reset by peer
	at jnr.enxio.channels.NativeSocketChannel.read(NativeSocketChannel.java:82)
	at sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:59)
	at sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:109)
	at sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:103)
	at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137)
	at org.apache.http.impl.io.SessionInputBufferImpl.read(SessionInputBufferImpl.java:198)
	at org.apache.http.impl.io.IdentityInputStream.read(IdentityInputStream.java:93)
	at org.apache.http.conn.EofSensorInputStream.read(EofSensorInputStream.java:137)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
	at java.io.FilterInputStream.read(FilterInputStream.java:133)
	at java.io.FilterInputStream.read(FilterInputStream.java:133)
	at org.glassfish.jersey.message.internal.EntityInputStream.read(EntityInputStream.java:102)
	at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream.read(ReaderInterceptorExecutor.java:296)
	at com.google.common.io.ByteStreams.read(ByteStreams.java:859)
	at com.spotify.docker.client.LogReader.nextMessage(LogReader.java:49)
	at com.spotify.docker.client.DefaultLogStream.computeNext(DefaultLogStream.java:56)
	... 12 more

**Comment by gavarava** [comment]
Any updates to this one ? We are still facing this issue we want to assert the output of ls command
