### ISSUE TITLE
Container remove error: "Container not found"

### ISSUE THREAD

**Issue by DimaStoyanov** [spotify/docker-client#1103]
**Is this a BUG REPORT or FEATURE REQUEST?**:

Bug report
## Description
I create container, start and wait it, then collect some results and try to remove container. But I got error, which says that container with specified id not found. In logs you can see that container is created and started
```
 c.s.docker.client.DefaultDockerClient    : Starting container with Id: ee8e86f114d78cf9e0782b11ffd4ac80fb5cadf77320cae793fd4de0e2e013cf
```
and then docker client can't find container with same id
```
com.spotify.docker.client.exceptions.ContainerNotFoundException: Container not found: ee8e86f114d78cf9e0782b11ffd4ac80fb5cadf77320cae793fd4de0e2e013cf
```
My code is bellow:
```
        ContainerCreation creation = docker.createContainer(containerConfig);
        String id = creation.id();
        docker.startContainer(id);

        killIfTimeLimitExceeds(id, optionsState.millis);
        collectContainerStat(id);
        docker.waitContainer(id);
        ContainerExecutionResult result = buildResult(id);
        docker.removeContainer(id);
```
So all rows before remove are working, but  then this error repeatedly appears in the logs

## How to reproduce
1. Create container and get id
2. Start it
3. Wait until container is finished ( or kill)
4. Remove container

## What do you expect

Container is removed

## What happened instead

ContainerNotFoundException

## Software:

- `docker version`: `18.06.1-ce`
- Spotify's docker-client version: `8.14.3`
- OS: Windows 10 Professional

## Full backtrace

```text
2018-11-03 23:30:30.427  INFO 13268 --- [nio-4568-exec-1] c.s.docker.client.DefaultDockerClient    : Starting container with Id: ee8e86f114d78cf9e0782b11ffd4ac80fb5cadf77320cae793fd4de0e2e013cf
2018-11-03 23:30:33.330  INFO 13268 --- [nio-4568-exec-1] t.t.c.m.c.CodeCompilationManager         : Compilation result: ContainerExecutionResult(executionTime=PT1.6801441S, exitCode=2, oomKilled=false, memoryUsage=null)
2018-11-03 23:30:33.385  INFO 13268 --- [nio-4568-exec-1] t.t.c.m.c.CodeCompilationManager         : CodeCompilationResult(language=JAVA, status=COMPILATION_ERROR, workDirName=66f77bc2-b5aa-4423-ba5a-19c5ae74ecbd)
2018-11-03 23:30:33.706 ERROR 13268 --- [TaskScheduler-2] t.t.c.m.docker.DockerContainerManager    : com.spotify.docker.client.exceptions.ContainerNotFoundException: Container not found: ee8e86f114d78cf9e0782b11ffd4ac80fb5cadf77320cae793fd4de0e2e013cf

com.spotify.docker.client.exceptions.ContainerNotFoundException: Container not found: ee8e86f114d78cf9e0782b11ffd4ac80fb5cadf77320cae793fd4de0e2e013cf
	at com.spotify.docker.client.DefaultDockerClient.stats(DefaultDockerClient.java:2379) ~[docker-client-8.14.3.jar:8.14.3]
	at tsystems.tchallenge.codecompiler.managers.docker.DockerContainerManager.lambda$collectContainerStat$2(DockerContainerManager.java:120) ~[main/:na]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
Caused by: com.spotify.docker.client.exceptions.DockerRequestException: Request error: GET http://localhost:2375/containers/ee8e86f114d78cf9e0782b11ffd4ac80fb5cadf77320cae793fd4de0e2e013cf/stats?stream=0: 404, body: {"message":"No such container: ee8e86f114d78cf9e0782b11ffd4ac80fb5cadf77320cae793fd4de0e2e013cf"}

	at com.spotify.docker.client.DefaultDockerClient.propagate(DefaultDockerClient.java:2820) ~[docker-client-8.14.3.jar:8.14.3]
	at com.spotify.docker.client.DefaultDockerClient.request(DefaultDockerClient.java:2692) ~[docker-client-8.14.3.jar:8.14.3]
	at com.spotify.docker.client.DefaultDockerClient.stats(DefaultDockerClient.java:2375) ~[docker-client-8.14.3.jar:8.14.3]
	... 8 common frames omitted
Caused by: javax.ws.rs.NotFoundException: HTTP 404 Not Found
	at org.glassfish.jersey.client.JerseyInvocation.convertToException(JerseyInvocation.java:1086) ~[jersey-client-2.26.jar:na]
	at org.glassfish.jersey.client.JerseyInvocation.translate(JerseyInvocation.java:883) ~[jersey-client-2.26.jar:na]
	at org.glassfish.jersey.client.JerseyInvocation.access$500(JerseyInvocation.java:99) ~[jersey-client-2.26.jar:na]
	at org.glassfish.jersey.client.JerseyInvocation$2.completed(JerseyInvocation.java:840) ~[jersey-client-2.26.jar:na]
	at org.glassfish.jersey.client.ClientRuntime.processResponse(ClientRuntime.java:227) ~[jersey-client-2.26.jar:na]
	at org.glassfish.jersey.client.ClientRuntime.access$200(ClientRuntime.java:85) ~[jersey-client-2.26.jar:na]
	at org.glassfish.jersey.client.ClientRuntime$2.lambda$response$0(ClientRuntime.java:178) ~[jersey-client-2.26.jar:na]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:272) ~[jersey-common-2.26.jar:na]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:268) ~[jersey-common-2.26.jar:na]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:316) ~[jersey-common-2.26.jar:na]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:298) ~[jersey-common-2.26.jar:na]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:268) ~[jersey-common-2.26.jar:na]
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:312) ~[jersey-common-2.26.jar:na]
	at org.glassfish.jersey.client.ClientRuntime$2.response(ClientRuntime.java:178) ~[jersey-client-2.26.jar:na]
	at org.glassfish.jersey.apache.connector.ApacheConnector$1.run(ApacheConnector.java:491) ~[jersey-apache-connector-2.22.2.jar:na]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
	at jersey.repackaged.com.google.common.util.concurrent.MoreExecutors$DirectExecutorService.execute(MoreExecutors.java:299) ~[jersey-guava-2.25.1.jar:na]
	at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:118) ~[na:na]
	at jersey.repackaged.com.google.common.util.concurrent.AbstractListeningExecutorService.submit(AbstractListeningExecutorService.java:50) ~[jersey-guava-2.25.1.jar:na]
	at jersey.repackaged.com.google.common.util.concurrent.AbstractListeningExecutorService.submit(AbstractListeningExecutorService.java:37) ~[jersey-guava-2.25.1.jar:na]
	at org.glassfish.jersey.apache.connector.ApacheConnector.apply(ApacheConnector.java:487) ~[jersey-apache-connector-2.22.2.jar:na]
	at org.glassfish.jersey.client.ClientRuntime.lambda$null$3(ClientRuntime.java:187) ~[jersey-client-2.26.jar:na]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:272) ~[jersey-common-2.26.jar:na]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:268) ~[jersey-common-2.26.jar:na]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:316) ~[jersey-common-2.26.jar:na]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:298) ~[jersey-common-2.26.jar:na]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:268) ~[jersey-common-2.26.jar:na]
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:312) ~[jersey-common-2.26.jar:na]
	at org.glassfish.jersey.client.ClientRuntime.lambda$createRunnableForAsyncProcessing$4(ClientRuntime.java:163) ~[jersey-client-2.26.jar:na]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
	... 3 common frames omitted

2018-11-03 23:30:34.216 ERROR 13268 --- [TaskScheduler-3] t.t.c.m.docker.DockerContainerManager    : com.spotify.docker.client.exceptions.ContainerNotFoundException: Container not found: ee8e86f114d78cf9e0782b11ffd4ac80fb5cadf77320cae793fd4de0e2e013cf

com.spotify.docker.client.exceptions.ContainerNotFoundException: Container not found: ee8e86f114d78cf9e0782b11ffd4ac80fb5cadf77320cae793fd4de0e2e013cf
	at com.spotify.docker.client.DefaultDockerClient.stats(DefaultDockerClient.java:2379) ~[docker-client-8.14.3.jar:8.14.3]
	at tsystems.tchallenge.codecompiler.managers.docker.DockerContainerManager.lambda$collectContainerStat$2(DockerContainerManager.java:120) ~[main/:na]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
Caused by: com.spotify.docker.client.exceptions.DockerRequestException: Request error: GET http://localhost:2375/containers/ee8e86f114d78cf9e0782b11ffd4ac80fb5cadf77320cae793fd4de0e2e013cf/stats?stream=0: 404, body: {"message":"No such container: ee8e86f114d78cf9e0782b11ffd4ac80fb5cadf77320cae793fd4de0e2e013cf"}

	at com.spotify.docker.client.DefaultDockerClient.propagate(DefaultDockerClient.java:2820) ~[docker-client-8.14.3.jar:8.14.3]
	at com.spotify.docker.client.DefaultDockerClient.request(DefaultDockerClient.java:2692) ~[docker-client-8.14.3.jar:8.14.3]
	at com.spotify.docker.client.DefaultDockerClient.stats(DefaultDockerClient.java:2375) ~[docker-client-8.14.3.jar:8.14.3]
	... 8 common frames omitted

```

**Comment by DimaStoyanov** [comment]
My fault, in another thread I collecting statistics of container, and when container is removed, I got this message
