### ISSUE TITLE
Unable to push docker image to local registry.

### ISSUE THREAD

**Issue by hemikak** [spotify/docker-client#1110]
I am getting the following error when pushing an image to the local registry:

**Is this a BUG REPORT or FEATURE REQUEST?**: It is a bug.

## Description
I am using a mac and trying to push an image to my local registry. But I am getting the following error(see bottom). I was usin fabric8 docker-client and it worked fine. I am using the shaded jar.

## How to reproduce
```
DockerClient client = DefaultDockerClient.builder().uri("unix:///var/run/docker.sock).build();
client.build(Paths.get(dockerDir), dockerModel.getName(), message -> {
    String errorMessage = message.error();
    String builtImageId = message.buildImageId();
}, DockerClient.BuildParam.noCache(), DockerClient.BuildParam.forceRm());
```

## What do you expect

The image to be pushed.

## What happened instead

Fails

## Software:

- `docker version`: 18.06.1-ce
- Spotify's docker-client version: 8.14.3

## Full backtrace

```text
[2018-11-12 16:15:17,188] WARN  {com.spotify.docker.client.shaded.com.fasterxml.jackson.databind.ext.Java7Support} - Unable to load JDK7 types (annotations, java.nio.file.Path): no Java7 support added  
[2018-11-12 16:15:17,413] ERROR {org.ballerinalang.launcher.Main} - Bad return type
Exception Details:
  Location:
    com/spotify/docker/client/UnixConnectionSocketFactory.createSocket(Lcom/spotify/docker/client/shaded/org/apache/http/protocol/HttpContext;)Ljava/net/Socket; @5: areturn
  Reason:
    Type 'jnr/unixsocket/UnixSocket' (current frame, stack[0]) is not assignable to 'java/net/Socket' (from method signature)
  Current Frame:
    bci: @5
    flags: { }
    locals: { 'com/spotify/docker/client/UnixConnectionSocketFactory', 'com/spotify/docker/client/shaded/org/apache/http/protocol/HttpContext' }
    stack: { 'jnr/unixsocket/UnixSocket' }
  Bytecode:
    0x0000000: 2a2b b600 9cb0                         
 
java.lang.VerifyError: Bad return type
Exception Details:
  Location:
    com/spotify/docker/client/UnixConnectionSocketFactory.createSocket(Lcom/spotify/docker/client/shaded/org/apache/http/protocol/HttpContext;)Ljava/net/Socket; @5: areturn
  Reason:
    Type 'jnr/unixsocket/UnixSocket' (current frame, stack[0]) is not assignable to 'java/net/Socket' (from method signature)
  Current Frame:
    bci: @5
    flags: { }
    locals: { 'com/spotify/docker/client/UnixConnectionSocketFactory', 'com/spotify/docker/client/shaded/org/apache/http/protocol/HttpContext' }
    stack: { 'jnr/unixsocket/UnixSocket' }
  Bytecode:
    0x0000000: 2a2b b600 9cb0                         

	at com.spotify.docker.client.DefaultDockerClient.<init>(DefaultDockerClient.java:440)
	at com.spotify.docker.client.DefaultDockerClient$Builder.build(DefaultDockerClient.java:3174)
	at org.ballerinax.docker.DockerArtifactHandler.buildImage(DockerArtifactHandler.java:90)
	at org.ballerinax.docker.DockerAnnotationProcessor.createDockerArtifacts(DockerAnnotationProcessor.java:229)
	at org.ballerinax.docker.DockerAnnotationProcessor.processDockerModel(DockerAnnotationProcessor.java:88)
	at org.ballerinax.docker.DockerPlugin.codeGenerated(DockerPlugin.java:158)
	at org.wso2.ballerinalang.compiler.BinaryFileWriter.lambda$writeExecutableBinary$0(BinaryFileWriter.java:121)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at org.wso2.ballerinalang.compiler.BinaryFileWriter.writeExecutableBinary(BinaryFileWriter.java:120)
	at org.wso2.ballerinalang.compiler.BinaryFileWriter.write(BinaryFileWriter.java:95)
	at org.wso2.ballerinalang.compiler.Compiler.write(Compiler.java:117)
	at org.ballerinalang.packerina.BuilderUtils.compileWithTestsAndWrite(BuilderUtils.java:77)
	at org.ballerinalang.packerina.cmd.BuildCommand.execute(BuildCommand.java:162)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.ballerinalang.launcher.Main.main(Main.java:65)
```

**Comment by mattnworb** [comment]
can you tell us more about what OS you are using, what version of Java and what JVM? I don't think I have seen a stacktrace formatting like that before.

**Comment by hemikak** [comment]
Java version: Oracle "1.8.0_144"
OS version: MacOS Mojave

**Comment by hemikak** [comment]
Closing this issue as this was due to having fabric8 docker-client dependency in my fat jar.
