### ISSUE TITLE
"Could not acquire image ID or digest following build" on windows

### ISSUE THREAD

**Issue by hemikak** [spotify/docker-client#1139]
**Is this a BUG REPORT or FEATURE REQUEST?**: BUG REPORT

## Description
I am trying to do a docker build on windows but I am getting the following error:
```
2019-02-07 02:34:57 INFO  DockerTestUtils:204 - [2019-02-07 02:34:57,152] ERROR {org.ballerinalang.launcher.Main} - Could not acquire image ID or digest following build 
java.lang.IllegalStateException: Could not acquire image ID or digest following build
	at com.google.common.base.Preconditions.checkState(Preconditions.java:174)
	at com.spotify.docker.client.DefaultDockerClient$BuildProgressHandler.getImageId(DefaultDockerClient.java:302)
	at com.spotify.docker.client.DefaultDockerClient$BuildProgressHandler.access$1200(DefaultDockerClient.java:291)
	at com.spotify.docker.client.DefaultDockerClient.build(DefaultDockerClient.java:1496)
	at com.spotify.docker.client.DefaultDockerClient.build(DefaultDockerClient.java:1460)
	at org.ballerinax.docker.generator.DockerArtifactHandler.buildImage(DockerArtifactHandler.java:131)
	at org.ballerinax.docker.generator.DockerArtifactHandler.createArtifacts(DockerArtifactHandler.java:96)
```

The above works in mac and linux.

## How to reproduce

```java
            DockerClient client;
            client = DefaultDockerClient.builder()
                    .uri(dockerModel.getDockerHost())
                    .dockerCertificates(certs)
                    .build();
    
            client.build(Paths.get(dockerDir), dockerModel.getName(), message -> {
                String buildImageId = message.buildImageId();
                String error = message.error();
    
                if (null != message.stream()) {
                    printDebug(message.stream());
                }
                
                if (null != message.progress()) {
                    printDebug("Progress: " + message.progress());
                }
    
                // when an image is built successfully.
                if (null != buildImageId) {
                    printDebug("Build ID: " + buildImageId);
                }
                
                // when there is an error.
                if (null != error) {
                    printDebug("Error message: " + error);
                }
            }, DockerClient.BuildParam.noCache(), DockerClient.BuildParam.forceRm());
```

## What do you expect

Expects the docker image built

## What happened instead

Docker image doesnt build

## Software:

- `docker version`: 18.05.0-ce, build f150324
- Spotify's docker-client version: 8.14.5

**Comment by hemikak** [comment]
Update: I also passed in the another BuildParam as `new DockerClient.BuildParam("platform", "linux")` after it started to print an error saying the image is a linux based image. Still getting the same error. No clue as to why its failing like this. How to get more info on this ?
