### ISSUE TITLE
BUG: `DefaultDockerClient.events()` is not interruptible

### ISSUE THREAD

**Issue by t-8ch** [spotify/docker-client#1140]
**BUG REPORT**:

## Description

When waiting for events from docker in a loop the client can't be shut down normally, because the thread polling for events can not be interrupted.

## How to reproduce

Start the following program:

```java
public class Main {
    public static void main(String[] args) throws Exception {
        DefaultDockerClient docker = DefaultDockerClient.fromEnv().build();
        EventStream events = docker.events();
        while (events.hasNext()) {
            System.out.println(events.next());
        }
    }
}
```

Try to interrupt using normal facilities.

## What do you expect

The program exits.

## What happened instead

The program continues to run.

## Software:

- `docker version`:

```
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.4
 Git commit:        e68fc7a
 Built:             Thu Nov 15 21:12:47 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       e68fc7a
  Built:            Sun Nov 11 21:53:22 2018
  OS/Arch:          linux/amd64
  Experimental:     false\
```

- Spotify's docker-client version: `8.15.0`

## Full backtrace

N/A

**Comment by caryyu** [comment]
Even an issue below is happening but still running:
```
swarm-detector_swarm-detector_14 | 2019-04-06T00:41:15.231526423Z Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
swarm-detector_swarm-detector_14 | 2019-04-06T00:41:15.231814262Z 	at java.nio.HeapByteBuffer.<init>(HeapByteBuffer.java:57)
swarm-detector_swarm-detector_14 | 2019-04-06T00:41:15.231832366Z 	at java.nio.ByteBuffer.allocate(ByteBuffer.java:335)
swarm-detector_swarm-detector_14 | 2019-04-06T00:41:15.231837893Z 	at jnr.enxio.channels.Common.read(Common.java:47)
swarm-detector_swarm-detector_14 | 2019-04-06T00:41:15.231842647Z 	at jnr.enxio.channels.AbstractNativeSocketChannel.read(AbstractNativeSocketChannel.java:62)
swarm-detector_swarm-detector_14 | 2019-04-06T00:41:15.231848007Z 	at jnr.unixsocket.UnixSocketChannel.read(UnixSocketChannel.java:250)
swarm-detector_swarm-detector_14 | 2019-04-06T00:41:15.231854560Z 	at sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:59)
swarm-detector_swarm-detector_14 | 2019-04-06T00:41:15.232275920Z 	at sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:109)
swarm-detector_swarm-detector_14 | 2019-04-06T00:41:15.232291065Z 	at sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:103)
swarm-detector_swarm-detector_14 | 2019-04-06T00:41:15.232296881Z 	at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137)
swarm-detector_swarm-detector_14 | 2019-04-06T00:41:15.232301959Z 	at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:153)
swarm-detector_swarm-detector_14 | 2019-04-06T00:41:15.232306970Z 	at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:282)
swarm-detector_swarm-detector_14 | 2019-04-06T00:41:15.232312001Z 	at org.apache.http.impl.io.ChunkedInputStream.getChunkSize(ChunkedInputStream.java:264)
swarm-detector_swarm-detector_14 | 2019-04-06T00:41:15.232316834Z 	at org.apache.http.impl.io.ChunkedInputStream.nextChunk(ChunkedInputStream.java:225)
swarm-detector_swarm-detector_14 | 2019-04-06T00:41:15.232321163Z 	at org.apache.http.impl.io.ChunkedInputStream.read(ChunkedInputStream.java:184)
swarm-detector_swarm-detector_14 | 2019-04-06T00:41:15.232326029Z 	at org.apache.http.conn.EofSensorInputStream.read(EofSensorInputStream.java:137)
swarm-detector_swarm-detector_14 | 2019-04-06T00:41:15.232330887Z 	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._loadMore(UTF8StreamJsonParser.java:205)
swarm-detector_swarm-detector_14 | 2019-04-06T00:41:15.232336005Z 	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._skipWSOrEnd2(UTF8StreamJsonParser.java:2974)
swarm-detector_swarm-detector_14 | 2019-04-06T00:41:15.232341204Z 	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._skipWSOrEnd(UTF8StreamJsonParser.java:2969)
swarm-detector_swarm-detector_14 | 2019-04-06T00:41:15.232346169Z 	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:685)
swarm-detector_swarm-detector_14 | 2019-04-06T00:41:15.232351126Z 	at com.spotify.docker.client.EventReader.nextMessage(EventReader.java:54)
swarm-detector_swarm-detector_14 | 2019-04-06T00:41:15.232356113Z 	at com.spotify.docker.client.EventStream.computeNext(EventStream.java:45)
swarm-detector_swarm-detector_14 | 2019-04-06T00:41:15.233573904Z 	at com.spotify.docker.client.EventStream.computeNext(EventStream.java:33)
swarm-detector_swarm-detector_14 | 2019-04-06T00:41:15.233595012Z 	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:145)
swarm-detector_swarm-detector_14 | 2019-04-06T00:41:15.233600475Z 	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:140)
swarm-detector_swarm-detector_14 | 2019-04-06T00:41:15.233605440Z 	at java.util.Iterator.forEachRemaining(Iterator.java:115)
``
