### ISSUE TITLE
Client ignores DOCKER_CONFIG env var

### ISSUE THREAD

**Issue by micw** [spotify/docker-client#1151]
**Is this a BUG REPORT or FEATURE REQUEST?**:

BUG

## Description

If docker's config dir has a non default location that is set in DOCKER_CONFIG, it's ignored by the client. This causes other issues like credentials (created with "docker login") being ignored.

## How to reproduce

* export DOCKER_CONFIG=/non/default/path
* do "docker login" to some private repo
* Try to pull an image using the java client

## What do you expect

* The java client should use the credentials stored in $DOCKER_CONFIG/

## What happened instead

* The java client fails to use the credentials

## Software:

- com.spotify:docker-client:8.14.4 (via Docker JUnit rule)

## Full backtrace

```text
Caused by: com.spotify.docker.client.exceptions.DockerRequestException: Request error: POST unix://localhost:80/images/create?fromImage=****: 500, body: {"message":"Get https://docker.****: no basic auth credentials"}
	at com.spotify.docker.client.DefaultDockerClient.requestAndTail(DefaultDockerClient.java:2780)
	at com.spotify.docker.client.DefaultDockerClient.pull(DefaultDockerClient.java:1326)
	at com.spotify.docker.client.DefaultDockerClient.pull(DefaultDockerClient.java:1303)
	at com.spotify.docker.client.DefaultDockerClient.pull(DefaultDockerClient.java:1297)
	at com.arakelian.docker.junit.Container.pullImage(Container.java:527)
```
(URL and image name removed)

Running docker pull for the same image works.

## Extra Info

* this breaks the usage of the client with jenkins pipelines and private registries since jenkins uses a temporary a non-default config path
* There's a pending PR addressing this issue: https://github.com/spotify/docker-client/pull/1145

**Comment by micw** [comment]
Should be fixed because the PR is merged.
