### ISSUE TITLE
Spotify unable to pull a large docker image from docker hub 

### ISSUE THREAD

**Issue by Manku02** [spotify/docker-client#1152]
I am hitting an weird read timeout exception while trying to download large docker images in Amazon EC2 instance using spotify API. This issue is only happening on windows machine( the same application setup I have in Linux machine and it is working fine)  in case of large images (>2 GB) but the same setup works fine with Linux and small windows docker images, following are the logs - 

```
=2019-04-16 08:01:16,791 [pool-1-thread-1] INFO [scan.microservice.ScannerService]  - Docker image found
=2019-04-16 08:01:16,904 [pool-1-thread-1] INFO [scan.microservice.ScannerService]  - 7869f6d3-790b-4893-820a-4d4672937362, Started to pull image : aujascodesigningsupport/aujasdocker:poweruat
=2019-04-16 08:09:41,408 [pool-1-thread-1] ERROR [scan.microservice.ScannerService]  - Failed to remove docker image.
com.spotify.docker.client.exceptions.ImageNotFoundException: Image not found: aujascodesigningsupport/aujasdocker:poweruat
	at com.spotify.docker.client.DefaultDockerClient.removeImage(DefaultDockerClient.java:1451)
	at aujas.code.scan.microservice.ScannerService.removeImage(ScannerService.java:266)
	at aujas.code.scan.microservice.ScannerService.getDockerImage(ScannerService.java:259)
	at aujas.code.scan.microservice.ScannerService.getInputStreamToScan(ScannerService.java:106)
	at aujas.code.scan.microservice.McAfeeScannerService.scan(McAfeeScannerService.java:88)
	at aujas.code.scan.microservice.ScannerService.streamScan(ScannerService.java:91)
	at aujas.code.scan.microservice.ScanWorker.run(ScanWorker.java:57)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.spotify.docker.client.exceptions.DockerRequestException: Request error: DELETE http://localhost:2375/images/aujascodesigningsupport/aujasdocker:poweruat?force=true&noprune=false: 404, body: {"message":"No such image: aujascodesigningsupport/aujasdocker:poweruat"}

	at com.spotify.docker.client.DefaultDockerClient.propagate(DefaultDockerClient.java:2691)
	at com.spotify.docker.client.DefaultDockerClient.request(DefaultDockerClient.java:2620)
	at com.spotify.docker.client.DefaultDockerClient.removeImage(DefaultDockerClient.java:1447)
	... 9 more
Caused by: javax.ws.rs.NotFoundException: HTTP 404 Not Found
	at org.glassfish.jersey.client.JerseyInvocation.convertToException(JerseyInvocation.java:1008)
	at org.glassfish.jersey.client.JerseyInvocation.translate(JerseyInvocation.java:877)
	at org.glassfish.jersey.client.JerseyInvocation.access$800(JerseyInvocation.java:92)
	at org.glassfish.jersey.client.JerseyInvocation$6.completed(JerseyInvocation.java:836)
	at org.glassfish.jersey.client.ClientRuntime.processResponse(ClientRuntime.java:198)
	at org.glassfish.jersey.client.ClientRuntime.access$300(ClientRuntime.java:79)
	at org.glassfish.jersey.client.ClientRuntime$2.run(ClientRuntime.java:180)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:340)
	at org.glassfish.jersey.client.ClientRuntime$3.run(ClientRuntime.java:210)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 3 more
=2019-04-16 08:09:41,564 [pool-1-thread-1] INFO [scan.microservice.ScannerService]  - 7869f6d3-790b-4893-820a-4d4672937362, Deleting docker downloaded dir: C:\Users\ADMINI~1\AppData\Local\Temp\2\cs-scanner-4819168627723572395
=2019-04-16 08:09:41,564 [pool-1-thread-1] INFO [scan.microservice.ScannerService]  - 7869f6d3-790b-4893-820a-4d4672937362, Downloaded docker tar file, so deleting it.
=2019-04-16 08:09:41,986 [pool-1-thread-1] ERROR [scan.microservice.ScanWorker]  - Exception while scanning 7869f6d3-790b-4893-820a-4d4672937362, retrying.. attempt :0
com.spotify.docker.client.exceptions.DockerTimeoutException: Timeout: POST http://localhost:2375/images/create?fromImage=aujascodesigningsupport%2Faujasdocker&tag=poweruat
	at com.spotify.docker.client.ProgressStream.hasNextMessage(ProgressStream.java:55)
	at com.spotify.docker.client.ProgressStream.tail(ProgressStream.java:73)
	at com.spotify.docker.client.DefaultDockerClient.pull(DefaultDockerClient.java:1251)
	at aujas.code.scan.microservice.ScannerService.getDockerImage(ScannerService.java:225)
	at aujas.code.scan.microservice.ScannerService.getInputStreamToScan(ScannerService.java:106)
	at aujas.code.scan.microservice.McAfeeScannerService.scan(McAfeeScannerService.java:88)
	at aujas.code.scan.microservice.ScannerService.streamScan(ScannerService.java:91)
	at aujas.code.scan.microservice.ScanWorker.run(ScanWorker.java:57)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:139)
	at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:155)
	at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:284)
	at org.apache.http.impl.io.ChunkedInputStream.getChunkSize(ChunkedInputStream.java:266)
	at org.apache.http.impl.io.ChunkedInputStream.nextChunk(ChunkedInputStream.java:227)
	at org.apache.http.impl.io.ChunkedInputStream.read(ChunkedInputStream.java:186)
	at org.apache.http.conn.EofSensorInputStream.read(EofSensorInputStream.java:137)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
	at java.io.FilterInputStream.read(FilterInputStream.java:133)
	at java.io.FilterInputStream.read(FilterInputStream.java:133)
	at org.glassfish.jersey.message.internal.EntityInputStream.read(EntityInputStream.java:106)
	at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream.read(ReaderInterceptorExecutor.java:302)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.loadMore(UTF8StreamJsonParser.java:180)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._skipWSOrEnd2(UTF8StreamJsonParser.java:2904)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._skipWSOrEnd(UTF8StreamJsonParser.java:2899)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:692)
	at com.fasterxml.jackson.databind.MappingIterator.hasNextValue(MappingIterator.java:240)
	at com.spotify.docker.client.ProgressStream.hasNextMessage(ProgressStream.java:53)
	... 10 more
```

**Comment by Manku02** [comment]
I am seeing error in Microsoft-Windows-Hyper-V-VMMS is this somehow contributing to above exception - 

The Virtual Machine Management Service failed to start the virtual machine 'MobyLinuxVM' because one of the Hyper-V components is not running (Virtual machine ID DBD14900-B3AF-4EF8-9E20-B706DE1B727B).
