### ISSUE TITLE
request to write '8192' bytes exceeds size in header of '17825792' bytes for entry

### ISSUE THREAD

**Issue by Cinzq4615** [spotify/docker-client#1154]
java.io.IOException: request to write '8192' bytes exceeds size in header of '17825792' bytes for entry 'config_generate'
	at org.apache.commons.compress.archivers.tar.TarArchiveOutputStream.write(TarArchiveOutputStream.java:377)
	at java.nio.file.Files.copy(Files.java:2909)
	at java.nio.file.Files.copy(Files.java:3069)
	at com.spotify.docker.client.CompressedDirectory$Visitor.visitFile(CompressedDirectory.java:303)
	at com.spotify.docker.client.CompressedDirectory$Visitor.visitFile(CompressedDirectory.java:253)
	at java.nio.file.Files.walkFileTree(Files.java:2670)
	at com.spotify.docker.client.CompressedDirectory.create(CompressedDirectory.java:115)
	at com.spotify.docker.client.DefaultDockerClient.build(DefaultDockerClient.java:1408)
	at com.spotify.docker.client.DefaultDockerClient.build(DefaultDockerClient.java:1383)
	at com.spotify.docker.client.DefaultDockerClient.build(DefaultDockerClient.java:1369)
	at com.kedacom.dolphin.docker.operator.DockerCommon.buildDockerImage(DockerCommon.java:131)
	at com.kedacom.dolphin.release.docker.service.impl.DockerServiceImpl.createImage(DockerServiceImpl.java:191)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.aop.interceptor.AsyncExecutionInterceptor$1.call(AsyncExecutionInterceptor.java:115)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
	Suppressed: java.io.IOException: This archives contains unclosed entries.
		at org.apache.commons.compress.archivers.tar.TarArchiveOutputStream.finish(TarArchiveOutputStream.java:220)
		at org.apache.commons.compress.archivers.tar.TarArchiveOutputStream.close(TarArchiveOutputStream.java:236)
		at com.spotify.docker.client.CompressedDirectory.create(CompressedDirectory.java:120)
		... 15 common frames omitted

**Comment by jamesdobson** [comment]
We're also experiencing this problem intermittently in our builds. The archive looks fine and expands correctly using CLI commands on developer local machines.

@Cinzq4615 did you manage to work around the issue?

**Comment by JamesSpaniak** [comment]
@Cinzq4615 @jamesdobson Was there a workaround? Im getting this issue in deployed instances, but not locally. It works if i write using one buffer (instead of incrementally adding it 8192 at a time), but obviously loading it all in one go is not feasible for larger files.
