### ISSUE TITLE
Cannot share host device with container

### ISSUE THREAD

**Issue by zied-guesmi** [spotify/docker-client#1162]
## Description

Hi,

 I'm trying to share the device /dev/isgx with a container but I'm getting an error from docker daemon.

## How to reproduce
On a machine that supports intel SGX, try sharing the device /dev/isgx and start the container:
```
Device device = Device.builder().pathOnHost("/dev/isgx").pathInContainer("/dev/isgx").build();
return hostConfigBuilder.devices(device).build();
```

## What do you expect
The device /dev/isgx should be shared with the container.

## What happened instead
I had this error from docker daemon:
```
      com.spotify.docker.client.exceptions.DockerRequestException: Request error:
      POST unix://localhost:80/containers/07d07533ff582dea16c5c7bf7a0787b1df2c51da50773976a42f125b982a9b60/start:500,
      body: {"message":"OCI runtime create failed: device access at 8 field cannot be empty: unknown"}
```

## Software:

- docker version:
```
Client:
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.6
 Git commit:        6247962
 Built:             Sun Feb 10 04:13:50 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 03:42:13 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

- Spotify's docker-client version: `docker-client:8.13.1`

## Full backtrace

```text
      com.spotify.docker.client.exceptions.DockerRequestException: Request error: POST
      unix://localhost:80/containers/07d07533ff582dea16c5c7bf7a0787b1df2c51da50773976a42f125b982 a9b60/start: 500,
      body: {"message":"OCI runtime create failed: device access at 8 field cannot be empty: unknown"}
      at com.spotify.docker.client.DefaultDockerClient.propagate(DefaultDockerClient.java:2820)
      at com.spotify.docker.client.DefaultDockerClient.request(DefaultDockerClient.java:2714)
      at com.spotify.docker.client.DefaultDockerClient.containerAction(DefaultDockerClient.java:763)
      at com.spotify.docker.client.DefaultDockerClient.containerAction(DefaultDockerClient.java:748)
      at com.spotify.docker.client.DefaultDockerClient.startContainer(DefaultDockerClient.java:743)
      at com.iexec.worker.docker.CustomDockerClient.startContainer(CustomDockerClient.java:137)
```

**Comment by zied-guesmi** [comment]
The problem was with the permission on the device. Adding `.cgroupPermissions("rwm")` to the device object solved the issue.

**Comment by balaspidy** [comment]
> The problem was with the permission on the device. Adding `.cgroupPermissions("rwm")` to the device object solved the issue.

how do u did that

**Comment by zguesmi** [comment]
> 
> how do u did that

When you create the device object you need to specify permissions
```
Device device = Device.builder()
        .pathOnHost("/dev/isgx")
        .pathInContainer("/dev/isgx")
        .cgroupPermissions("rwm")  <---
        .build();
```
