### ISSUE TITLE
Passing FileInputStream respectively tar file to custom build method doesn't work (?)

### ISSUE THREAD

**Issue by stozk** [spotify/docker-client#117]
Hi,

I'm trying to add the docker-client to an application (interface) which is integrated into another application (interface) via maven dependencies.

I've added a second build method (buildFromFile) which builds a container from a tar archive containing all the files and the dockerfile instead of building a tar file from a directory as it's currently implemented.

So this works:

docker-client TestClient: works

app1 TestClient --> client app: works

but:

app2 TestClient --> app1 --> client: this error:

> com.spotify.docker.client.DockerException: java.util.concurrent.ExecutionException: javax.ws.rs.ProcessingException: Unable to invoke request
	at com.spotify.docker.client.DefaultDockerClient.propagate(DefaultDockerClient.java:1094)
	at com.spotify.docker.client.DefaultDockerClient.request(DefaultDockerClient.java:1034)
	at com.spotify.docker.client.DefaultDockerClient.buildFromFile(DefaultDockerClient.java:810)
	at com.spotify.docker.client.DefaultDockerClient.buildFromFile(DefaultDockerClient.java:735)
	at docker.DockerImageMgmt.addImage(DockerImageMgmt.java:66)
	at docker.DockerIaaSInterface.addImage(DockerIaaSInterface.java:42)
	at TestClient.main(TestClient.java:30)
Caused by: java.util.concurrent.ExecutionException: javax.ws.rs.ProcessingException: Unable to invoke request
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:188)
	at com.spotify.docker.client.DefaultDockerClient.request(DefaultDockerClient.java:1032)
	... 5 more
Caused by: javax.ws.rs.ProcessingException: Unable to invoke request
	at org.jboss.resteasy.client.jaxrs.engines.ApacheHttpClient4Engine.invoke(ApacheHttpClient4Engine.java:287)
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.invoke(ClientInvocation.java:407)
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.invoke(ClientInvocation.java:442)
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation$2.call(ClientInvocation.java:477)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: javax.ws.rs.ProcessingException: could not find writer for content-type application/tar type: java.io.File
	at org.jboss.resteasy.core.interception.ClientWriterInterceptorContext.throwWriterNotFoundException(ClientWriterInterceptorContext.java:40)
	at org.jboss.resteasy.core.interception.AbstractWriterInterceptorContext.getWriter(AbstractWriterInterceptorContext.java:138)
	at org.jboss.resteasy.core.interception.AbstractWriterInterceptorContext.proceed(AbstractWriterInterceptorContext.java:117)
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.writeRequestBody(ClientInvocation.java:341)
	at org.jboss.resteasy.client.jaxrs.engines.ApacheHttpClient4Engine.writeRequestBodyToOutputStream(ApacheHttpClient4Engine.java:558)
	at org.jboss.resteasy.client.jaxrs.engines.ApacheHttpClient4Engine.buildEntity(ApacheHttpClient4Engine.java:524)
	at org.jboss.resteasy.client.jaxrs.engines.ApacheHttpClient4Engine.loadHttpMethod(ApacheHttpClient4Engine.java:423)
	at org.jboss.resteasy.client.jaxrs.engines.ApacheHttpClient4Engine.invoke(ApacheHttpClient4Engine.java:281)
	... 7 more

I have no idea how to fix this... googling for "could not find writer for content-type application/tar type: java.io.File" doesn't bring up anything. 

Does anyone know what might be causing this?

BR
Daniel

**Comment by rohansingh** [comment]
Just a first guess, but perhaps the "app1" build process is stripping out whatever class is responsible for serializing a `File`? Somehow that class doesn't seem to exist according to "app2".

**Comment by stozk** [comment]
Yeah I have a slight suspicion that the maven build process might be causing this, because the only thing  I've found about similar issues seems to have been solved by doind a shaded build.
I'll look into this, if you're initial thought was about missing dependencies this might be really the case.
Thanks.

**Comment by rohansingh** [comment]
Sure thing. Note that [we use shading in the build for docker-client itself](https://github.com/spotify/docker-client/blob/master/pom.xml#L285). The docker-client JAR includes a bunch of its dependencies, with some of them renamed.

This is to avoid collisions between the Jersey 2.x / JAX-RS stuff we use and other libraries that consumers might be using (eg., Jersey 1.x). In theory this shouldn't matter as long as any intermediate library faithfully reproduces all our dependencies, but you never know with shading.

**Comment by stozk** [comment]
I've finally figured out the problem.
I used a docker registry api client which is currently based on resteasy instead of jersey.
Those two dependencies don't like each other ;-)
