### ISSUE TITLE
Win7 support for Docker v1.6 & API 1.18?

### ISSUE THREAD

**Issue by psmet01** [spotify/docker-client#166]
Im not sure if this is the right place to post this but I can't find anywhere else, so here goes:

I ran the Boot2Docker Windows installer on Win7 64 bit. I can run docker commands just fine. Then I pulled the latest Docker-client master branch (v2.7.22) and ran it in Eclipse Java IDE. In DefaultDockerClient I changed DEFAULT_HOST and DEFAULT_PORT to the values which Docker seemed to be using https://docs.docker.com/installation/images/windows-boot2docker-cmd.png (the default values were giving me localhost:2375 connection refused errors).

I tried running the following commands: 

``` java
final DockerClient docker = DefaultDockerClient.fromEnv().build();
List<ImageSearchResult> results = docker.searchImages("ubuntu");
```

My result is an Apache error going: 

```
Exception in thread "main" com.spotify.docker.client.DockerException: java.util.concurrent.ExecutionException: javax.ws.rs.ProcessingException: org.apache.http.client.ClientProtocolException
    at com.spotify.docker.client.DefaultDockerClient.propagate(DefaultDockerClient.java:1109)
    at com.spotify.docker.client.DefaultDockerClient.request(DefaultDockerClient.java:1028)
    at com.spotify.docker.client.DefaultDockerClient.searchImages(DefaultDockerClient.java:653)
    at com.spotify.docker.client.main.Test.main(Test.java:28)
Caused by: java.util.concurrent.ExecutionException: javax.ws.rs.ProcessingException: org.apache.http.client.ClientProtocolException
    at jersey.repackaged.com.google.common.util.concurrent.AbstractFuture$Sync.getValue(AbstractFuture.java:306)
    at jersey.repackaged.com.google.common.util.concurrent.AbstractFuture$Sync.get(AbstractFuture.java:293)
    at jersey.repackaged.com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:116)
    at com.spotify.docker.client.DefaultDockerClient.request(DefaultDockerClient.java:1026)
    ... 2 more
Caused by: javax.ws.rs.ProcessingException: org.apache.http.client.ClientProtocolException
    at org.glassfish.jersey.apache.connector.ApacheConnector.apply(ApacheConnector.java:517)
    at org.glassfish.jersey.apache.connector.ApacheConnector$1.run(ApacheConnector.java:527)
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
    at java.util.concurrent.FutureTask.run(Unknown Source)
    at jersey.repackaged.com.google.common.util.concurrent.MoreExecutors$SameThreadExecutorService.execute(MoreExecutors.java:293)
    at jersey.repackaged.com.google.common.util.concurrent.AbstractListeningExecutorService.submit(AbstractListeningExecutorService.java:49)
    at jersey.repackaged.com.google.common.util.concurrent.AbstractListeningExecutorService.submit(AbstractListeningExecutorService.java:45)
    at org.glassfish.jersey.apache.connector.ApacheConnector.apply(ApacheConnector.java:523)
    at org.glassfish.jersey.client.ClientRuntime$1.run(ClientRuntime.java:169)
    at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
    at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
    at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
    at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
    at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
    at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:320)
    at org.glassfish.jersey.client.ClientRuntime$2.run(ClientRuntime.java:201)
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
    at java.util.concurrent.FutureTask.run(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
Caused by: org.apache.http.client.ClientProtocolException
    at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:186)
    at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72)
    at org.glassfish.jersey.apache.connector.ApacheConnector.apply(ApacheConnector.java:469)
    ... 20 more
Caused by: org.apache.http.ProtocolException: The server failed to respond with a valid HTTP response
    at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:151)
    at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57)
    at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:260)
    at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:161)
    at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:153)
    at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:271)
    at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:123)
    at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:254)
    at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:195)
    at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:86)
    at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:108)
    at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
    ... 22 more
```

I also tried it using the v2.7.21 client version but I had the same errors. Any ideas how to solve and is it even possible to work from a Win7 environment? Thanks!

**Comment by davidxia** [comment]
@psmet01 Sorry for the long delay. Did you try setting an environment variable for `DOCKER_CERT_PATH` to give your docker server SSL/TLS certificates? [This line in the docker-client][1] will check if that variable is set and then speak HTTPS to the `DOCKER_HOST` if it is.

Instead of editing the java code, I recommend setting env vars inside Eclipse to the same things in that png you mentioned. So something like:

```
DOCKER_CERT_PATH=/Users/dxia/.boot2docker/certs/boot2docker-vm
DOCKER_HOST=tcp://192.168.59.103:2376
DOCKER_TLS_VERIFY=1
```

  [1]: https://github.com/spotify/docker-client/blob/master/src/main/java/com/spotify/docker/client/DefaultDockerClient.java#L1154

**Comment by davidxia** [comment]
@psmet01 Do you still have this issue or can I close this?
