### ISSUE TITLE
Can not work on boot2docker 1.6 ?

### ISSUE THREAD

**Issue by stream1984** [spotify/docker-client#167]
i try to run with above code 

```java
DockerClient docker = DefaultDockerClient.fromEnv().build();
System.out.println(docker.info());
```

version is 2.7.21

==Exception
```
Exception in thread "main" com.spotify.docker.client.DockerTimeoutException: Timeout: GET http://192.168.59.103:2375/v1.12/containers/json
	at com.spotify.docker.client.DefaultDockerClient.propagate(DefaultDockerClient.java:1104)
	at com.spotify.docker.client.DefaultDockerClient.request(DefaultDockerClient.java:1028)
	at com.spotify.docker.client.DefaultDockerClient.listContainers(DefaultDockerClient.java:311)
	at as.leap.cloudcode.manager.impl.TestDockerClient.main(TestDockerClient.java:14)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
Caused by: java.util.concurrent.ExecutionException: javax.ws.rs.ProcessingException: java.net.SocketTimeoutException: Read timed out
	at jersey.repackaged.com.google.common.util.concurrent.AbstractFuture$Sync.getValue(AbstractFuture.java:306)
	at jersey.repackaged.com.google.common.util.concurrent.AbstractFuture$Sync.get(AbstractFuture.java:293)
	at jersey.repackaged.com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:116)
	at com.spotify.docker.client.DefaultDockerClient.request(DefaultDockerClient.java:1026)
	... 7 more
Caused by: javax.ws.rs.ProcessingException: java.net.SocketTimeoutException: Read timed out
	at org.glassfish.jersey.apache.connector.ApacheConnector.apply(ApacheConnector.java:517)
	at org.glassfish.jersey.apache.connector.ApacheConnector$1.run(ApacheConnector.java:527)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at jersey.repackaged.com.google.common.util.concurrent.MoreExecutors$SameThreadExecutorService.execute(MoreExecutors.java:293)
	at jersey.repackaged.com.google.common.util.concurrent.AbstractListeningExecutorService.submit(AbstractListeningExecutorService.java:49)
	at jersey.repackaged.com.google.common.util.concurrent.AbstractListeningExecutorService.submit(AbstractListeningExecutorService.java:45)
	at org.glassfish.jersey.apache.connector.ApacheConnector.apply(ApacheConnector.java:523)
	at org.glassfish.jersey.client.ClientRuntime$1.run(ClientRuntime.java:169)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:320)
	at org.glassfish.jersey.client.ClientRuntime$2.run(ClientRuntime.java:201)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.read(SocketInputStream.java:150)
	at java.net.SocketInputStream.read(SocketInputStream.java:121)
	at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:136)
	at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:152)
	at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:270)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:140)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57)
	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:260)
	at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:161)
	at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:153)
	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:271)
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:123)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:254)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:195)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:86)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:108)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72)
	at org.glassfish.jersey.apache.connector.ApacheConnector.apply(ApacheConnector.java:469)
	... 20 more
```

**Comment by stream1984** [comment]
I click the link  http://192.168.59.103:2375/v1.12/containers/json 
and it could get information on my Chrome.

**Comment by psmet01** [comment]
Im having problems with v1.6 also. Can you confirm that your code was working for v1.5? Then it should definitely be a 1.6 bug and we will probably just have to wait for an update

**Comment by stream1984** [comment]
I can confirm that exception could be reproducer in boot2docker 1.6 but not docker 1.6
That would be working try to make connect to docker 1.6 which on physics machine instead of VirtualBox with boot2docker 1.6

**Comment by davidxia** [comment]
@stream1984 @psmet01 Is this still an issue for you?

docker-client version 2.7.21 works for me on my Mac with boot2docker 1.6.0 and these environment variables

```
DOCKER_CERT_PATH=/Users/dxia/.boot2docker/certs/boot2docker-vm
DOCKER_HOST=tcp://192.168.59.103:2376
DOCKER_TLS_VERIFY=1
```

and on ubuntu 14.04 with docker 1.6.2 with these env vars

```
DOCKER_HOST=tcp://127.0.0.1:2375
```

**Comment by stream1984** [comment]
it is works now
