### ISSUE TITLE
ClientBuilder happend ClassCastException

### ISSUE THREAD

**Issue by yangtao309** [spotify/docker-client#212]
```
Exception in thread "main" java.lang.LinkageError: ClassCastException: attempting to castjar:file:/micro-service-blog/target/micro-service-blog.jar!/com/spotify/docker/client/shaded/javax/ws/rs/client/ClientBuilder.class to jar:file:/micro-service-blog/target/micro-service-blog.jar!/com/spotify/docker/client/shaded/javax/ws/rs/client/ClientBuilder.class
	at com.spotify.docker.client.shaded.javax.ws.rs.client.ClientBuilder.newBuilder(ClientBuilder.java:97)
	at com.spotify.docker.client.shaded.javax.ws.rs.client.ClientBuilder.newClient(ClientBuilder.java:126)
	at com.spotify.docker.client.DefaultDockerClient.<init>(DefaultDockerClient.java:215)
	at com.spotify.docker.client.DefaultDockerClient.<init>(DefaultDockerClient.java:171)
	at com.spotify.docker.client.DefaultDockerClient.<init>(DefaultDockerClient.java:163)
	at com.shuyun.soa.blog.Application.main(Application.java:20)
```
in my pom.xml
```
<dependency>
            <groupId>com.spotify</groupId>
            <artifactId>docker-client</artifactId>
            <version>2.7.7</version>
        </dependency>

        <dependency>
            <groupId>com.spotify</groupId>
            <artifactId>docker-client</artifactId>
            <classifier>shaded</classifier>
            <version>2.7.7</version>
        </dependency>
```

in my main method:
```
public static void main(String[] args) throws Exception {
        final DockerClient docker = new DefaultDockerClient("unix:///var/run/docker.sock");

        List<Container>  containers = docker.listContainers();
        for (Container container: containers) {
            System.out.print(container.id());
        }

        // new Application().run(args);
    }

```
what happend? can you help me !

**Comment by rgrunber** [comment]
This seems like a problem with classloader hierarchy. More than one classloader is loading ClientBuilder and the instances are being used together in the same code, hence the ClassCastException. Without knowing more about how the code is being run, or the environment, it'd be difficult to diagnose such issues, but maybe someone else can comment.

You also shouldn't need to depend on both the shaded and non-shaded versions of docker-client, just one or the other, depending on whether you provide all the docker-client dependencies yourself, or expect them provided for you.
