### ISSUE TITLE
Error: java.lang.NoSuchMethodError: org.glassfish.jersey.internal.util.collection.Values.lazy  

### ISSUE THREAD

**Issue by Shaileshk-egnaroinc** [spotify/docker-client#224]
I had include spotify/docker-client project as a jar file in my java play framework project.After that I had include hk2-api-2.1.46.jar ,jersey-client-2.10.4.jar,jersey-common-2.0-m13.jar,jersey-media-json-jackson-2.0-m07-1.jar respective jar files in my project.When I run my project it gives error -

```
Error-
java.lang.NoSuchMethodError: org.glassfish.jersey.internal.util.collection.Values.lazy(Lorg/glassfish/jersey/internal/util/collection/Value;)Lorg/glassfish/jersey/internal/util/collection/LazyValue;
	at org.glassfish.jersey.client.ClientConfig$State.<init>(ClientConfig.java:116) ~[jersey-client-2.10.4.jar:na]
	at org.glassfish.jersey.client.ClientConfig.<init>(ClientConfig.java:457) ~[jersey-client-2.10.4.jar:na]
	at org.glassfish.jersey.client.ClientConfig.<init>(ClientConfig.java:466) ~[jersey-client-2.10.4.jar:na]
	at com.spotify.docker.client.DefaultDockerClient.<clinit>(DefaultDockerClient.java:127) ~[dockerClient.jar:na]
	at Automattercontrollers.Dockercontroller.pong(Dockercontroller.java:613) ~[classes/:na]
	at Automatter.Routes$$anonfun$routes$1$$anonfun$applyOrElse$28$$anonfun$apply$28.apply(routes_routing.scala:369) ~[classes/:na]
	at Automatter.Routes$$anonfun$routes$1$$anonfun$applyOrElse$28$$anonfun$apply$28.apply(routes_routing.scala:369) ~[classes/:na]
	at play.core.Router$HandlerInvoker$$anon$7$$anon$2.invocation(Router.scala:183) ~[play_2.10-2.2.2.jar:2.2.2]
	at play.core.Router$Routes$$anon$1.invocation(Router.scala:377) ~[play_2.10-2.2.2.jar:2.2.2]
	at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:56) ~[play_2.10-2.2.2.jar:2.2.2]
	at play.core.j.JavaAction$$anon$3.apply(JavaAction.scala:91) ~[play_2.10-2.2.2.jar:2.2.2]
	at play.core.j.JavaAction$$anon$3.apply(JavaAction.scala:90) ~[play_2.10-2.2.2.jar:2.2.2]
	at play.core.j.FPromiseHelper$$anonfun$flatMap$1.apply(FPromiseHelper.scala:82) ~[play_2.10-2.2.2.jar:2.2.2]
	at play.core.j.FPromiseHelper$$anonfun$flatMap$1.apply(FPromiseHelper.scala:82) ~[play_2.10-2.2.2.jar:2.2.2]
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251) ~[scala-library.jar:na]
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:249) ~[scala-library.jar:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) ~[scala-library.jar:na]
	at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:37) ~[play_2.10-2.2.2.jar:2.2.2]
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:42) ~[akka-actor_2.10-2.2.0.jar:2.2.0]
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:386) [akka-actor_2.10-2.2.0.jar:2.2.0]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library.jar:na]
```       

Could you peoples resolve this error ?
Thanks in advance

**Comment by rgrunber** [comment]
You are using unsupported versions of dependencies for docker-client, as well as not maintaining a consistent version among the dependencies that come from the same project (eg. jersey). Have a look at the [project pom](https://github.com/spotify/docker-client/blob/9df2e400d241191d1b214c52fd3d68b44890d995/pom.xml#L81) for some info on the recommended dependency versions to use.

The oldest version of Jersey that would be expected to work with this project is 2.13. If you need to use an older version it might be possible, but you're also using different versions among the Jersey project dependencies (2.10.4, 2.0-m13, 2.0-m07-1) which can definitely cause issues.

As a simple way of testing, you could just replace the versions listed in the pom.xml with the versions you'd like to use and see if the project at least compiles and runs the tests.

**Comment by davidxia** [comment]
@rgrunber thanks for answering. Closing as this sounds like user error.

**Comment by Shaileshk-egnaroinc** [comment]
Thank you
