### ISSUE TITLE
issue on Connection pool size

### ISSUE THREAD

**Issue by Runomu** [spotify/docker-client#231]
im using Docker-client API in EE Platform to manage a bundle of containers on remote machine. Java SE Client running in Docker instance in order to process a work.  After Processing is done and get a response from se client, im restarting container ,let it wait 15 seconds in a separate Thread and pause that container after time is up. But there is a problem, when i pause containers in multi threads through DefaultDockerClient or DockerClient. Although im setting connectionpoolsize on 1000, im getting following exception while pausing a worker. i have been debugging for hours for PoolingHttpClientConnectionManager whether its set. and yes. its already set on 1000. But it doesnt work for parallel request ? Does anyone has an idea, why it doesnt work ? 

Caused by: java.util.concurrent.ExecutionException: javax.ws.rs.ProcessingException: Unable to invoke request
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:188)
	at com.spotify.docker.client.DefaultDockerClient.request(DefaultDockerClient.java:1019)
	... 9 more
Caused by: javax.ws.rs.ProcessingException: Unable to invoke request
	at org.jboss.resteasy.client.jaxrs.engines.ApacheHttpClient4Engine.invoke(ApacheHttpClient4Engine.java:287)
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.invoke(ClientInvocation.java:407)
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.invoke(ClientInvocation.java:442)
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation$2.call(ClientInvocation.java:477)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: Invalid use of BasicClientConnManager: connection still allocated.
Make sure to release the connection before allocating another one.
	at org.apache.http.util.Asserts.check(Asserts.java:34)
	at org.apache.http.impl.conn.BasicClientConnectionManager.getConnection(BasicClientConnectionManager.java:160)
	at org.apache.http.impl.conn.BasicClientConnectionManager$1.getConnection(BasicClientConnectionManager.java:142)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:423)
	at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:863)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:57)
	at org.jboss.resteasy.client.jaxrs.engines.ApacheHttpClient4Engine.invoke(ApacheHttpClient4Engine.java:283)

**Comment by Runomu** [comment]
Do I have to use client in synchronized block ?

**Comment by grexe** [comment]
I've also experienced synchronisation errors inside the docker api in apache httpcommons, but the docker client tests suggest it's not necessary to synchronise client calls... What's the official word on this? Please comment before closing tickets @Runomu
