### ISSUE TITLE
LogStream.computeNext throws an exception EOFException despite of working container

### ISSUE THREAD

**Issue by keinesorgen** [spotify/docker-client#353]
My Docker container has dockered the sipp application. When I run it from docker command tool, 

`docker run -t localhost:5000/application:v2 /data/go.sh`

I can see the continuous output.

But when I run the java code

```
@Test
    public void testMe() throws DockerException, InterruptedException {
        try (DockerClient docker = DefaultDockerClient.builder()
                .uri(URI.create("http://docker.my.com:2375"))
                .build()) {
 
            ContainerConfig containerConfig = ContainerConfig.builder()
                    .image("localhost:5000/application:v2")
                    .attachStdout(true)
                    .tty(true)
                    .cmd("/data/go.sh")
                    .build();

            ContainerCreation containerCreation = docker.createContainer(containerConfig);
            docker.startContainer(containerCreation.id());
            LogStream logStream = docker.logs(containerCreation.id(), DockerClient.LogsParameter.STDOUT);

            while (logStream.hasNext()) {
                System.out.println("LINE: " + logStream.next());
            }
        }
    }
```

it performs the running of this container. It works well at docker

`[mami@me ~]$ docker ps
CONTAINER ID        IMAGE                             COMMAND                  CREATED             STATUS              PORTS                          NAMES
ccf9eb647afd        localhost:5000/application:v2   "/data/go.sh"            9 seconds ago       Up 8 seconds           modest_mclean
`

but my test throws the exception

```
java.lang.RuntimeException: java.io.EOFException: reached end of stream after reading 67 bytes; 1667330080 bytes expected
        at com.google.common.base.Throwables.propagate(Throwables.java:160)
        at com.spotify.docker.client.LogStream.computeNext(LogStream.java:69)
        at com.spotify.docker.client.LogStream.computeNext(LogStream.java:43)
        at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:143)
        at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:138)
        at com.myapplication.tests.performance.DockerTest.testMe(DockerTest.java:34)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
        at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
Caused by: java.io.EOFException: reached end of stream after reading 67 bytes; 1667330080 bytes expected
        at com.google.common.io.ByteStreams.readFully(ByteStreams.java:787)
        at com.google.common.io.ByteStreams.readFully(ByteStreams.java:766)
        at com.spotify.docker.client.LogReader.nextMessage(LogReader.java:69)
        at com.spotify.docker.client.LogStream.computeNext(LogStream.java:67)
        ... 33 more
```

When I attach to this working container via "docker attach" I can see the appending output.

How can I read the output with LogsStream here?

**Comment by rgrunber** [comment]
Can you try leaving out '.tty(true)' in your container configuration ? I've seen similar thing in the past and I think it's because [LogReader#nextMessage] (https://github.com/spotify/docker-client/blob/master/src/main/java/com/spotify/docker/client/LogReader.java#L47) assumes the output always has an 8 byte header where the last 4 bytes represent the size of the actual frame. When tty is enabled this isn't the case :

From (https://docs.docker.com/engine/reference/api/docker_remote_api_v1.22/#attach-to-a-container)
'When using the TTY setting is enabled in POST /containers/create , the stream is the raw data from the process PTY and client’s stdin'

If you really need TTY enabled, one possible workaround might be to get access to the raw stream and avoid the LogReader/LogStream API until it's fixed.
