### ISSUE TITLE
docker build fails when using tags with an URI

### ISSUE THREAD

**Issue by Neuw84** [spotify/docker-client#369]
## Description

Docker build goal fails when using tags with an URI. This bug makes this plugin not feasible for automatizing docker build/push using the Amazon ECR service (Registry) via maven as you will need to tag and push the image via the command line.

## How to reproduce
 Just use as image tag an URI, for example: 
``` 
 <imageTags>
      <imageTag>ikusi.com/test</imageTag>                    
 </imageTags>
```

## What do you expect

An image with it's tag should be build with the correspondent  tag.

## What happened instead

docker build maven goal fails.

## Software:

- docker version: 1.10.3
- docker-client version: 1.10.3
- docker API version: 1.22

## Full backtrace
```
Failed to execute goal com.spotify:docker-maven-plugin:0.4.2:build (default-cli) on project ikusi-base: Exception caught: Request error: POST unix://localhost:80/images/ikusi-api/tag?repo=ikusi-api:ikusi.com/test: 500: HTTP 500 Internal Server Error -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.spotify:docker-maven-plugin:0.4.2:build (default-cli) on project ikusi-base: Exception caught
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:217)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
Caused by: org.apache.maven.plugin.MojoExecutionException: Exception caught
	at com.spotify.docker.AbstractDockerMojo.execute(AbstractDockerMojo.java:115)
	at com.spotify.docker.BuildMojo.execute(BuildMojo.java:86)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
	... 19 more
Caused by: com.spotify.docker.client.DockerRequestException: Request error: POST unix://localhost:80/images/ikusi-api/tag?repo=ikusi-api:ikusi.com/test: 500
	at com.spotify.docker.client.DefaultDockerClient.propagate(DefaultDockerClient.java:1306)
	at com.spotify.docker.client.DefaultDockerClient.request(DefaultDockerClient.java:1277)
	at com.spotify.docker.client.DefaultDockerClient.tag(DefaultDockerClient.java:850)
	at com.spotify.docker.BuildMojo.tagImage(BuildMojo.java:572)
	at com.spotify.docker.BuildMojo.execute(BuildMojo.java:348)
	at com.spotify.docker.AbstractDockerMojo.execute(AbstractDockerMojo.java:113)
	... 22 more
Caused by: com.spotify.docker.client.shaded.javax.ws.rs.InternalServerErrorException: HTTP 500 Internal Server Error
	at org.glassfish.jersey.client.JerseyInvocation.convertToException(JerseyInvocation.java:1002)
	at org.glassfish.jersey.client.JerseyInvocation.translate(JerseyInvocation.java:799)
	at org.glassfish.jersey.client.JerseyInvocation.access$500(JerseyInvocation.java:91)
	at org.glassfish.jersey.client.JerseyInvocation$5.completed(JerseyInvocation.java:760)
	at org.glassfish.jersey.client.ClientRuntime.processResponse(ClientRuntime.java:197)
	at org.glassfish.jersey.client.ClientRuntime.access$300(ClientRuntime.java:78)
	at org.glassfish.jersey.client.ClientRuntime$2.run(ClientRuntime.java:179)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:340)
	at org.glassfish.jersey.client.ClientRuntime$3.run(ClientRuntime.java:209)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by mattnworb** [comment]
`HTTP 500 Internal Server Error` indicates the daemon is returning an error. You may be able to find more details in docker's logs, which are usually under `/var/log/docker.log` or /var/log/upstart/docker.log` depending on your system. It is likely not related to this plugin itself.

**Comment by johnflavin** [comment]
I tried to reproduce this error using `curl` calls to a 1.10.3 vm. 

You did a `POST` to `/images/ikusi-api/tag?repo=ikusi-api:ikusi.com/test:` and got back a 500 status. 

I can do a similar POST and also get a 500 error. 

    > POST /images/busybox/tag?repo=busybox:foo.com/bar:
    < HTTP/1.1 500 Internal Server Error 
    invalid reference format

I think the error is caused by the colons in the query param. I can remove the colons in a similar request and it works fine:

    > POST /images/busybox/tag?repo=foo.com/bar
    < HTTP/1.1 201 Created

My question is: how was your failed `POST` generated, exactly, and is there some problem there? If there is some bug—not just a configuration issue—I think it is more likely to be in the [docker maven plugin](https://github.com/spotify/docker-maven-plugin) that in the docker client.

**Comment by Neuw84** [comment]
Hi, 
The error is generated using the [docker maven plugin] (https://github.com/spotify/docker-maven-plugin) as you said.  

Running the maven docker build target triggers the error. 
For example using this config (see that I have tested too without colons but does not work either)
````
 <plugin>
                <groupId>com.spotify</groupId>
                <artifactId>docker-maven-plugin</artifactId>
                <version>0.4.2</version>
                <configuration>
                    <imageName>ikusi-api</imageName>
                    <baseImage>java</baseImage>
                    <entryPoint>["java", "-jar", "/${project.build.finalName}.jar"]</entryPoint>
                    <!-- copy the service's jar file from target into the root directory of the image --> 
                    <resources>
                        <resource>
                            <targetPath>/</targetPath>
                            <directory>${project.build.directory}</directory>
                            <include>${project.build.finalName}.jar</include>
                        </resource>
                    </resources>
                    <imageTags>
                        <imageTag>${project.version}</imageTag>
                        <imageTag>ikusi.com/test</imageTag>
                    </imageTags>
                </configuration>
            </plugin>
```

Was trying to use the plugin to push images to an Amazon ECR registry, where the url of the repository must be in the tag of the built image. 

Edit --> 
Putting the url in the image name like this: 

```
  <plugin>
                <groupId>com.spotify</groupId>
                <artifactId>docker-maven-plugin</artifactId>
                <version>0.4.2</version>
                <configuration>
                    <imageName>AWS-ACCOUNT-ID.dkr.ecr.us-east-1.amazonaws.com/ikusi-api</imageName>
                    <baseImage>java</baseImage>
                    <entryPoint>["java", "-jar", "/${project.build.finalName}.jar"]</entryPoint>
                    <!-- copy the service's jar file from target into the root directory of the image --> 
                    <resources>
                        <resource>
                            <targetPath>/</targetPath>
                            <directory>${project.build.directory}</directory>
                            <include>${project.build.finalName}.jar</include>
                        </resource>
                    </resources>
                    <imageTags>
                        <imageTag>${project.version}</imageTag>
                    </imageTags>
                </configuration>
            </plugin>
```

Run the maven goal (it builds the image), although the docker push maven goal refuses to work. Anyway as you said but this should be part of the configuration of the  [docker maven plugin] (https://github.com/spotify/docker-maven-plugin). 

Thanks!
