### ISSUE TITLE
Test failure: testEventStream

### ISSUE THREAD

**Issue by johnflavin** [spotify/docker-client#412]
## Description
Had a seemingly random test error occur in `DefaultDockerClientTest.testEventStream` (see build [420.10](https://travis-ci.org/spotify/docker-client/jobs/122327781)). I want to note it here so I (or someone else) can remember to fix it later.

The code that produced the error is
```
Event startEvent = eventStream.next();
if (!dockerApiVersionLessThan("1.22")) {
  // For some reason, version 1.22 has an extra null Event. So we read the next one.
  startEvent = eventStream.next();
}
```
It appears that, occasionally, the first event is not null. Or, at least, there is only one available event in the stream, so calling `eventStream.next()` throws an error. I've never seen that error before now and I haven't seen it again (even with [another build of the exact same code](https://travis-ci.org/spotify/docker-client/builds/122339189)), so I have no idea how to reproduce it.

The quick way to fix this would be to amend the conditional to say `if (!dockerApiVersionLessThan("1.22") && startEvent != null)` or something. The longer but better solution is to try to dig into why the event stream is returning a null event in the first place, and open an issue upstream at docker/docker.

## Software:

- docker version: `1.10.3`
- docker-client version: `3.6.9-SNAPSHOT`, being updated to `4.0.0-SNAPSHOT` in #401.

## Full backtrace

```text
testEventStream(com.spotify.docker.client.DefaultDockerClientTest)  Time elapsed: 0.813 sec  <<< ERROR!
java.util.NoSuchElementException
	at com.google.common.collect.AbstractIterator.next(AbstractIterator.java:154)
	at com.spotify.docker.client.DefaultDockerClientTest.testEventStream(DefaultDockerClientTest.java:1409)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:239)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
```

**Comment by johnflavin** [comment]
Closing after merge of #415.
