### ISSUE TITLE
Connection refused docker mac

### ISSUE THREAD

**Issue by Mouflin-Guillaume** [spotify/docker-client#442]
Hello,

I have a problem with docker-client spotify.
With this code : final DockerClient docker = DefaultDockerClient.fromEnv().build();
I have this error : 
      com.spotify.docker.client.exceptions.DockerException: java.util.concurrent.ExecutionException: javax.ws.rs.ProcessingException: org.apache.http.conn.HttpHostConnectException: Connect to localhost:2375 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused
	at com.spotify.docker.client.DefaultDockerClient.propagate(DefaultDockerClient.java:1583)
	at com.spotify.docker.client.DefaultDockerClient.request(DefaultDockerClient.java:1504)
	at com.spotify.docker.client.DefaultDockerClient.listContainers(DefaultDockerClient.java:442)
	at packageFunctions.Core$1.handleDelivery(Core.java:55)
	at com.rabbitmq.client.impl.ConsumerDispatcher$5.run(ConsumerDispatcher.java:144)
	at com.rabbitmq.client.impl.ConsumerWorkService$WorkPoolRunnable.run(ConsumerWorkService.java:99)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.util.concurrent.ExecutionException: javax.ws.rs.ProcessingException: org.apache.http.conn.HttpHostConnectException: Connect to localhost:2375 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused

     Caused by: javax.ws.rs.ProcessingException: org.apache.http.conn.HttpHostConnectException: Connect to localhost:2375 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused
	at org.glassfish.jersey.apache.connector.ApacheConnector.apply(ApacheConnector.java:481)
	at org.glassfish.jersey.apache.connector.ApacheConnector$1.run(ApacheConnector.java:491)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)

I tried to define docker_host but this doesn't work

**Comment by mattnworb** [comment]
This is addressed in https://github.com/spotify/docker-client/pull/436 which the just-released version `4.0.8` of docker-client includes.

But for older versions, you can just set the environment variable `DOCKER_HOST` to `unix:///var/run/docker.sock`.

**Comment by Mouflin-Guillaume** [comment]
I tried this but I didn't work. I tell you

**Comment by mattnworb** [comment]
How did you set it?

**Comment by Mouflin-Guillaume** [comment]
export DOCKER_HOST=unix:///var/run/docker.sock

**Comment by mattnworb** [comment]
What version of docker-client are you using? We need a lot more info to help out than "it doesn't work".

**Comment by Mouflin-Guillaume** [comment]
I use 4.0.6.

**Comment by aantono** [comment]
I have the same problem, and I'm using it via docker-maven-plugin version 0.4.10, so getting problems:
```
[ERROR] Failed to execute goal com.spotify:docker-maven-plugin:0.4.10:build (default-cli) on project admin: Exception caught: An HTTPS URI for DOCKER_HOST must be provided to use Docker client certificates -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.spotify:docker-maven-plugin:0.4.10:build (default-cli) on project admin: Exception caught
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:216)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Exception caught
	at com.spotify.docker.AbstractDockerMojo.execute(AbstractDockerMojo.java:130)
	at com.spotify.docker.BuildMojo.execute(BuildMojo.java:86)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 20 more
Caused by: java.lang.IllegalArgumentException: An HTTPS URI for DOCKER_HOST must be provided to use Docker client certificates
	at com.spotify.docker.client.DefaultDockerClient.<init>(DefaultDockerClient.java:303)
	at com.spotify.docker.client.DefaultDockerClient.<init>(DefaultDockerClient.java:294)
	at com.spotify.docker.client.DefaultDockerClient$Builder.build(DefaultDockerClient.java:1857)
	at com.spotify.docker.AbstractDockerMojo.execute(AbstractDockerMojo.java:127)
	... 23 more
```

I've tried running it as `DOCKER_TLS_VERIFY=0 DOCKER_HOST=unix:///var/run/docker.sock mvn -X docker:build`  as well as 
```
export DOCKER_TLS_VERIFY=0
export DOCKER_HOST=unix:///var/run/docker.sock
```
But neither case helped. :(

**Comment by mattnworb** [comment]
@aantono docker-client tries to use HTTPS if the `DOCKER_CERT_PATH` env var is set. I'd suggest unsetting all environment variables leftover from docker-machine as [the Docker for Mac site suggests](https://beta.docker.com/docs/mac/troubleshoot/) with `unset ${!DOCKER_*}` (or the appropriate command for your shell).

**Comment by aantono** [comment]
Looks like deleting ~/.docker directory solved the problem. :/

**Comment by venki09** [comment]
Not sure if its too late to jump into this but when I uplifted to 4.0.8 of docker-client and did 
```
    final DockerClient docker = DefaultDockerClient.fromEnv().build();
    System.out.print(docker.listContainers());
```

 I get the following exception
```
Caused by: javax.ws.rs.ProcessingException: Unable to invoke request
	at org.jboss.resteasy.client.jaxrs.engines.ApacheHttpClient4Engine.invoke(ApacheHttpClient4Engine.java:287)
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.invoke(ClientInvocation.java:436)
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.invoke(ClientInvocation.java:479)
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation$3.call(ClientInvocation.java:519)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.http.client.ClientProtocolException
	at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:867)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:57)
	at org.jboss.resteasy.client.jaxrs.engines.ApacheHttpClient4Engine.invoke(ApacheHttpClient4Engine.java:283)
	... 7 more
Caused by: org.apache.http.HttpException: Scheme 'unix' not registered.
	at org.apache.http.impl.conn.DefaultHttpRoutePlanner.determineRoute(DefaultHttpRoutePlanner.java:109)
	at org.apache.http.impl.client.DefaultRequestDirector.determineRoute(DefaultRequestDirector.java:762)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:381)
	at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:863)
	... 10 more
```

I am using docker for mac and I didn't set any environment variables related to docker.

**Comment by eliu** [comment]
Why do we have to remove `~/.docker` directory anyways? it is used by Docker for Mac and Docker Machines. there must be another way out. @mattnworb @aantono 

I got the same issue recently. I set `dockerHost` to `unix:///var/run/docker.sock` which is currently the only way to communicate with `Docker for Mac` right now.
