### ISSUE TITLE
Date parsing failure

### ISSUE THREAD

**Issue by sayarg** [spotify/docker-client#450]
## Description

We have been using 4.0.2, trying to upgrade to 5.0.1 we hit this exception when querying /info. This is happening with both docker 1.7 and 1.11. Then downgrading to 4.0.8 as thought this was a change in the 5.x branch only we hit the same issue.

Suspecting this could be related to this commit?

https://github.com/spotify/docker-client/commit/49341c70949894be8dc27690e6a7d8ff5ed40cda

But this has been there for some time, so wondering if this hasn't been an issue for anyone else.

## How to reproduce

Call DockerClient::info

## What do you expect

[Describe what do you expect to happen]

## What happened instead

Exception:

Caused by: com.fasterxml.jackson.databind.exc.InvalidFormatException: Can not construct instance of java.util.Date from String value '2016-06-03T06:57:17.4782869-04:0
0': not a valid representation (error: Failed to parse Date value '2016-06-03T06:57:17.4782869-04:00': Can not parse date "2016-06-03T06:57:17.4782869-04:00": not com
patible with any of standard forms ("yyyy-MM-dd'T'HH:mm:ss.SSSZ", "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'", "EEE, dd MMM yyyy HH:mm:ss zzz", "yyyy-MM-dd"))
 at [Source: org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream@6f7ec518; line: 1, column: 756] (through reference chain: com.spot
ify.docker.client.messages.Info["SystemTime"])
        at com.fasterxml.jackson.databind.exc.InvalidFormatException.from(InvalidFormatException.java:55)
        at com.fasterxml.jackson.databind.DeserializationContext.weirdStringException(DeserializationContext.java:907)
        at com.fasterxml.jackson.databind.deser.std.StdDeserializer._parseDate(StdDeserializer.java:787)

## Software:

- docker version: 
1.11.1-cs1

as well as:

1.7.1

- docker-client version: [Add docker-client version here]

**Comment by mattnworb** [comment]
I think the problem would have existed before the linked-to commit as the DockerDateFormat class seems to always expect a date string ending in `Z` (i.e. the timezone is always UTC). I am not sure why this assumption is made but it should not be too bad to fix in the DockerDateFormat class.

**Comment by mattnworb** [comment]
btw @sayarg can you paste the output `docker info` from the CLI from your system? On both versions if possible.

**Comment by sayarg** [comment]
@mattnworb unfortunately that's not easy as the system is somewhat isolated. i can manually post any specific field of interest in that helps?
