### ISSUE TITLE
Fix compatibility with 1.24

### ISSUE THREAD

**Issue by velo** [spotify/docker-client#465]
I'm willing to fix this, would just need some pointers

## Description
On v1-24 API copy is no longer available, returning 404

https://docs.docker.com/engine/reference/api/docker_remote_api/#v1-24-api-changes
POST /containers/{name:.*}/copy is now removed and errors out starting from this API version.

## How to reproduce
Install docker 1.12 and try to use copyContainer.  https://github.com/spotify/docker-client/blob/master/docs/user_manual.md#copy-files-or-folders-from-a-container
```
C:\Users\froederm>docker -v
Docker version 1.12.0-rc2, build 906eacd, experimental
```

## Software:

- docker version: 1.12.0-rc2
- docker-client version: 1.12.0-rc2

## Full backtrace

```
com.spotify.docker.client.exceptions.ContainerNotFoundException: Container not found: ecefb611d3273459c4d581f749161f6bc90407e0dff4dc0f3961188dd9d0df7e
	at com.spotify.docker.client.DefaultDockerClient.copyContainer(DefaultDockerClient.java:746)
	at com.vizexplorer.crm.pushpull.containers.PushPullContainer.readLog(PushPullContainer.java:81)
	at com.vizexplorer.crm.pushpull.it.PushPullLoggerRule.failed(PushPullLoggerRule.java:37)
	at org.junit.rules.TestWatcher.failedQuietly(TestWatcher.java:84)
	at org.junit.rules.TestWatcher.access$300(TestWatcher.java:46)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:62)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: com.spotify.docker.client.exceptions.DockerRequestException: Request error: POST http://localhost:2375/containers/ecefb611d3273459c4d581f749161f6bc90407e0dff4dc0f3961188dd9d0df7e/copy: 404
	at com.spotify.docker.client.DefaultDockerClient.propagate(DefaultDockerClient.java:1599)
	at com.spotify.docker.client.DefaultDockerClient.request(DefaultDockerClient.java:1549)
	at com.spotify.docker.client.DefaultDockerClient.copyContainer(DefaultDockerClient.java:740)
	... 21 more
Caused by: javax.ws.rs.NotFoundException: HTTP 404 Not Found
	at org.glassfish.jersey.client.JerseyInvocation.convertToException(JerseyInvocation.java:990)
	at org.glassfish.jersey.client.JerseyInvocation.translate(JerseyInvocation.java:799)
	at org.glassfish.jersey.client.JerseyInvocation.access$500(JerseyInvocation.java:91)
	at org.glassfish.jersey.client.JerseyInvocation$5.completed(JerseyInvocation.java:760)
	at org.glassfish.jersey.client.ClientRuntime.processResponse(ClientRuntime.java:197)
	at org.glassfish.jersey.client.ClientRuntime.access$300(ClientRuntime.java:78)
	at org.glassfish.jersey.client.ClientRuntime$2.run(ClientRuntime.java:179)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:340)
	at org.glassfish.jersey.client.ClientRuntime$3.run(ClientRuntime.java:209)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

```text
froederm@DESKTOP-ASLA2C8 ~/vizexplorer-flex-8.8.0  (8.8.2-fixes)
$ curl http://localhost:2375/containers/cfa769ff7901415acdf67f48d99b8825a199400b67bb442a0e324fb60e4bda57/copy -d '{"Resource":"/log.txt"}' -v
* STATE: INIT => CONNECT handle 0x600057840; line 1402 (connection #-5000)
* Added connection 0. The cache now contains 1 members
*   Trying ::1...
* STATE: CONNECT => WAITCONNECT handle 0x600057840; line 1455 (connection #0)
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 2375 (#0)
* STATE: WAITCONNECT => SENDPROTOCONNECT handle 0x600057840; line 1562 (connection #0)
* STATE: SENDPROTOCONNECT => DO handle 0x600057840; line 1580 (connection #0)
> POST /containers/cfa769ff7901415acdf67f48d99b8825a199400b67bb442a0e324fb60e4bda57/copy HTTP/1.1
> Host: localhost:2375
> User-Agent: curl/7.49.0
> Accept: */*
> Content-Length: 23
> Content-Type: application/x-www-form-urlencoded
>
* upload completely sent off: 23 out of 23 bytes
* STATE: DO => DO_DONE handle 0x600057840; line 1659 (connection #0)
* STATE: DO_DONE => WAITPERFORM handle 0x600057840; line 1786 (connection #0)
* STATE: WAITPERFORM => PERFORM handle 0x600057840; line 1796 (connection #0)
* HTTP 1.1 or later with persistent connection, pipelining supported
< HTTP/1.1 404 Not Found
< Content-Length: 0
< Content-Type: text/plain; charset=utf-8
< Date: Tue, 28 Jun 2016 03:47:51 GMT
* Server Docker/1.12.0-rc2 (linux) is not blacklisted
< Server: Docker/1.12.0-rc2 (linux)
<
* STATE: PERFORM => DONE handle 0x600057840; line 1955 (connection #0)
* multi_done
* Connection #0 to host localhost left intact
```

**Comment by mattnworb** [comment]
The best way to address this is probably to add a `@Deprecated` to the method and throw an exception like `UnsupportedOperationException` when the method is called *if* the api version is >= 1.24. The method should not be removed altogether from the client since it is still usable by users using older versions of docker.
