### ISSUE TITLE
DefaultDockerClient changes default unix socket port which breaks mac beta

### ISSUE THREAD

**Issue by frank-calma** [spotify/docker-client#479]
## Description

When the DefaultDockerClient builder analyzes the builder uri, it attempts to "sanitize it" through the UnixConnectionSocketFactory to a linux appropriate docker url (e.g. localhost:80). This is currently enforced regardless of the original unix endpoint specified (including the environment default). This in turn causes the client to fail to connect for any instance where the valid endpoint is a unix socket that is not localhost:80.

[Add feature/bug description here]
See above.

[Add steps on how to reproduce this issue]
1. Run the docker mac beta. 
2. Attempt to use the library (DefaultDockerClient.fromEnv().build() is fine here, then try running a command). 
3. Watch it fail with fun stack traces.
## What do you expect

The unix socket uri should not be unnecessarily sanitized. Just let it be. Otherwise there's no valid way to connect to the docker endpoint. 
## What happened instead

See above. Connection refused, fun stack traces. 

[Describe the actual results]
## Software:
- docker version: 1.12.0-rc4, build e4a0dbc, experimental
- docker-client version: 5.0.2, (also fails on 5.0.1, 4.0.8)
## Full backtrace

Caused by: com.spotify.docker.client.exceptions.DockerException: java.util.concurrent.ExecutionException: com.spotify.docker.client.shaded.javax.ws.rs.ProcessingException: java.io.IOException: Connection refused
    at com.spotify.docker.client.DefaultDockerClient.propagate(DefaultDockerClient.java:1607)
    at com.spotify.docker.client.DefaultDockerClient.request(DefaultDockerClient.java:1549)
    at com.spotify.docker.client.DefaultDockerClient.createContainer(DefaultDockerClient.java:550)
    at com.spotify.docker.client.DefaultDockerClient.createContainer(DefaultDockerClient.java:532)
    at com.rei.selenous.test.SeleniumContainerManager.startSeleniumContainer(SeleniumContainerManager.java:99)
    ... 25 more
Caused by: java.util.concurrent.ExecutionException: com.spotify.docker.client.shaded.javax.ws.rs.ProcessingException: java.io.IOException: Connection refused
    at jersey.repackaged.com.google.common.util.concurrent.AbstractFuture$Sync.getValue(AbstractFuture.java:299)
    at jersey.repackaged.com.google.common.util.concurrent.AbstractFuture$Sync.get(AbstractFuture.java:286)
    at jersey.repackaged.com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:116)
    at com.spotify.docker.client.DefaultDockerClient.request(DefaultDockerClient.java:1547)
    ... 28 more
Caused by: com.spotify.docker.client.shaded.javax.ws.rs.ProcessingException: java.io.IOException: Connection refused
    at org.glassfish.jersey.apache.connector.ApacheConnector.apply(ApacheConnector.java:481)
    at org.glassfish.jersey.apache.connector.ApacheConnector$1.run(ApacheConnector.java:491)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at jersey.repackaged.com.google.common.util.concurrent.MoreExecutors$DirectExecutorService.execute(MoreExecutors.java:299)
    at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112)
    at jersey.repackaged.com.google.common.util.concurrent.AbstractListeningExecutorService.submit(AbstractListeningExecutorService.java:50)
    at jersey.repackaged.com.google.common.util.concurrent.AbstractListeningExecutorService.submit(AbstractListeningExecutorService.java:37)
    at org.glassfish.jersey.apache.connector.ApacheConnector.apply(ApacheConnector.java:487)
    at org.glassfish.jersey.client.ClientRuntime$2.run(ClientRuntime.java:177)
    at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
    at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
    at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
    at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
    at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
    at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:340)
    at org.glassfish.jersey.client.ClientRuntime$3.run(ClientRuntime.java:209)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: Connection refused
    at jnr.unixsocket.UnixSocketChannel.doConnect(UnixSocketChannel.java:94)
    at jnr.unixsocket.UnixSocketChannel.connect(UnixSocketChannel.java:102)
    at com.spotify.docker.client.ApacheUnixSocket.connect(ApacheUnixSocket.java:73)
    at com.spotify.docker.client.UnixConnectionSocketFactory.connectSocket(UnixConnectionSocketFactory.java:74)
    at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:141)
    at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
    at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
    at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
    at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
    at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
    at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
    at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
    at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:71)
    at org.glassfish.jersey.apache.connector.ApacheConnector.apply(ApacheConnector.java:435)
    ... 21 more

**Comment by johnflavin** [comment]
You said you're using `DefaultDockerClient.fromEnv()` to instantiate your client, but you didn't say anything about your environment. What are you setting your environment variables to?

**Comment by frank-calma** [comment]
They are not set. Setting DOCKER_HOST to unix:///var/run/docker.sock or explicitly setting the uri in the builder has similar results. The issue is in DefaultDockerClient(304), which calls UnixConnectionSocketFactory.sanitizeUri(lines 53 - 59). This in turn changes any unix scheme uri in to "unix://localhost:80". This causes any uri with a unix scheme (such as the DEFAULT_UNIX_ENDPOINT in DockerHost, the standard unix socket for mac beta instances, and any uri defined in the DefaultDockerClient configuration) to be overwritten.

**Comment by mattnworb** [comment]
The original URI (i.e. `unix:///var/run/docker.sock`) is preserved when it is passed to the [`UnixConnectionSocketFactory` constructor](https://github.com/spotify/docker-client/blob/704bfe7535c2b275303f80bcc6bb5a6b94391804/src/main/java/com/spotify/docker/client/DefaultDockerClient.java#L373). 

This class creates a `jnr.unixsocket.UnixSocketAddress` that points to the unix socket. 

So it isn't the case that the Apache HTTP client is actually trying to open a socket to `unix://localhost:80` - but rather than it thinks this is the URI/host it is using, but then with the custom `ConnectionSocketFactory` the socket is actually connected to the original `unix:///var/run/docker.sock` file.

I suspect there is probably something else going on that causes this exception for you. 

Can you paste the results of `ls -l /var/run/docker.sock` run at the same time as you get this exception from docker-client?

Can you also paste the results of this curl command?

```
$> curl -v --unix-socket /var/run/docker.sock http:/_ping
*   Trying /var/run/docker.sock...
* Connected to http (/Users/mattbrown/Library/Containers/com.docke) port 80 (#0)
> GET /_ping HTTP/1.1
> Host: http
> User-Agent: curl/7.43.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Content-Length: 2
< Content-Type: text/plain; charset=utf-8
< Date: Wed, 27 Jul 2016 14:39:34 GMT
< Server: Docker/1.12.0-rc4 (linux)
<
* Connection #0 to host http left intact
OK
```

**Comment by frank-calma** [comment]
fcalma@WORK ~/ $ ls -1 /var/run/docker.sock
/var/run/docker.sock

fcalma@WORK ~/ $ curl -v --unix-socket /var/run/docker.sock http:/_ping
*   Trying /var/run/docker.sock...
* Connected to http (/Users/fcalma/Library/Containers/com.docker.d) port 80 (#0)
> GET /_ping HTTP/1.1
> Host: http
> User-Agent: curl/7.43.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Content-Length: 2
< Content-Type: text/plain; charset=utf-8
< Date: Wed, 27 Jul 2016 15:43:55 GMT
< Server: Docker/1.12.0-rc4 (linux)
<
* Connection #0 to host http left intact
