### ISSUE TITLE
Docker Load API not working

### ISSUE THREAD

**Issue by karthikduraisamy** [spotify/docker-client#484]
## Description

While using the docker client to load the image with the following code  

```
final File imageFile = new File("/Users/xxxxx/postgres.tar");
            final String image = "postgres-test";
            logger.info("Loading Image");
            try {
                InputStream imagePayload = new BufferedInputStream(new FileInputStream(imageFile));
                dockerClient.load(image, imagePayload);
                logger.info("Loaded Image");
            } catch (Exception e) {
                logger.info("Exception in loading Image");
                e.printStackTrace();
            }
```

[Add feature/bug description here]

```
Exception in loading Image
java.lang.IllegalStateException: Could not acquire image ID following load
    at com.google.common.base.Preconditions.checkState(Preconditions.java:173)
    at com.spotify.docker.client.DefaultDockerClient$LoadProgressHandler.getImageId(DefaultDockerClient.java:142)
    at com.spotify.docker.client.DefaultDockerClient$LoadProgressHandler.access$700(DefaultDockerClient.java:129)
    at com.spotify.docker.client.DefaultDockerClient.load(DefaultDockerClient.java:732)
    at com.spotify.docker.client.DefaultDockerClient.load(DefaultDockerClient.java:696)
    at com.ge.postgres.service.PostgresDocker.createPostgresDocker(PostgresDocker.java:77)
```

[Add steps on how to reproduce this issue]
## What do you expect

Image to be loaded and listed in the docker images
## What happened instead

Exception is thrown 
[Describe the actual results]
## Software:
- docker version: [client: 1.12.0 and server : 1.12.0]
- spotify docker-client version: [3.5.12]

**Comment by davidxia** [comment]
We just released 6.0.0. Does this problem still exist for you?
