### ISSUE TITLE
DefaultDockerClient.build() failing on wrong content type=text/plain instead of json with Docker Engine v1.10.3.

### ISSUE THREAD

**Issue by vberruchon** [spotify/docker-client#486]
## Description

The DefaultDockerClient.build() method is failing due to wrong content type=text/plain;charset=utf instead of json returned by Docker Engine v1.10.3.
It's working perfectly with 1.9.1 Docker Engine.

Corresponding Http Requests:
 GET /version HTTP/1.1
Accept: application/json
User-Agent: Jersey/2.19 (Apache HttpClient 4.5)
Host: 10.XXX.XXX.31:2375
Connection: Keep-Alive
Accept-Encoding: gzip,deflate
HTTP/1.1 200 OK
Date: Fri, 02 Sep 2016 17:11:26 GMT
Content-Length: 268
Content-Type: text/plain; charset=utf-8
{"Version":"1.10.3","ApiVersion":"1.22","GitCommit":"d932666-unsupported","GoVersion":"go1.6.2","Os":"linux","Arch":"amd64","KernelVersion":"3.10.0-229.el7.x86_64","BuildTime":"2016-07-29T13:49:00.234124044-04:00","PkgVersion":"docker-common-1.10.3-46.el7.10.x86_64"}

## How to reproduce

Build and image with docker-client using a 1.10.3 docker engine.

## What do you expect

I'd like to be able to build image on 1.10.3 Docker Engine.
For information 1.10.3 is the latest version supported officially on RHEL, so we cannot update to newer version for the moment.

## What happened instead

Crash on this exception : 

com.spotify.docker.client.exceptions.DockerException: java.util.concurrent.ExecutionException: org.glassfish.jersey.message.internal.MessageBodyProviderNotFoundException: MessageBodyReader not found for media type=text/plain;charset=utf-8, type=class com.spotify.docker.client.messages.Version, genericType=class com.spotify.docker.client.messages.Version.
	at com.spotify.docker.client.DefaultDockerClient.propagate(DefaultDockerClient.java:1607)
	at com.spotify.docker.client.DefaultDockerClient.request(DefaultDockerClient.java:1538)
	at com.spotify.docker.client.DefaultDockerClient.version(DefaultDockerClient.java:393)
	at com.spotify.docker.client.DefaultDockerClient.authRegistryHeader(DefaultDockerClient.java:1646)
	at com.spotify.docker.client.DefaultDockerClient.build(DefaultDockerClient.java:1147)
	at com.spotify.docker.client.DefaultDockerClient.build(DefaultDockerClient.java:1106)
	at com.spotify.docker.client.DefaultDockerClient.build(DefaultDockerClient.java:1092)

## Software:

- docker version: docker version

-- Client:
 Version:         1.10.3
 API version:     1.22
 Package version: docker-common-1.10.3-46.el7.10.x86_64
 Go version:      go1.6.2
 Git commit:      d932666-unsupported
 Built:           Fri Jul 29 13:49:00 2016
 OS/Arch:         linux/amd64

-- Server:
 Version:         1.10.3
 API version:     1.22
 Package version: docker-common-1.10.3-46.el7.10.x86_64
 Go version:      go1.6.2
 Git commit:      d932666-unsupported
 Built:           Fri Jul 29 13:49:00 2016
 OS/Arch:         linux/amd64
- docker-client version: 5.0.2 (latest at the moment)

## Full backtrace
com.spotify.docker.client.exceptions.DockerException: java.util.concurrent.ExecutionException: org.glassfish.jersey.message.internal.MessageBodyProviderNotFoundException: MessageBodyReader not found for media type=text/plain;charset=utf-8, type=class com.spotify.docker.client.messages.Version, genericType=class com.spotify.docker.client.messages.Version.
	at com.spotify.docker.client.DefaultDockerClient.propagate(DefaultDockerClient.java:1607)
	at com.spotify.docker.client.DefaultDockerClient.request(DefaultDockerClient.java:1538)
	at com.spotify.docker.client.DefaultDockerClient.version(DefaultDockerClient.java:393)
	at com.spotify.docker.client.DefaultDockerClient.authRegistryHeader(DefaultDockerClient.java:1646)
	at com.spotify.docker.client.DefaultDockerClient.build(DefaultDockerClient.java:1147)
	at com.spotify.docker.client.DefaultDockerClient.build(DefaultDockerClient.java:1106)
	at com.spotify.docker.client.DefaultDockerClient.build(DefaultDockerClient.java:1092)
	at net.client.pic.plugins.docker.java.mojos.AssemblerMojo.buildImageFromDockerfile(AssemblerMojo.java:236)
	at net.client.pic.plugins.docker.java.mojos.AssemblerMojo.execute(AssemblerMojo.java:598)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.MojoExecutor.executeForkedExecutions(MojoExecutor.java:365)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:199)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:319)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
Caused by: java.util.concurrent.ExecutionException: org.glassfish.jersey.message.internal.MessageBodyProviderNotFoundException: MessageBodyReader not found for media type=text/plain;charset=utf-8, type=class com.spotify.docker.client.messages.Version, genericType=class com.spotify.docker.client.messages.Version.
	at jersey.repackaged.com.google.common.util.concurrent.AbstractFuture$Sync.getValue(AbstractFuture.java:299)
	at jersey.repackaged.com.google.common.util.concurrent.AbstractFuture$Sync.get(AbstractFuture.java:286)
	at jersey.repackaged.com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:116)
	at com.spotify.docker.client.DefaultDockerClient.request(DefaultDockerClient.java:1536)
	... 32 more
Caused by: org.glassfish.jersey.message.internal.MessageBodyProviderNotFoundException: MessageBodyReader not found for media type=text/plain;charset=utf-8, type=class com.spotify.docker.client.messages.Version, genericType=class com.spotify.docker.client.messages.Version.
	at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$TerminalReaderInterceptor.aroundReadFrom(ReaderInterceptorExecutor.java:232)
	at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor.proceed(ReaderInterceptorExecutor.java:156)
	at org.glassfish.jersey.message.internal.MessageBodyFactory.readFrom(MessageBodyFactory.java:1085)
	at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:853)
	at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:785)
	at org.glassfish.jersey.client.ClientResponse.readEntity(ClientResponse.java:326)
	at org.glassfish.jersey.client.JerseyInvocation.translate(JerseyInvocation.java:790)
	at org.glassfish.jersey.client.JerseyInvocation.access$500(JerseyInvocation.java:91)
	at org.glassfish.jersey.client.JerseyInvocation$5.completed(JerseyInvocation.java:760)
	at org.glassfish.jersey.client.ClientRuntime.processResponse(ClientRuntime.java:197)
	at org.glassfish.jersey.client.ClientRuntime.access$300(ClientRuntime.java:78)
	at org.glassfish.jersey.client.ClientRuntime$2.run(ClientRuntime.java:179)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:340)
	at org.glassfish.jersey.client.ClientRuntime$3.run(ClientRuntime.java:209)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```text
```

**Comment by vberruchon** [comment]
OK so as seen in other thread this is a Docker bug:

https://github.com/docker/docker/issues/25927
#This is happening from docker 1.10.3 when authz plugins were firstly introduced also
 @yongtang yongtang referenced this issue 13 days ago
 Merged
Fix AuthZ plugins headers change issue https://github.com/docker/docker/pull/25965

But what can we do when using =>1.10.3 Docker engine?
Latest Red Hat Docker available version is 1.10.3!

**Comment by yan-foto** [comment]
@vberruchon I would close this issue, as it is not related to this project.

You could try to build from the source to have the latest version of Docker or use the script at `get.docker.io`.

**Comment by vberruchon** [comment]
Red Hat should release a patched 1.10.3 and the 1.12 quite soon ... so we'll have to wait for our system team to qualify that (I'm actually working for a big company - we cannot do what we want).
For the moment we're stucked with Docker 1.9.1.

**Comment by davidxia** [comment]
@yan-foto is right. This project isn't related to docker engine.

**Comment by Chavjoh** [comment]
Possible workaround:

Create a new provider based on the `JacksonJsonProvider`:
```java
@Provider
@Consumes(MediaType.WILDCARD)
@Produces(MediaType.WILDCARD)
public class WorkaroundJsonProvider extends JacksonJsonProvider {

    @Override
    protected boolean hasMatchingMediaType(MediaType mediaType) {
        // Reflection to change the media type
        setField(mediaType, "type", "application");
        setField(mediaType, "subtype", "json");
        return true;
    }

}
```

Create a new docker client based on the default one:
```java

public class WorkaroundDockerClient extends DefaultDockerClient {

    public WorkaroundDockerClient(String uri) {
        super(uri);
        getClient().register(WorkaroundJsonProvider.class);
    }

}
```

Use the new docker client instead of the builder:
```java
try (DockerClient docker = new WorkaroundDockerClient("http://yourserver:1234")) {
    // TODO
}
```

**Be careful:** The only purpose of this workround is for this case of contacting docker client. Do not use it in other places. I tested it with some of the available API methods. If a part of the API is not sending JSON, this workaround will not work (because every time it will consider every input as JSON).
