### ISSUE TITLE
Unable to create a container with docker-client

### ISSUE THREAD

**Issue by neddogg** [spotify/docker-client#505]
## Description

[I was able to connect to docker using docker-client. But when I want to create a container, I have an exception.]

## How to reproduce

[public class TestDockerClient {
	public static void main(String[] args) throws DockerCertificateException, DockerException, InterruptedException, URISyntaxException, IOException{
	
	final DockerClient docker = DefaultDockerClient.fromEnv().build();
        final ContainerCreation container = docker.createContainer(ContainerConfig.builder().build());
        }
   }]

## What do you expect

[I expected that this code would have create a container on docker.]

## What happened instead

[I have a com.spotify.docker.client.exceptions.DockerRequestException: Request error: POST unix://localhost:80/containers/create: 500 ]

## Software:

- `docker version`: [Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:22:43 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:22:43 2016
 OS/Arch:      linux/amd64]
- Spotify's docker-client version: [<dependency>
			<groupId>com.spotify</groupId>
			<artifactId>docker-client</artifactId>
			<classifier>shaded</classifier>
			<version>5.0.2</version>
		</dependency>]

## Full backtrace

```text
[Exception in thread "main" com.spotify.docker.client.exceptions.DockerRequestException: Request error: POST unix://localhost:80/containers/create: 500
	at com.spotify.docker.client.DefaultDockerClient.propagate(DefaultDockerClient.java:1599)
	at com.spotify.docker.client.DefaultDockerClient.request(DefaultDockerClient.java:1549)
	at com.spotify.docker.client.DefaultDockerClient.createContainer(DefaultDockerClient.java:550)
	at com.spotify.docker.client.DefaultDockerClient.createContainer(DefaultDockerClient.java:532)
	at test.docker1.TestDockerClient.main(TestDockerClient.java:73)
Caused by: javax.ws.rs.InternalServerErrorException: HTTP 500 Internal Server Error
	at org.glassfish.jersey.client.JerseyInvocation.convertToException(JerseyInvocation.java:1002)
	at org.glassfish.jersey.client.JerseyInvocation.translate(JerseyInvocation.java:799)
	at org.glassfish.jersey.client.JerseyInvocation.access$500(JerseyInvocation.java:91)
	at org.glassfish.jersey.client.JerseyInvocation$5.completed(JerseyInvocation.java:760)
	at org.glassfish.jersey.client.ClientRuntime.processResponse(ClientRuntime.java:197)
	at org.glassfish.jersey.client.ClientRuntime.access$300(ClientRuntime.java:78)
	at org.glassfish.jersey.client.ClientRuntime$2.run(ClientRuntime.java:179)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:340)
	at org.glassfish.jersey.client.ClientRuntime$3.run(ClientRuntime.java:209)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]
```

**Comment by davidxia** [comment]
@neddogg What does the corresponding docker logs say? I'm guessing it'll say

```
time="2016-09-26T17:41:20.006911568Z" level=error msg="Handler for POST /containers/create returned error: Config cannot be empty in order to create a container"
```

**Comment by neddogg** [comment]
Yes it does not. How can I fix that please?

**Comment by neddogg** [comment]
Sorry, I had to add some configurations for that to work.
Thanks @davidxia

**Comment by saurabhdevops** [comment]
I am facing similar issue. @neddogg  can you please suggest what configurations did you add?

**Comment by anton-khodak** [comment]
@neddogg having the same issue, it would be very gracious if you elaborated on how you had resolved the problem

**Comment by johnflavin** [comment]
In the original post, @neddogg was creating the container with an empty [container config object](https://github.com/spotify/docker-client/blob/master/src/main/java/com/spotify/docker/client/messages/ContainerConfig.java): `ContainerConfig.builder().build()`. He got back an error because the container config can't be empty. That would be like, on the command line, running `docker create` with no arguments; you won't get a container that way. 

I think that, at the minimum, the container config needs to have an `image`: i.e. `ContainerConfig.builder().image("whatever docker image you want").build()`. But there are also lots of other configuration options you can set on that `Builder` to configure your container. (And also a lot under the `HostConfig`.)
