### ISSUE TITLE
Cannot pull from other registries when client is configured with private registry auth

### ISSUE THREAD

**Issue by triggetry** [spotify/docker-client#593]
## Description

When creating a `DefaultDockerClient` instance with `serverAddress`, `username`, and `password` of a private registry, I am not able to pull images from other registries anymore (including docker.io).
Pushing and Pulling to the private registry works as expected. 
I am not quite sure whether this is an issue of the docker client, docker or its configuration.

## How to reproduce

```
final RegistryAuth auth = RegistryAuth.builder()
            .serverAddress( "https://url.to.private.registry" + "/v2/" )
            .username( "username" )
            .password( "password" )
            .build();

 final DefaultDockerClient dockerClient =
            DefaultDockerClient.builder()
            .uri( "http://" + "192.168.56.11" + ":" + "2375" )
            .registryAuth( auth )
            .build();

dockerClient.pull( "busybox:latest" );
```

## What do you expect
The image `busybox:latest` will be pulled from docker.io on docker host `192.168.56.11`.

**Note:** This is working fine with an older docker version (`1.7`). With the docker version `1.12` it is not working anymore like described below.

## What happened instead
The docker client crashes with a request error `401 Unauthorized` when trying to pull the image from docker.io.
A `DockerRequestException` gets thrown:

`Request error: POST http://192.168.56.11:2375/images/create?fromImage=busybox&tag=latest: 401`

## Software:

- `docker version`: 
```
Client:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Tue Jan 10 20:20:01 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Tue Jan 10 20:20:01 2017
 OS/Arch:      linux/amd64
```

- Spotify's docker-client version:
Tested with version `7.0.2`

## Full backtrace

```
Exception in thread "main" com.spotify.docker.client.exceptions.DockerRequestException: Request error: POST http://192.168.56.11:2375/images/create?fromImage=busybox&tag=latest: 401
	at com.spotify.docker.client.DefaultDockerClient.propagate(DefaultDockerClient.java:2103)
	at com.spotify.docker.client.DefaultDockerClient.request(DefaultDockerClient.java:2042)
	at com.spotify.docker.client.DefaultDockerClient.pull(DefaultDockerClient.java:1151)
	at com.spotify.docker.client.DefaultDockerClient.pull(DefaultDockerClient.java:1128)
	at com.spotify.docker.client.DefaultDockerClient.pull(DefaultDockerClient.java:1122)
	at dockerclienttest.Main.main(Main.java:67)
Caused by: javax.ws.rs.NotAuthorizedException: HTTP 401 Unauthorized
	at org.glassfish.jersey.client.JerseyInvocation.convertToException(JerseyInvocation.java:1002)
	at org.glassfish.jersey.client.JerseyInvocation.translate(JerseyInvocation.java:816)
	at org.glassfish.jersey.client.JerseyInvocation.access$700(JerseyInvocation.java:92)
	at org.glassfish.jersey.client.JerseyInvocation$5.completed(JerseyInvocation.java:773)
	at org.glassfish.jersey.client.ClientRuntime.processResponse(ClientRuntime.java:198)
	at org.glassfish.jersey.client.ClientRuntime.access$300(ClientRuntime.java:79)
	at org.glassfish.jersey.client.ClientRuntime$2.run(ClientRuntime.java:180)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:340)
	at org.glassfish.jersey.client.ClientRuntime$3.run(ClientRuntime.java:210)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by fraisse** [comment]
Hello.
Have you got a status on this issue?

I think I've the same problem…
The private registry which I use is a docker hub proxy. It could then pull the busybox image from the official docker hub without any problem. With the official go client, I have no problem. But with the java client, it does not work: I got a `401 Unauthorized` error as describe by @triggetry (with the same stack trace).
Thanks in advance.

**Comment by triggetry** [comment]
Hi unfortunately I was not (yet) able to find the root cause of this behavior.
My current workaround is to pass the `RegistryAuth` credentials on each and every `pull`. This works because this way I do not need to initialize the `DockerClient` with any credentials, hence I am also able to pull from public registries with no authentication. But I am not very happy with this workaround.
I also noted, that this issue is not reproduceable with the [docker-java](https://github.com/docker-java/docker-java) docker client.

**Comment by johnflavin** [comment]
A few questions:
* What are the contents of your `~/.docker/config.json` file?
* How are you constructing the `RegistryAuth` / `DockerClient` object for the pulls from the public docker hub? Are you giving it no `RegistryAuth` information? (I mean when it fails, of course, but also when you’re doing your workaround.)

**Comment by fraisse** [comment]
Personally, the code is deployed on a kubernetes cluster, so no particular `~/.docker/config.json`.

For the construction of the `RegistryAuth`, we use the builder pattern:
```java
RegistryAuth authConfig = RegistryAuth.builder()
    .email(email()).username(username()).password(password())
    .serverAddress(url())
    .build();
```
and the docker client is simply created with:
```java
DefaultDockerClient.fromEnv().registryAuth(authConfig);
```

Just to remember, `url` is an URL to a docker proxy. 

Hope it will help.

**Comment by mattnworb** [comment]
Up until [version 8.6.0](https://github.com/spotify/docker-client/blob/master/CHANGELOG.md) docker-client was pretty naive about it's authentication support; it tried to use the same RegistryAuth instance for every single operation that needs authentication. 

We've made several improvements related to this in 8.6.x and 8.7.0 that I think should improve the situation. 

Please re-open or create a new issue if you think the new support (RegistryAuthSupplier) doesn't fix your problem.
