### ISSUE TITLE
Cannot deserialize ProcessConfig - Null user

### ISSUE THREAD

**Issue by flozano** [spotify/docker-client#598]
## Description
Process execInspect fails to deserialize docker response properly

## How to reproduce

```java
			ExecCreation result = docker.execCreate(container.id(), command, ExecCreateParam.attachStdout(),
					ExecCreateParam.attachStderr());
			LogStream logStream = docker.execStart(result.id());
			return executionChecker.whenCommandIsFinished(logStream, () -> docker.execInspect(result.id()), result,
					command);
```

## Software:

- `docker version`: Docker version 1.12.5, build 7392c3b (using docker-machine)
- Spotify's docker-client version: 7.0.0

## Full backtrace

```text
com.spotify.docker.client.exceptions.DockerRequestException: Request error: GET https://192.168.99.100:2376/exec/04dcb8022aeaee0c59e8fea3cab5220b7453787d9a42c26a3436057044736d67/json: 200
	at com.spotify.docker.client.DefaultDockerClient.propagate(DefaultDockerClient.java:2103)
	at com.spotify.docker.client.DefaultDockerClient.request(DefaultDockerClient.java:2042)
	at com.spotify.docker.client.DefaultDockerClient.execInspect(DefaultDockerClient.java:1773)
	at com.flozano.common.test.container.docker.DockerContainer.lambda$2(DockerContainer.java:155)
	at com.flozano.common.test.container.docker.DockerExecutionChecker.lambda$0(DockerExecutionChecker.java:30)
	at com.nurkiewicz.asyncretry.SyncRetryJob.run(SyncRetryJob.java:23)
	at com.nurkiewicz.asyncretry.RetryJob.run(RetryJob.java:108)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: javax.ws.rs.client.ResponseProcessingException: com.fasterxml.jackson.databind.JsonMappingException: Can not construct instance of com.spotify.docker.client.messages.ProcessConfig, problem: Null user
 at [Source: org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream@1cc02229; line: 1, column: 201] (through reference chain: com.spotify.docker.client.messages.ExecState["ProcessConfig"])
	at org.glassfish.jersey.client.JerseyInvocation.translate(JerseyInvocation.java:809)
	at org.glassfish.jersey.client.JerseyInvocation.access$700(JerseyInvocation.java:92)
	at org.glassfish.jersey.client.JerseyInvocation$5.completed(JerseyInvocation.java:776)
	at org.glassfish.jersey.client.ClientRuntime.processResponse(ClientRuntime.java:196)
	at org.glassfish.jersey.client.ClientRuntime.access$300(ClientRuntime.java:74)
	at org.glassfish.jersey.client.ClientRuntime$2$1$1.run(ClientRuntime.java:166)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:340)
	at org.glassfish.jersey.client.ClientRuntime$2$1.response(ClientRuntime.java:164)
	at org.glassfish.jersey.apache.connector.ApacheConnector$1.run(ApacheConnector.java:491)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at jersey.repackaged.com.google.common.util.concurrent.MoreExecutors$DirectExecutorService.execute(MoreExecutors.java:299)
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112)
	at jersey.repackaged.com.google.common.util.concurrent.AbstractListeningExecutorService.submit(AbstractListeningExecutorService.java:50)
	at jersey.repackaged.com.google.common.util.concurrent.AbstractListeningExecutorService.submit(AbstractListeningExecutorService.java:37)
	at org.glassfish.jersey.apache.connector.ApacheConnector.apply(ApacheConnector.java:487)
	at org.glassfish.jersey.client.ClientRuntime$2.run(ClientRuntime.java:180)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:340)
	at org.glassfish.jersey.client.ClientRuntime$3.run(ClientRuntime.java:208)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 3 more
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Can not construct instance of com.spotify.docker.client.messages.ProcessConfig, problem: Null user
 at [Source: org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream@1cc02229; line: 1, column: 201] (through reference chain: com.spotify.docker.client.messages.ExecState["ProcessConfig"])
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:277)
	at com.fasterxml.jackson.databind.DeserializationContext.instantiationException(DeserializationContext.java:1441)
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.wrapAsJsonMappingException(StdValueInstantiator.java:476)
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.rewrapCtorProblem(StdValueInstantiator.java:495)
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromObjectWith(StdValueInstantiator.java:276)
	at com.fasterxml.jackson.databind.deser.ValueInstantiator.createFromObjectWith(ValueInstantiator.java:228)
	at com.fasterxml.jackson.databind.deser.impl.PropertyBasedCreator.build(PropertyBasedCreator.java:138)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:471)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1198)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:314)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:148)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:499)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:511)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:396)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1198)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:314)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:148)
	at com.fasterxml.jackson.databind.ObjectReader._bind(ObjectReader.java:1583)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:964)
	at com.fasterxml.jackson.jaxrs.base.ProviderBase.readFrom(ProviderBase.java:815)
	at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$TerminalReaderInterceptor.invokeReadFrom(ReaderInterceptorExecutor.java:256)
	at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$TerminalReaderInterceptor.aroundReadFrom(ReaderInterceptorExecutor.java:235)
	at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor.proceed(ReaderInterceptorExecutor.java:155)
	at org.glassfish.jersey.message.internal.MessageBodyFactory.readFrom(MessageBodyFactory.java:1085)
	at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:874)
	at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:808)
	at org.glassfish.jersey.client.ClientResponse.readEntity(ClientResponse.java:326)
	at org.glassfish.jersey.client.JerseyInvocation.translate(JerseyInvocation.java:806)
	... 33 more
Caused by: java.lang.NullPointerException: Null user
	at com.spotify.docker.client.messages.AutoValue_ProcessConfig.<init>(AutoValue_ProcessConfig.java:28)
	at com.spotify.docker.client.messages.ProcessConfig.create(ProcessConfig.java:64)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.fasterxml.jackson.databind.introspect.AnnotatedMethod.call(AnnotatedMethod.java:117)
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromObjectWith(StdValueInstantiator.java:274)
	... 56 more
```

**Comment by flozano** [comment]
Upgraded to docker 1.13, problem remains.

**Comment by flozano** [comment]
HTTP log:
```
13:02:34.740 [jersey-client-async-executor-0] DEBUG org.apache.http.wire - http-outgoing-9 >> "GET /exec/0b8c068636d5424597946f669e059b2c862275bde67da96eafc66b913b4e3a03/json HTTP/1.1[\r][\n]"
13:02:34.740 [jersey-client-async-executor-0] DEBUG org.apache.http.wire - http-outgoing-9 >> "Accept: application/json[\r][\n]"
13:02:34.740 [jersey-client-async-executor-0] DEBUG org.apache.http.wire - http-outgoing-9 >> "User-Agent: Jersey/2.25.1 (Apache HttpClient 4.5.2)[\r][\n]"
13:02:34.740 [jersey-client-async-executor-0] DEBUG org.apache.http.wire - http-outgoing-9 >> "Host: 192.168.99.100:2376[\r][\n]"
13:02:34.740 [jersey-client-async-executor-0] DEBUG org.apache.http.wire - http-outgoing-9 >> "Connection: Keep-Alive[\r][\n]"
13:02:34.740 [jersey-client-async-executor-0] DEBUG org.apache.http.wire - http-outgoing-9 >> "Accept-Encoding: gzip,deflate[\r][\n]"
13:02:34.740 [jersey-client-async-executor-0] DEBUG org.apache.http.wire - http-outgoing-9 >> "[\r][\n]"
13:02:34.743 [jersey-client-async-executor-0] DEBUG org.apache.http.wire - http-outgoing-9 << "HTTP/1.1 200 OK[\r][\n]"
13:02:34.743 [jersey-client-async-executor-0] DEBUG org.apache.http.wire - http-outgoing-9 << "Api-Version: 1.25[\r][\n]"
13:02:34.743 [jersey-client-async-executor-0] DEBUG org.apache.http.wire - http-outgoing-9 << "Content-Type: application/json[\r][\n]"
13:02:34.743 [jersey-client-async-executor-0] DEBUG org.apache.http.wire - http-outgoing-9 << "Docker-Experimental: false[\r][\n]"
13:02:34.743 [jersey-client-async-executor-0] DEBUG org.apache.http.wire - http-outgoing-9 << "Server: Docker/1.13.0 (linux)[\r][\n]"
13:02:34.743 [jersey-client-async-executor-0] DEBUG org.apache.http.wire - http-outgoing-9 << "Date: Wed, 25 Jan 2017 12:02:34 GMT[\r][\n]"
13:02:34.743 [jersey-client-async-executor-0] DEBUG org.apache.http.wire - http-outgoing-9 << "Content-Length: 380[\r][\n]"
13:02:34.743 [jersey-client-async-executor-0] DEBUG org.apache.http.wire - http-outgoing-9 << "[\r][\n]"
13:02:34.743 [jersey-client-async-executor-0] DEBUG org.apache.http.wire - http-outgoing-9 << "{"ID":"0b8c068636d5424597946f669e059b2c862275bde67da96eafc66b913b4e3a03","Running":true,"ExitCode":null,"ProcessConfig":{"tty":false,"entrypoint":"/bin/touch","arguments":["/asdfg"],"privileged":false},"OpenStdin":false,"OpenStderr":true,"OpenStdout":true,"CanRemove":false,"ContainerID":"14d8f08b06658e50b9d4bf4856d06c1367143faec15c160c5d522efa642f4669","DetachKeys":"","Pid":0}[\n]"
```

**Comment by flozano** [comment]
Sorry for the duplicate issue, I see it was fixed: 
```
https://github.com/spotify/docker-client/commit/b359cd6f2a251f30b94a5845467df422748cdbd8
```
I was thinking 7.0.0 was latest: 

![screen shot 2017-01-25 at 13 20 38](https://cloud.githubusercontent.com/assets/1159291/22290560/c7057e06-e301-11e6-86d1-8a9d56c4fcf7.png)

**Comment by aatxe** [comment]
@flozano How did you get a newer version from maven?

**Comment by flozano** [comment]
Yes, it seems to be an issue with search.maven.org. mvnrepository.com shows the right version as latest (7.0.2)
