### ISSUE TITLE
inspect container can't get containerinfo

### ISSUE THREAD

**Issue by stefiane** [spotify/docker-client#631]
## Description

com.spotify.docker.client.exceptions.DockerRequestException: Request error: GET http://10.110.13.32:3375/containers/0d6e51015f514d09e6ed3d5/json: 200
	at com.spotify.docker.client.DefaultDockerClient.propagate(DefaultDockerClient.java:2103)
	at com.spotify.docker.client.DefaultDockerClient.request(DefaultDockerClient.java:2042)
	at com.spotify.docker.client.DefaultDockerClient.inspectContainer(DefaultDockerClient.java:901)
	at org.MainDocker.main(MainDocker.java:71)
Caused by: javax.ws.rs.client.ResponseProcessingException: com.fasterxml.jackson.databind.JsonMappingException: Instantiation of [simple type, class com.spotify.docker.client.messages.ContainerInfo$Node] value failed: Null id (through reference chain: com.spotify.docker.client.messages.ContainerInfo["Node"])
	....
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Instantiation of [simple type, class com.spotify.docker.client.messages.ContainerInfo$Node] value failed: Null id (through reference chain: 
	... 17 more
**Caused by: java.lang.NullPointerException: Null id**
	at com.spotify.docker.client.messages.AutoValue_ContainerInfo_Node.<init>(AutoValue_ContainerInfo_Node.java:21)
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromObjectWith(StdValueInstantiator.java:227)
	... 39 more

## How to reproduce
1.DockerClient docker = DefaultDockerClient.builder().uri(URI.create("http://10.110.13.32:3375")).build();
2.String id = "0d6e51015f514d09e6ed3d5";
3.ContainerInfo containerInfo = docker.inspectContainer(id);
"http://10.110.13.32:3375" is my swarm manager‘s address
## What do you expect
the container's information，then i can look up the networksetting.

## What happened instead
the error occured,error show me the id isnull

## Software:

Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:39:25 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:39:25 2016
 OS/Arch:      linux/amd64
- `docker version`: [Add the output of `docker version` here, both client and server]
- Spotify's docker-client version: [Add docker-client version here]

## Full backtrace
Question：how should i use method “inspectContainer”? 
Thanks all！
```text
com.spotify.docker.client.exceptions.DockerRequestException: Request error: GET http://10.110.13.32:3375/containers/0d6e51015f514d09e6ed3d5/json: 200
	at com.spotify.docker.client.DefaultDockerClient.propagate(DefaultDockerClient.java:2103)
	at com.spotify.docker.client.DefaultDockerClient.request(DefaultDockerClient.java:2042)
	at com.spotify.docker.client.DefaultDockerClient.inspectContainer(DefaultDockerClient.java:901)
	at org.MainDocker.main(MainDocker.java:71)
Caused by: javax.ws.rs.client.ResponseProcessingException: com.fasterxml.jackson.databind.JsonMappingException: Instantiation of [simple type, class com.spotify.docker.client.messages.ContainerInfo$Node] value failed: Null id (through reference chain: com.spotify.docker.client.messages.ContainerInfo["Node"])
	at org.glassfish.jersey.client.JerseyInvocation.translate(JerseyInvocation.java:806)
	at org.glassfish.jersey.client.JerseyInvocation.access$700(JerseyInvocation.java:92)
	at org.glassfish.jersey.client.JerseyInvocation$5.completed(JerseyInvocation.java:773)
	at org.glassfish.jersey.client.ClientRuntime.processResponse(ClientRuntime.java:198)
	at org.glassfish.jersey.client.ClientRuntime.access$300(ClientRuntime.java:79)
	at org.glassfish.jersey.client.ClientRuntime$2.run(ClientRuntime.java:180)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:340)
	at org.glassfish.jersey.client.ClientRuntime$3.run(ClientRuntime.java:210)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Instantiation of [simple type, class com.spotify.docker.client.messages.ContainerInfo$Node] value failed: Null id (through reference chain: com.spotify.docker.client.messages.ContainerInfo["Node"])
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.wrapException(StdValueInstantiator.java:399)
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromObjectWith(StdValueInstantiator.java:231)
	at com.fasterxml.jackson.databind.deser.impl.PropertyBasedCreator.build(PropertyBasedCreator.java:135)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:440)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1100)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:294)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:131)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:520)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:461)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:377)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1100)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:294)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:131)
	at com.fasterxml.jackson.databind.ObjectReader._bind(ObjectReader.java:1470)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:912)
	at com.fasterxml.jackson.jaxrs.base.ProviderBase.readFrom(ProviderBase.java:811)
	at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$TerminalReaderInterceptor.invokeReadFrom(ReaderInterceptorExecutor.java:256)
	at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$TerminalReaderInterceptor.aroundReadFrom(ReaderInterceptorExecutor.java:235)
	at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor.proceed(ReaderInterceptorExecutor.java:155)
	at org.glassfish.jersey.message.internal.MessageBodyFactory.readFrom(MessageBodyFactory.java:1085)
	at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:874)
	at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:808)
	at org.glassfish.jersey.client.ClientResponse.readEntity(ClientResponse.java:326)
	at org.glassfish.jersey.client.JerseyInvocation.translate(JerseyInvocation.java:803)
	... 17 more
Caused by: java.lang.NullPointerException: Null id
	at com.spotify.docker.client.messages.AutoValue_ContainerInfo_Node.<init>(AutoValue_ContainerInfo_Node.java:21)
	at com.spotify.docker.client.messages.ContainerInfo$Node.create(ContainerInfo.java:209)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.fasterxml.jackson.databind.introspect.AnnotatedMethod.call(AnnotatedMethod.java:120)
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromObjectWith(StdValueInstantiator.java:227)
	... 39 more
```

**Comment by johnflavin** [comment]
So, I can fix this problem pretty quickly. But I am concerned that another problem just like it would happen—some other field would be null where the code doesn't expect it—and you will be right back in the same place. So, to prevent that, it would be helpful to know what docker is sending you when you make this call. Could you possibly run this `curl` command and post the JSON that gets returned?
```
curl http://10.110.13.32:3375/containers/0d6e51015f514d09e6ed3d5/json
```

**Comment by johnflavin** [comment]
I should also say, you aren't doing anything wrong. It's 100% our bug. We recently migrated a ton of our code over to a new style in which we have to explicitly annotate all fields that could possibly be null, and we missed some. Docker will under some conditions send messages that have nulls in fields where our code is not expecting them, and those cause `NullPointerExceptions` to be thrown. And everyone is sad.

**Comment by stefiane** [comment]
@johnflavin ，OK,I run the **curl** command,and results is as follows：
{
  "Id": "0d6e51015f514d09e6ed3d5fadb3ed70b5782f5169fcce53461ba5fb1fc40a3a",
  "Created": "2017-02-15T01:12:03.714202576Z",
  "Path": "catalina.sh",
  "Args": [
    "run"
  ],
  "State": {
    "Status": "running",
    "Running": true,
    "Paused": false,
    "Restarting": false,
    "OOMKilled": false,
    "Dead": false,
    "Pid": 10598,
    "ExitCode": 0,
    "Error": "",
    "StartedAt": "2017-02-15T01:12:04.4899204Z",
    "FinishedAt": "0001-01-01T00:00:00Z"
  },
  "Image": "sha256:57d87b47399bb8e9c5c5e4035c8ecba0c84f662d07a89a9497fd45b52b304ea1",
  "ResolvConfPath": "/var/lib/docker/containers/0d6e51015f514d09e6ed3d5fadb3ed70b5782f5169fcce53461ba5fb1fc40a3a/resolv.conf",
  "HostnamePath": "/var/lib/docker/containers/0d6e51015f514d09e6ed3d5fadb3ed70b5782f5169fcce53461ba5fb1fc40a3a/hostname",
  "HostsPath": "/var/lib/docker/containers/0d6e51015f514d09e6ed3d5fadb3ed70b5782f5169fcce53461ba5fb1fc40a3a/hosts",
  "LogPath": "/var/lib/docker/containers/0d6e51015f514d09e6ed3d5fadb3ed70b5782f5169fcce53461ba5fb1fc40a3a/0d6e51015f514d09e6ed3d5fadb3ed70b5782f5169fcce53461ba5fb1fc40a3a-json.log",
  "Node": {
    "ID": "FU4U:FPGX:PNRQ:KH3G:H6UQ:P6ZZ:JSJR:6NGL:TIUY:DO4T:D63E:T6JY",
    "IP": "10.110.13.31",
    "Addr": "10.110.13.31:2375",
    "Name": "swarm-node2",
    "Cpus": 2,
    "Memory": 4143976448,
    "Labels": {
      "executiondriver": "native-0.2",
      "kernelversion": "4.6.2-1.el7.elrepo.x86_64",
      "operatingsystem": "CentOS Linux 7 (Core)",
      "storagedriver": "devicemapper"
    }
  },
  "Name": "/bsp_test",
  "RestartCount": 0,
  "Driver": "devicemapper",
  "MountLabel": "system_u:object_r:svirt_sandbox_file_t:s0:c127,c600",
  "ProcessLabel": "system_u:system_r:svirt_lxc_net_t:s0:c127,c600",
  "AppArmorProfile": "",
  "ExecIDs": null,
  "HostConfig": {
    "Binds": null,
    "ContainerIDFile": "",
    "LogConfig": {
      "Type": "json-file",
      "Config": {}
    },
    "NetworkMode": "over",
    "PortBindings": {},
    "RestartPolicy": {
      "Name": "always",
      "MaximumRetryCount": 0
    },
    "VolumeDriver": "",
    "VolumesFrom": null,
    "CapAdd": null,
    "CapDrop": null,
    "Dns": [],
    "DnsOptions": [],
    "DnsSearch": [],
    "ExtraHosts": null,
    "GroupAdd": null,
    "IpcMode": "",
    "Links": null,
    "OomScoreAdj": 0,
    "PidMode": "",
    "Privileged": false,
    "PublishAllPorts": true,
    "ReadonlyRootfs": false,
    "SecurityOpt": null,
    "UTSMode": "",
    "ShmSize": 67108864,
    "ConsoleSize": [
      0,
      0
    ],
    "Isolation": "",
    "CpuShares": 0,
    "CgroupParent": "",
    "BlkioWeight": 0,
    "BlkioWeightDevice": null,
    "BlkioDeviceReadBps": null,
    "BlkioDeviceWriteBps": null,
    "BlkioDeviceReadIOps": null,
    "BlkioDeviceWriteIOps": null,
    "CpuPeriod": 0,
    "CpuQuota": 0,
    "CpusetCpus": "",
    "CpusetMems": "",
    "Devices": [],
    "KernelMemory": 0,
    "Memory": 0,
    "MemoryReservation": 0,
    "MemorySwap": 0,
    "MemorySwappiness": -1,
    "OomKillDisable": false,
    "PidsLimit": 0,
    "Ulimits": null
  },
  "GraphDriver": {
    "Name": "devicemapper",
    "Data": {
      "DeviceId": "1824",
      "DeviceName": "docker-253:0-17703341-4575a6a4364d19979baf48e85eec0c3334db447ef653d041ed1bb74c3ad0cb52",
      "DeviceSize": "10737418240"
    }
  },
  "Mounts": [],
  "Config": {
    "Hostname": "0d6e51015f51",
    "Domainname": "",
    "User": "",
    "AttachStdin": false,
    "AttachStdout": false,
    "AttachStderr": false,
    "ExposedPorts": {
      "8080/tcp": {}
    },
    "Tty": true,
    "OpenStdin": true,
    "StdinOnce": false,
    "Env": [
      "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/jdk1.7.0_80/bin:/usr/local/tomcat/lib:/usr/local/tomcat/bin",
      "JAVA_HOME=/usr/local/jdk1.7.0_80",
      "CLASSPATH=/usr/local/jdk1.7.0_80/lib/dt.jar:/usr/local/jdk1.7.0_80/lib/tools.jar",
      "CATALINA_HOME=/usr/local/tomcat",
      "CATALINA_BASE=/usr/local/tomcat",
      "TOMCAT_HOME=/usr/local/tomcat/",
      "java_size=512"
    ],
    "Cmd": [
      "catalina.sh",
      "run"
    ],
    "Image": "10.110.13.187:5001/bsp:2017020717",
    "Volumes": null,
    "WorkingDir": "/usr/local/tomcat/webapps",
    "Entrypoint": null,
    "OnBuild": null,
    "Labels": {
      "com.docker.swarm.id": "eb1fefebb0ad3b990f51dd9080fc8077ff068aa431ed08fd4d50266b8c8d9cdf"
    },
    "StopSignal": "SIGTERM"
  },
  "NetworkSettings": {
    "Bridge": "",
    "SandboxID": "88fe8800bf80583571371182745d6d10f0e85113b05eaa14a9db9169539df386",
    "HairpinMode": false,
    "LinkLocalIPv6Address": "",
    "LinkLocalIPv6PrefixLen": 0,
    "Ports": {
      "8080/tcp": [
        {
          "HostIp": "10.110.13.31",
          "HostPort": "32771"
        }
      ]
    },
    "SandboxKey": "/var/run/docker/netns/88fe8800bf80",
    "SecondaryIPAddresses": null,
    "SecondaryIPv6Addresses": null,
    "EndpointID": "",
    "Gateway": "",
    "GlobalIPv6Address": "",
    "GlobalIPv6PrefixLen": 0,
    "IPAddress": "",
    "IPPrefixLen": 0,
    "IPv6Gateway": "",
    "MacAddress": "",
    "Networks": {
      "over": {
        "IPAMConfig": null,
        "Links": [
          "lsrr_test:lsrr_test"
        ],
        "Aliases": null,
        "NetworkID": "a81d854bbadc82b99610e154819866b19d281b97eea629f2f0ca5f7b26f02059",
        "EndpointID": "01da14c11fb9a45b3c12d1348d5263b485410f37d1bb8601cf11fc0f0a8b3cbe",
        "Gateway": "",
        "IPAddress": "10.0.1.3",
        "IPPrefixLen": 24,
        "IPv6Gateway": "",
        "GlobalIPv6Address": "",
        "GlobalIPv6PrefixLen": 0,
        "MacAddress": "02:42:0a:00:01:03"
      }
    }
  }
}

**Comment by christoe** [comment]
We have been seeing (on Docker 1.10.2 and docker-client-7.0.2) among other:
```
Caused by: com.spotify.docker.client.shaded.com.fasterxml.jackson.databind.JsonMappingException: Unexpected end-of-input in VALUE_STRING
at [Source: org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream@74b3c9dc; line: 1, column: 7887] (through reference chain: com.spotify.docker.client.messages.ContainerInfo["NetworkSettings"]->com.spotify.docker.client.messages.NetworkSettings["IPAddress"])
[...]
Caused by: com.spotify.docker.client.shaded.com.fasterxml.jackson.core.JsonParseException: Unexpected end-of-input within/between OBJECT entries
at [Source: org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream@324eb8c3; line: 1, column: 7887]
[...]
Caused by: com.spotify.docker.client.shaded.com.fasterxml.jackson.databind.JsonMappingException: Unexpected end-of-input in field name
at [Source: org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream@2997dd97; line: 1, column: 7887] (through reference chain: com.spotify.docker.client.messages.ContainerInfo["NetworkSettings"])
```

Related to the above mentioned code migrations?

**Comment by johnflavin** [comment]
That looks like a different problem to me. Could you open another issue for that? More detail on what you were doing when that happens would be helpful.

**Comment by davidxia** [comment]
@stefiane From your JSON, it looks like the field names for `Node` are wrong. It should be `ID` and `IP` instead of `Id`, and `Ip`, right?

```json
  "Node":{
    "ID":"FU4U:FPGX:PNRQ:KH3G:H6UQ:P6ZZ:JSJR:6NGL:TIUY:DO4T:D63E:T6JY",
    "IP":"10.110.13.31",
    "Addr":"10.110.13.31:2375",
    "Name":"swarm-node2",
    "Cpus":2,
    "Memory":4143976448,
    "Labels":{
      "executiondriver":"native-0.2",
      "kernelversion":"4.6.2-1.el7.elrepo.x86_64",
      "operatingsystem":"CentOS Linux 7 (Core)",
      "storagedriver":"devicemapper"
    }
```

Do you have steps to repro how you created that container you're inspecting?

**Comment by stefiane** [comment]
@davidxia  Steps to create my container:

1. HostConfig.Builder hostConfigBuilder = HostConfig.builder()	.memory(memoryByte).memorySwap(memoryByte).memorySwappiness(42).publishAllPorts(true);

2. HostConfig expected = hostConfigBuilder.build();

3. ContainerCreation creation = swarmClient.createContainer(ContainerConfig	.builder().image(image).hostConfig(expected).env(envList).build());

4. String containerId = creation.id();

5. swarmClient.startContainer(containerId);

6. ContainerInfo containerInfo = swarmClient.inspectContainer(containerId);

**Comment by davidxia** [comment]
@stefiane Following your steps to repro, I'm not getting the `Node` part of the output you had above when I curl. I want to write a test for df96238 to check nothing else is broken. Do you have a complete java snippet that I could run to repro your error?

**Comment by scddev** [comment]
I ran into the same problem. It looks like the mapping on Node for Id and Ip is wrong, they are sent as "ID" and "IP" if you have a look at the JSON above. So they are dropped caused by "unknown properties".

Adding OBJECT_MAPPER.configure(MapperFeature.ACCEPT_CASE_INSENSITIVE_PROPERTIES, true); to ObjectMapperProvider.java resolves that but seems to create other problems.
