### ISSUE TITLE
Unexpected end-of-input during json parsing

### ISSUE THREAD

**Issue by christoe** [spotify/docker-client#640]
## Description

We are using docker-client indirectly through helios, and lately we've been seeing a lot of these exceptions in the logs:

```
Caused by: com.spotify.docker.client.shaded.com.fasterxml.jackson.databind.JsonMappingException: Unexpected end-of-input in VALUE_STRING
at [Source: org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream@74b3c9dc; line: 1, column: 7887] (through reference chain: com.spotify.docker.client.messages.ContainerInfo["NetworkSettings"]->com.spotify.docker.client.messages.NetworkSettings["IPAddress"])
[...]
Caused by: com.spotify.docker.client.shaded.com.fasterxml.jackson.core.JsonParseException: Unexpected end-of-input within/between OBJECT entries
at [Source: org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream@324eb8c3; line: 1, column: 7887]
[...]
Caused by: com.spotify.docker.client.shaded.com.fasterxml.jackson.databind.JsonMappingException: Unexpected end-of-input in field name
at [Source: org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream@2997dd97; line: 1, column: 7887] (through reference chain: com.spotify.docker.client.messages.ContainerInfo["NetworkSettings"])
```

I've been using curl to get the json-document directly from the Docker unix socket, but never been able to reproduce the truncated documents that the exceptions suggest. It seems quite random, it's not always the same errors, but all seem to suggest "unexpected end-of-input" in different ways.

## How to reproduce

Unclear. Issue seem to appear after code has been running for a while. Might be related to Helios making quite a lot of inspect container calls during a short period of time.

## What do you expect

No exceptions. No truncated json from the Docker socket.

## What happened instead

Numerous exceptions suggesting "unexpected end-of-input" from the Docker daemon.

## Software:

- `docker version`: 
```
Client:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Tue Jan 10 20:20:01 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Tue Jan 10 20:20:01 2017
 OS/Arch:      linux/amd64
```
- Spotify's docker-client version: 7.0.2
- Spotify's helios: 0.9.86

## Full backtrace
One example of a full stacktrace:
```text
com.spotify.docker.client.exceptions.DockerRequestException: Request error: GET unix://localhost:80/containers/5126dd57eba50f412405577ae723a52a7cf284c6f962d432e81376c4b6bf0568/json: 200
at com.spotify.docker.client.DefaultDockerClient.propagate(DefaultDockerClient.java:2103) ~[helios-services-0.9.86-shaded.jar:0.9.86]
at com.spotify.docker.client.DefaultDockerClient.request(DefaultDockerClient.java:2042) ~[helios-services-0.9.86-shaded.jar:0.9.86]
at com.spotify.docker.client.DefaultDockerClient.inspectContainer(DefaultDockerClient.java:901) ~[helios-services-0.9.86-shaded.jar:0.9.86]
at com.spotify.helios.agent.PollingDockerClient.waitContainer(PollingDockerClient.java:59) ~[helios-services-0.9.86-shaded.jar:0.9.86]
at com.spotify.helios.agent.TaskRunner.run0(TaskRunner.java:214) ~[helios-services-0.9.86-shaded.jar:0.9.86]
at com.spotify.helios.agent.TaskRunner.run(TaskRunner.java:148) ~[helios-services-0.9.86-shaded.jar:0.9.86]
at com.google.common.util.concurrent.AbstractExecutionThreadService$1$2.run(AbstractExecutionThreadService.java:60) [helios-services-0.9.86-shaded.jar:0.9.86]
at com.google.common.util.concurrent.Callables$3.run(Callables.java:100) [helios-services-0.9.86-shaded.jar:0.9.86]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_51]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_51]
at java.lang.Thread.run(Thread.java:745) [na:1.8.0_51]
Caused by: com.spotify.docker.client.shaded.javax.ws.rs.client.ResponseProcessingException: com.spotify.docker.client.shaded.com.fasterxml.jackson.databind.JsonMappingException: Unexpected end-of-input in VALUE_STRING
at [Source: org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream@749d10b6; line: 1, column: 7887] (through reference chain: com.spotify.docker.client.messages.ContainerInfo["Mounts"]->jav
ent.messages.ContainerMount["Destination"])
at org.glassfish.jersey.client.JerseyInvocation.translate(JerseyInvocation.java:806) ~[helios-services-0.9.86-shaded.jar:0.9.86]
at org.glassfish.jersey.client.JerseyInvocation.access$700(JerseyInvocation.java:92) ~[helios-services-0.9.86-shaded.jar:0.9.86]
at org.glassfish.jersey.client.JerseyInvocation$5.completed(JerseyInvocation.java:773) ~[helios-services-0.9.86-shaded.jar:0.9.86]
at org.glassfish.jersey.client.ClientRuntime.processResponse(ClientRuntime.java:198) ~[helios-services-0.9.86-shaded.jar:0.9.86]
at org.glassfish.jersey.client.ClientRuntime.access$300(ClientRuntime.java:79) ~[helios-services-0.9.86-shaded.jar:0.9.86]
at org.glassfish.jersey.client.ClientRuntime$2.run(ClientRuntime.java:180) ~[helios-services-0.9.86-shaded.jar:0.9.86]
at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271) ~[helios-services-0.9.86-shaded.jar:0.9.86]
at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267) ~[helios-services-0.9.86-shaded.jar:0.9.86]
at org.glassfish.jersey.internal.Errors.process(Errors.java:315) ~[helios-services-0.9.86-shaded.jar:0.9.86]
at org.glassfish.jersey.internal.Errors.process(Errors.java:297) ~[helios-services-0.9.86-shaded.jar:0.9.86]
at org.glassfish.jersey.internal.Errors.process(Errors.java:267) ~[helios-services-0.9.86-shaded.jar:0.9.86]
at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:340) ~[helios-services-0.9.86-shaded.jar:0.9.86]
at org.glassfish.jersey.client.ClientRuntime$3.run(ClientRuntime.java:210) ~[helios-services-0.9.86-shaded.jar:0.9.86]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_51]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_51]
... 3 common frames omitted
Caused by: com.spotify.docker.client.shaded.com.fasterxml.jackson.databind.JsonMappingException: Unexpected end-of-input in VALUE_STRING
at [Source: org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream@749d10b6; line: 1, column: 7887] (through reference chain: com.spotify.docker.client.messages.ContainerInfo["Mounts"]->jav
ent.messages.ContainerMount["Destination"])
at com.spotify.docker.client.shaded.com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:210) ~[helios-services-0.9.86-shaded.jar:0.9.86]
at com.spotify.docker.client.shaded.com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:177) ~[helios-services-0.9.86-shaded.jar:0.9.86]
at com.spotify.docker.client.shaded.com.fasterxml.jackson.databind.deser.BeanDeserializerBase.wrapAndThrow(BeanDeserializerBase.java:1475) ~[helios-services-0.9.86-shaded.jar:0.9.86]
at com.spotify.docker.client.shaded.com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:463) ~[helios-services-0.9.86-shaded.jar:0.9.86]
at com.spotify.docker.client.shaded.com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:377) ~[helios-services-0.9.86-shaded.jar:0.9.86]
at com.spotify.docker.client.shaded.com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1100) ~[helios-services-0.9.86-shaded.jar:0.9.86]
at com.spotify.docker.client.shaded.com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:294) ~[helios-services-0.9.86-shaded.jar:0.9.86]
at com.spotify.docker.client.shaded.com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:131) ~[helios-services-0.9.86-shaded.jar:0.9.86]
at com.spotify.docker.client.shaded.com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:245) ~[helios-services-0.9.86-shaded.jar:0.9.86]
at com.spotify.docker.client.shaded.com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:217) ~[helios-services-0.9.86-shaded.jar:0.9.86]
at com.spotify.docker.client.shaded.com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:25) ~[helios-services-0.9.86-shaded.jar:0.9.86]
at com.spotify.docker.client.shaded.com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:520) ~[helios-services-0.9.86-shaded.jar:0.9.86]
at com.spotify.docker.client.shaded.com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:461) ~[helios-services-0.9.86-shaded.jar:0.9.86]
at com.spotify.docker.client.shaded.com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:377) ~[helios-services-0.9.86-shaded.jar:0.9.86]
at com.spotify.docker.client.shaded.com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1100) ~[helios-services-0.9.86-shaded.jar:0.9.86]
at com.spotify.docker.client.shaded.com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:294) ~[helios-services-0.9.86-shaded.jar:0.9.86]
at com.spotify.docker.client.shaded.com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:131) ~[helios-services-0.9.86-shaded.jar:0.9.86]
at com.spotify.docker.client.shaded.com.fasterxml.jackson.databind.ObjectReader._bind(ObjectReader.java:1470) ~[helios-services-0.9.86-shaded.jar:0.9.86]
at com.spotify.docker.client.shaded.com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:912) ~[helios-services-0.9.86-shaded.jar:0.9.86]
at com.spotify.docker.client.shaded.com.fasterxml.jackson.jaxrs.base.ProviderBase.readFrom(ProviderBase.java:811) ~[helios-services-0.9.86-shaded.jar:0.9.86]
at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$TerminalReaderInterceptor.invokeReadFrom(ReaderInterceptorExecutor.java:256) ~[helios-services-0.9.86-shaded.jar:0.9.86]
at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$TerminalReaderInterceptor.aroundReadFrom(ReaderInterceptorExecutor.java:235) ~[helios-services-0.9.86-shaded.jar:0.9.86]
at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor.proceed(ReaderInterceptorExecutor.java:155) ~[helios-services-0.9.86-shaded.jar:0.9.86]
at org.glassfish.jersey.message.internal.MessageBodyFactory.readFrom(MessageBodyFactory.java:1085) ~[helios-services-0.9.86-shaded.jar:0.9.86]
at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:874) ~[helios-services-0.9.86-shaded.jar:0.9.86]
at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:808) ~[helios-services-0.9.86-shaded.jar:0.9.86]
at org.glassfish.jersey.client.ClientResponse.readEntity(ClientResponse.java:326) ~[helios-services-0.9.86-shaded.jar:0.9.86]
at org.glassfish.jersey.client.JerseyInvocation.translate(JerseyInvocation.java:803) ~[helios-services-0.9.86-shaded.jar:0.9.86]
... 17 common frames omitted
Caused by: com.spotify.docker.client.shaded.com.fasterxml.jackson.core.JsonParseException: Unexpected end-of-input in VALUE_STRING
at [Source: org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream@749d10b6; line: 1, column: 7887]
at com.spotify.docker.client.shaded.com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1576) ~[helios-services-0.9.86-shaded.jar:0.9.86]
at com.spotify.docker.client.shaded.com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:533) ~[helios-services-0.9.86-shaded.jar:0.9.86]
at com.spotify.docker.client.shaded.com.fasterxml.jackson.core.base.ParserMinimalBase._reportInvalidEOF(ParserMinimalBase.java:470) ~[helios-services-0.9.86-shaded.jar:0.9.86]
at com.spotify.docker.client.shaded.com.fasterxml.jackson.core.base.ParserMinimalBase._reportInvalidEOF(ParserMinimalBase.java:466) ~[helios-services-0.9.86-shaded.jar:0.9.86]
at com.spotify.docker.client.shaded.com.fasterxml.jackson.core.base.ParserBase.loadMoreGuaranteed(ParserBase.java:459) ~[helios-services-0.9.86-shaded.jar:0.9.86]
at com.spotify.docker.client.shaded.com.fasterxml.jackson.core.json.UTF8StreamJsonParser._finishString2(UTF8StreamJsonParser.java:2431) ~[helios-services-0.9.86-shaded.jar:0.9.86]
at com.spotify.docker.client.shaded.com.fasterxml.jackson.core.json.UTF8StreamJsonParser._finishAndReturnString(UTF8StreamJsonParser.java:2411) ~[helios-services-0.9.86-shaded.jar:0.9.86]
at com.spotify.docker.client.shaded.com.fasterxml.jackson.core.json.UTF8StreamJsonParser.getText(UTF8StreamJsonParser.java:285) ~[helios-services-0.9.86-shaded.jar:0.9.86]
at com.spotify.docker.client.shaded.com.fasterxml.jackson.databind.deser.std.StringDeserializer.deserialize(StringDeserializer.java:32) ~[helios-services-0.9.86-shaded.jar:0.9.86]
at com.spotify.docker.client.shaded.com.fasterxml.jackson.databind.deser.std.StringDeserializer.deserialize(StringDeserializer.java:11) ~[helios-services-0.9.86-shaded.jar:0.9.86]
at com.spotify.docker.client.shaded.com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:520) ~[helios-services-0.9.86-shaded.jar:0.9.86]
at com.spotify.docker.client.shaded.com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:461) ~[helios-services-0.9.86-shaded.jar:0.9.86]
```

**Comment by davidxia** [comment]
@christoe Is this still an issue with recent versions of helios and docker-client?
