### ISSUE TITLE
Unable to parse Global service

### ISSUE THREAD

**Issue by michaelkrog** [spotify/docker-client#659]
## Description

Exception is thrown when parsing global service from Docker in swarm mode.

## How to reproduce

1. Setup docker in swarm mode
2. Create a global service `--mode global`
3. Parse the services from docker using docker-client.

## What do you expect

I expect he services to be listed.

## What happened instead

Exception is thrown

## Software:

- `docker version`: 17.03.0-ce
- Spotify's docker-client version: 8.1.0

## Full backtrace

```text
Caused by: com.spotify.docker.client.exceptions.DockerRequestException: Request error: GET unix://localhost:80/services?filters=%7B%7D: 200
	at com.spotify.docker.client.DefaultDockerClient.propagate(DefaultDockerClient.java:2163) ~[docker-client-8.1.0.jar!/:8.1.0]
	at com.spotify.docker.client.DefaultDockerClient.request(DefaultDockerClient.java:2092) ~[docker-client-8.1.0.jar!/:8.1.0]
	at com.spotify.docker.client.DefaultDockerClient.listServices(DefaultDockerClient.java:1709) ~[docker-client-8.1.0.jar!/:8.1.0]
	at dk.codezoo.meerkat.repository.ServiceRepository.findAllByCriteria(ServiceRepository.java:188) ~[classes!/:na]
	... 93 common frames omitted
Caused by: javax.ws.rs.client.ResponseProcessingException: com.fasterxml.jackson.databind.JsonMappingException: Can not construct instance of com.spotify.docker.client.messages.swarm.GlobalService: abstract types either need to be mapped to concrete types, have custom deserializer, or contain additional type information
 at [Source: org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream@2bd0485b; line: 1, column: 3994] (through reference chain: java.util.ArrayList[2]->com.spotify.docker.client.messages.swarm.Service["Spec"]->com.spotify.docker.client.messages.swarm.ServiceSpec["Mode"]->com.spotify.docker.client.messages.swarm.ServiceMode["Global"])
	at org.glassfish.jersey.client.JerseyInvocation.translate(JerseyInvocation.java:869) ~[jersey-client-2.22.2.jar!/:na]
	at org.glassfish.jersey.client.JerseyInvocation.access$800(JerseyInvocation.java:92) ~[jersey-client-2.22.2.jar!/:na]
	at org.glassfish.jersey.client.JerseyInvocation$6.completed(JerseyInvocation.java:836) ~[jersey-client-2.22.2.jar!/:na]
	at org.glassfish.jersey.client.ClientRuntime.processResponse(ClientRuntime.java:198) ~[jersey-client-2.22.2.jar!/:na]
	at org.glassfish.jersey.client.ClientRuntime.access$300(ClientRuntime.java:79) ~[jersey-client-2.22.2.jar!/:na]
	at org.glassfish.jersey.client.ClientRuntime$2.run(ClientRuntime.java:180) ~[jersey-client-2.22.2.jar!/:na]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271) ~[jersey-common-2.22.2.jar!/:na]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267) ~[jersey-common-2.22.2.jar!/:na]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315) ~[jersey-common-2.22.2.jar!/:na]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297) ~[jersey-common-2.22.2.jar!/:na]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267) ~[jersey-common-2.22.2.jar!/:na]
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:340) ~[jersey-common-2.22.2.jar!/:na]
	at org.glassfish.jersey.client.ClientRuntime$3.run(ClientRuntime.java:210) ~[jersey-client-2.22.2.jar!/:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_111]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_111]
	... 1 common frames omitted
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Can not construct instance of com.spotify.docker.client.messages.swarm.GlobalService: abstract types either need to be mapped to concrete types, have custom deserializer, or contain additional type information
 at [Source: org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream@2bd0485b; line: 1, column: 3994] (through reference chain: java.util.ArrayList[2]->com.spotify.docker.client.messages.swarm.Service["Spec"]->com.spotify.docker.client.messages.swarm.ServiceSpec["Mode"]->com.spotify.docker.client.messages.swarm.ServiceMode["Global"])
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:261) ~[jackson-databind-2.8.3.jar!/:2.8.3]
	at com.fasterxml.jackson.databind.DeserializationContext.instantiationException(DeserializationContext.java:1456) ~[jackson-databind-2.8.3.jar!/:2.8.3]
	at com.fasterxml.jackson.databind.DeserializationContext.handleMissingInstantiator(DeserializationContext.java:1012) ~[jackson-databind-2.8.3.jar!/:2.8.3]
	at com.fasterxml.jackson.databind.deser.AbstractDeserializer.deserialize(AbstractDeserializer.java:149) ~[jackson-databind-2.8.3.jar!/:2.8.3]
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:499) ~[jackson-databind-2.8.3.jar!/:2.8.3]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:511) ~[jackson-databind-2.8.3.jar!/:2.8.3]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:396) ~[jackson-databind-2.8.3.jar!/:2.8.3]
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1196) ~[jackson-databind-2.8.3.jar!/:2.8.3]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:314) ~[jackson-databind-2.8.3.jar!/:2.8.3]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:148) ~[jackson-databind-2.8.3.jar!/:2.8.3]
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:499) ~[jackson-databind-2.8.3.jar!/:2.8.3]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:511) ~[jackson-databind-2.8.3.jar!/:2.8.3]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:396) ~[jackson-databind-2.8.3.jar!/:2.8.3]
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1196) ~[jackson-databind-2.8.3.jar!/:2.8.3]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:314) ~[jackson-databind-2.8.3.jar!/:2.8.3]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:148) ~[jackson-databind-2.8.3.jar!/:2.8.3]
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:499) ~[jackson-databind-2.8.3.jar!/:2.8.3]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:511) ~[jackson-databind-2.8.3.jar!/:2.8.3]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:396) ~[jackson-databind-2.8.3.jar!/:2.8.3]
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1196) ~[jackson-databind-2.8.3.jar!/:2.8.3]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:314) ~[jackson-databind-2.8.3.jar!/:2.8.3]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:148) ~[jackson-databind-2.8.3.jar!/:2.8.3]
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:277) ~[jackson-databind-2.8.3.jar!/:2.8.3]
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:249) ~[jackson-databind-2.8.3.jar!/:2.8.3]
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:26) ~[jackson-databind-2.8.3.jar!/:2.8.3]
	at com.fasterxml.jackson.databind.ObjectReader._bind(ObjectReader.java:1580) ~[jackson-databind-2.8.3.jar!/:2.8.3]
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:961) ~[jackson-databind-2.8.3.jar!/:2.8.3]
	at com.fasterxml.jackson.jaxrs.base.ProviderBase.readFrom(ProviderBase.java:808) ~[jackson-jaxrs-base-2.8.3.jar!/:2.8.3]
	at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$TerminalReaderInterceptor.invokeReadFrom(ReaderInterceptorExecutor.java:256) ~[jersey-common-2.22.2.jar!/:na]
	at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$TerminalReaderInterceptor.aroundReadFrom(ReaderInterceptorExecutor.java:235) ~[jersey-common-2.22.2.jar!/:na]
	at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor.proceed(ReaderInterceptorExecutor.java:155) ~[jersey-common-2.22.2.jar!/:na]
	at org.glassfish.jersey.message.internal.MessageBodyFactory.readFrom(MessageBodyFactory.java:1085) ~[jersey-common-2.22.2.jar!/:na]
	at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:874) ~[jersey-common-2.22.2.jar!/:na]
	at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:834) ~[jersey-common-2.22.2.jar!/:na]
	at org.glassfish.jersey.client.ClientResponse.readEntity(ClientResponse.java:368) ~[jersey-client-2.22.2.jar!/:na]
	at org.glassfish.jersey.client.JerseyInvocation.translate(JerseyInvocation.java:867) ~[jersey-client-2.22.2.jar!/:na]
	... 17 common frames omitted

```

**Comment by davidxia** [comment]
I believe this has been fixed by https://github.com/spotify/docker-client/pull/655. I'll release the latest master branch now as 8.1.1.
