### ISSUE TITLE
Failed to pull images from the private registry

### ISSUE THREAD

**Issue by lephix** [spotify/docker-client#661]
code:
    
    registryAuth = RegistryAuth.builder()
                .email("xxxx@xxx.com")
                .username("xxxx@xxx.com")
                .password("xxxxx-xxxxxx")
                .serverAddress("xxxx.xxx.com")
                .build();
    DockerClient client = DefaultDockerClient.builder()
                .registryAuth(registryAuth)
                .uri("http://" + xxx.xxx.xxx + ":" + 2375).build();
    client.pull("registry.cn-hangzhou.aliyuncs.com/mc-docker/centos-tomcat7:latest")

response:

    com.spotify.docker.client.exceptions.ImageNotFoundException: Image not found: registry.cn-hangzhou.aliyuncs.com/mc-docker/centos-tomcat7:latest: ProgressMessage{id=null, status=null, stream=null, error=Error: image mc-docker/centos-tomcat7:latest not found, progress=null, progressDetail=null}

	at com.spotify.docker.client.LoggingPullHandler.progress(LoggingPullHandler.java:45)
	at com.spotify.docker.client.ProgressStream.tail(ProgressStream.java:74)
	at com.spotify.docker.client.DefaultDockerClient.pull(DefaultDockerClient.java:1183)
	at com.spotify.docker.client.DefaultDockerClient.pull(DefaultDockerClient.java:1156)
	at com.spotify.docker.client.DefaultDockerClient.pull(DefaultDockerClient.java:1150)
	at cn.mucang.container.service.bizservice.ContainerServiceTest.testPullContainer(ContainerServiceTest.java:86)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.intellij.junit4.JUnit4TestRunnerUtil$IgnoreIgnoredTestJUnit4ClassRunner.runChild(JUnit4TestRunnerUtil.java:365)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:117)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:262)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)

I could run docker pull registry.cn-hangzhou.aliyuncs.com/mc-docker/centos-tomcat7:latest on the target host successfully.

    docker login --username=xxxx@xxx.com registry.cn-hangzhou.aliyuncs.com
    docker pull registry.cn-hangzhou.aliyuncs.com/mc-docker/centos-tomcat7:latest

In the ~/.docker/config.json, I have a similar infos:

    {
	"auths": {
		"registry.cn-hangzhou.aliyuncs.com": {
			"auth": "xxxxxxxxxxxxxxxxxx="
		}
	}
    }

Is there anyone have the same problems?

**Comment by grexe** [comment]
I've had the same issue and fixed it by adding the option `dockerAuth(false)` when building the client, see #682.

**Comment by lephix** [comment]
@grexe I tried to build the client with the method `dockerAuth(false)`, get the same error. :(

**Comment by lephix** [comment]
Finally, I found my auth info is not correct. API working good.
Close issue.
