### ISSUE TITLE
testListTaskWithCriteria() is flaky

### ISSUE THREAD

**Issue by davidxia** [spotify/docker-client#704]
## Description

`testListTaskWithCriteria()` is flaky.

## How to reproduce

Run the test a lot (at least on Travis-CI).

## What do you expect

Test to pass.

## What happened instead

Test sometimes fails.

## Software:

- `docker version`:

$ docker version
Client:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Tue Jan 10 20:26:30 2017
 OS/Arch:      linux/amd64
Server:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Tue Jan 10 20:26:30 2017
 OS/Arch:      linux/amd64

- Spotify's docker-client version: master branch

## Full backtrace

https://travis-ci.org/spotify/docker-client/jobs/215755174

```text
testListTaskWithCriteria(com.spotify.docker.client.DefaultDockerClientTest)  Time elapsed: 0.223 sec  <<< FAILURE!
java.lang.AssertionError: 
Expected: <Task{id=2g1hz831y53tb3h77k0b2c5ch, version=Version{index=58}, createdAt=Tue Mar 28 00:44:48 UTC 2017, updatedAt=Tue Mar 28 00:44:48 UTC 2017, name=null, labels=null, spec=TaskSpec{containerSpec=ContainerSpec{image=alpine, hostname=null, labels={}, command=[ping, -c1000, localhost], args=null, env=null, dir=null, user=null, groups=null, tty=null, mounts=null, stopGracePeriod=null, healthcheck=null, hosts=null, secrets=null}, resources=null, restartPolicy=null, placement=null, networks=null, logDriver=null}, serviceId=5ilzsuisthiavlxzq4dg04sby, slot=1, nodeId=5ghcg4awkxnet0u167g68p5q2, status=TaskStatus{timestamp=2017-03-28T00:44:48.131347274Z, state=assigned, message=scheduler assigned task to node, err=null, containerStatus=ContainerStatus{containerId=null, pid=null, exitCode=null}}, desiredState=running, networkAttachments=null}>
     but: was <Task{id=2g1hz831y53tb3h77k0b2c5ch, version=Version{index=59}, createdAt=Tue Mar 28 00:44:48 UTC 2017, updatedAt=Tue Mar 28 00:44:48 UTC 2017, name=null, labels=null, spec=TaskSpec{containerSpec=ContainerSpec{image=alpine, hostname=null, labels={}, command=[ping, -c1000, localhost], args=null, env=null, dir=null, user=null, groups=null, tty=null, mounts=null, stopGracePeriod=null, healthcheck=null, hosts=null, secrets=null}, resources=null, restartPolicy=null, placement=null, networks=null, logDriver=null}, serviceId=5ilzsuisthiavlxzq4dg04sby, slot=1, nodeId=5ghcg4awkxnet0u167g68p5q2, status=TaskStatus{timestamp=2017-03-28T00:44:48.185988133Z, state=accepted, message=accepted, err=null, containerStatus=ContainerStatus{containerId=null, pid=null, exitCode=null}}, desiredState=running, networkAttachments=null}>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.Assert.assertThat(Assert.java:923)
	at com.spotify.docker.client.DefaultDockerClientTest.testListTaskWithCriteria(DefaultDockerClientTest.java:4902)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:239)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
Results :
Failed tests:   testListTaskWithCriteria(com.spotify.docker.client.DefaultDockerClientTest): (..)
```

**Comment by davidxia** [comment]
fixed by #735
