### ISSUE TITLE
DockerClient.listContainers fail.

### ISSUE THREAD

**Issue by lamarios** [spotify/docker-client#708]
## Description

When trying to list down my containers, it fails and throws exception (cf. stack trace)
## How to reproduce

Calling DockerClient.listContainers, i'm using http://localost:4243 to connect (no https, no unix://)

## What was expected

The list of my containers, if i call the api using CURL it works without problem

```
curl http://localhost:4243/containers/json?all=1

  {
    "Id": "cc5945d653533c317d23e89d9a36661ea1403a982cd9632df62b2cd44beb0a02",
    "Names": [
      "/web"
    ],
    "Image": "docker_web",
...
}
]
```

## What happened instead

Exception thrown (see stack trace)

## Software:

- `docker version`: 
```
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Fri Mar 24 00:45:26 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Fri Mar 24 00:45:26 2017
 OS/Arch:      linux/amd64
 Experimental: false


```
- Spotify's docker-client version: 8.3.1

## Full backtrace

```text
 com.spotify.docker.client.exceptions.DockerRequestException: Request error: GET http://localhost:4243/containers/json?all=1: 200
	at com.spotify.docker.client.DefaultDockerClient.propagate(DefaultDockerClient.java:2165) ~[docker-client-8.1.2.jar:8.1.2]
	at com.spotify.docker.client.DefaultDockerClient.request(DefaultDockerClient.java:2094) ~[docker-client-8.1.2.jar:8.1.2]
	at com.spotify.docker.client.DefaultDockerClient.listContainers(DefaultDockerClient.java:477) ~[docker-client-8.1.2.jar:8.1.2]
	at com.ftpix.homedash.plugins.docker.DockerPlugin.getContainersInfo(DockerPlugin.java:214) ~[docker-1.0.4.jar:?]
	at com.ftpix.homedash.plugins.docker.DockerPlugin.refresh(DockerPlugin.java:136) ~[docker-1.0.4.jar:?]
	at com.ftpix.homedash.plugins.Plugin.refreshPlugin(Plugin.java:181) [models-1.0.4.jar:?]
	at com.ftpix.homedash.websocket.MainWebSocket.refreshSingleModule(MainWebSocket.java:133) [classes/:?]
	at com.ftpix.homedash.websocket.FullScreenWebSocket$InnerSocketClass.refreshModule(FullScreenWebSocket.java:152) [classes/:?]
	at com.ftpix.homedash.websocket.FullScreenWebSocket$InnerSocketClass.access$100(FullScreenWebSocket.java:69) [classes/:?]
	at com.ftpix.homedash.websocket.FullScreenWebSocket$InnerSocketClass$1.run(FullScreenWebSocket.java:199) [classes/:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: javax.ws.rs.client.ResponseProcessingException: Unexpected error during response processing.
	at org.glassfish.jersey.client.JerseyInvocation.translate(JerseyInvocation.java:874) ~[jersey-client-2.22.2.jar:?]
	at org.glassfish.jersey.client.JerseyInvocation.access$800(JerseyInvocation.java:92) ~[jersey-client-2.22.2.jar:?]
	at org.glassfish.jersey.client.JerseyInvocation$6.completed(JerseyInvocation.java:836) ~[jersey-client-2.22.2.jar:?]
	at org.glassfish.jersey.client.ClientRuntime.processResponse(ClientRuntime.java:198) ~[jersey-client-2.22.2.jar:?]
	at org.glassfish.jersey.client.ClientRuntime.access$300(ClientRuntime.java:79) ~[jersey-client-2.22.2.jar:?]
	at org.glassfish.jersey.client.ClientRuntime$2.run(ClientRuntime.java:180) ~[jersey-client-2.22.2.jar:?]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271) ~[jersey-common-2.22.2.jar:?]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267) ~[jersey-common-2.22.2.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315) ~[jersey-common-2.22.2.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297) ~[jersey-common-2.22.2.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267) ~[jersey-common-2.22.2.jar:?]
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:340) ~[jersey-common-2.22.2.jar:?]
	at org.glassfish.jersey.client.ClientRuntime$3.run(ClientRuntime.java:210) ~[jersey-client-2.22.2.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_121]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_121]
	... 3 more
Caused by: org.glassfish.hk2.api.MultiException: A MultiException has 3 exceptions.  They are:
1. java.lang.NoClassDefFoundError: Could not initialize class com.spotify.docker.client.ObjectMapperProvider
2. java.lang.IllegalStateException: Unable to perform operation: create on com.spotify.docker.client.ObjectMapperProvider
3. java.lang.IllegalStateException: Unable to perform operation: create on org.glassfish.jersey.internal.ContextResolverFactory

	at org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:391) ~[hk2-locator-2.4.0-b34.jar:?]
	at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:471) ~[hk2-locator-2.4.0-b34.jar:?]
	at org.jvnet.hk2.internal.SingletonContext$1.compute(SingletonContext.java:83) ~[hk2-locator-2.4.0-b34.jar:?]
	at org.jvnet.hk2.internal.SingletonContext$1.compute(SingletonContext.java:71) ~[hk2-locator-2.4.0-b34.jar:?]
	at org.glassfish.hk2.utilities.cache.Cache$OriginThreadAwareFuture$1.call(Cache.java:97) ~[hk2-utils-2.4.0-b34.jar:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_121]
	at org.glassfish.hk2.utilities.cache.Cache$OriginThreadAwareFuture.run(Cache.java:154) ~[hk2-utils-2.4.0-b34.jar:?]
	at org.glassfish.hk2.utilities.cache.Cache.compute(Cache.java:199) ~[hk2-utils-2.4.0-b34.jar:?]
	at org.jvnet.hk2.internal.SingletonContext.findOrCreate(SingletonContext.java:122) ~[hk2-locator-2.4.0-b34.jar:?]
	at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2022) ~[hk2-locator-2.4.0-b34.jar:?]
	at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:114) ~[hk2-locator-2.4.0-b34.jar:?]
	at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:88) ~[hk2-locator-2.4.0-b34.jar:?]
	at org.glassfish.jersey.internal.inject.ProviderToService.apply(ProviderToService.java:58) ~[jersey-common-2.22.2.jar:?]
	at org.glassfish.jersey.internal.inject.ProviderToService.apply(ProviderToService.java:54) ~[jersey-common-2.22.2.jar:?]
	at jersey.repackaged.com.google.common.collect.Iterators$8.transform(Iterators.java:799) ~[jersey-guava-2.22.2.jar:?]
	at jersey.repackaged.com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48) ~[jersey-guava-2.22.2.jar:?]
	at java.util.AbstractCollection.addAll(AbstractCollection.java:343) ~[?:1.8.0_121]
	at java.util.LinkedHashSet.<init>(LinkedHashSet.java:169) ~[?:1.8.0_121]
	at jersey.repackaged.com.google.common.collect.Sets.newLinkedHashSet(Sets.java:325) ~[jersey-guava-2.22.2.jar:?]
	at org.glassfish.jersey.internal.inject.Providers.getClasses(Providers.java:392) ~[jersey-common-2.22.2.jar:?]
	at org.glassfish.jersey.internal.inject.Providers.getAllProviders(Providers.java:379) ~[jersey-common-2.22.2.jar:?]
	at org.glassfish.jersey.internal.inject.Providers.getAllProviders(Providers.java:215) ~[jersey-common-2.22.2.jar:?]
	at org.glassfish.jersey.internal.ContextResolverFactory.<init>(ContextResolverFactory.java:102) ~[jersey-common-2.22.2.jar:?]
	at sun.reflect.GeneratedConstructorAccessor41.newInstance(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingConstructorAccessorImpl.__newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_121]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java) ~[?:1.8.0_121]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java) ~[?:1.8.0_121]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_121]
	at org.glassfish.hk2.utilities.reflection.ReflectionHelper.makeMe(ReflectionHelper.java:1350) ~[hk2-utils-2.4.0-b34.jar:?]
	at org.jvnet.hk2.internal.ClazzCreator.createMe(ClazzCreator.java:271) ~[hk2-locator-2.4.0-b34.jar:?]
	at org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:365) ~[hk2-locator-2.4.0-b34.jar:?]
	at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:471) ~[hk2-locator-2.4.0-b34.jar:?]
	at org.jvnet.hk2.internal.SingletonContext$1.compute(SingletonContext.java:83) ~[hk2-locator-2.4.0-b34.jar:?]
	at org.jvnet.hk2.internal.SingletonContext$1.compute(SingletonContext.java:71) ~[hk2-locator-2.4.0-b34.jar:?]
	at org.glassfish.hk2.utilities.cache.Cache$OriginThreadAwareFuture$1.call(Cache.java:97) ~[hk2-utils-2.4.0-b34.jar:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_121]
	at org.glassfish.hk2.utilities.cache.Cache$OriginThreadAwareFuture.run(Cache.java:154) ~[hk2-utils-2.4.0-b34.jar:?]
	at org.glassfish.hk2.utilities.cache.Cache.compute(Cache.java:199) ~[hk2-utils-2.4.0-b34.jar:?]
	at org.jvnet.hk2.internal.SingletonContext.findOrCreate(SingletonContext.java:122) ~[hk2-locator-2.4.0-b34.jar:?]
	at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2022) ~[hk2-locator-2.4.0-b34.jar:?]
	at org.jvnet.hk2.internal.ServiceLocatorImpl.internalGetService(ServiceLocatorImpl.java:765) ~[hk2-locator-2.4.0-b34.jar:?]
	at org.jvnet.hk2.internal.ServiceLocatorImpl.getUnqualifiedService(ServiceLocatorImpl.java:772) ~[hk2-locator-2.4.0-b34.jar:?]
	at org.jvnet.hk2.internal.IterableProviderImpl.get(IterableProviderImpl.java:111) ~[hk2-locator-2.4.0-b34.jar:?]
	at org.glassfish.jersey.internal.JaxrsProviders.getContextResolver(JaxrsProviders.java:111) ~[jersey-common-2.22.2.jar:?]
	at com.fasterxml.jackson.jaxrs.json.JacksonJsonProvider._locateMapperViaProvider(JacksonJsonProvider.java:198) ~[jackson-jaxrs-json-provider-2.6.0.jar:2.6.0]
	at com.fasterxml.jackson.jaxrs.base.ProviderBase.locateMapper(ProviderBase.java:864) ~[jackson-jaxrs-base-2.6.0.jar:2.6.0]
	at com.fasterxml.jackson.jaxrs.base.ProviderBase.readFrom(ProviderBase.java:758) ~[jackson-jaxrs-base-2.6.0.jar:2.6.0]
	at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$TerminalReaderInterceptor.invokeReadFrom(ReaderInterceptorExecutor.java:256) ~[jersey-common-2.22.2.jar:?]
	at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$TerminalReaderInterceptor.aroundReadFrom(ReaderInterceptorExecutor.java:235) ~[jersey-common-2.22.2.jar:?]
	at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor.proceed(ReaderInterceptorExecutor.java:155) ~[jersey-common-2.22.2.jar:?]
	at org.glassfish.jersey.message.internal.MessageBodyFactory.readFrom(MessageBodyFactory.java:1085) ~[jersey-common-2.22.2.jar:?]
	at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:874) ~[jersey-common-2.22.2.jar:?]
	at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:834) ~[jersey-common-2.22.2.jar:?]
	at org.glassfish.jersey.client.ClientResponse.readEntity(ClientResponse.java:368) ~[jersey-client-2.22.2.jar:?]
	at org.glassfish.jersey.client.JerseyInvocation.translate(JerseyInvocation.java:867) ~[jersey-client-2.22.2.jar:?]
	at org.glassfish.jersey.client.JerseyInvocation.access$800(JerseyInvocation.java:92) ~[jersey-client-2.22.2.jar:?]
	at org.glassfish.jersey.client.JerseyInvocation$6.completed(JerseyInvocation.java:836) ~[jersey-client-2.22.2.jar:?]
	at org.glassfish.jersey.client.ClientRuntime.processResponse(ClientRuntime.java:198) ~[jersey-client-2.22.2.jar:?]
	at org.glassfish.jersey.client.ClientRuntime.access$300(ClientRuntime.java:79) ~[jersey-client-2.22.2.jar:?]
	at org.glassfish.jersey.client.ClientRuntime$2.run(ClientRuntime.java:180) ~[jersey-client-2.22.2.jar:?]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271) ~[jersey-common-2.22.2.jar:?]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267) ~[jersey-common-2.22.2.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315) ~[jersey-common-2.22.2.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297) ~[jersey-common-2.22.2.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267) ~[jersey-common-2.22.2.jar:?]
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:340) ~[jersey-common-2.22.2.jar:?]
	at org.glassfish.jersey.client.ClientRuntime$3.run(ClientRuntime.java:210) ~[jersey-client-2.22.2.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_121]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_121]
	... 3 more
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.spotify.docker.client.ObjectMapperProvider
	at sun.reflect.GeneratedConstructorAccessor42.newInstance(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingConstructorAccessorImpl.__newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_121]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java) ~[?:1.8.0_121]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java) ~[?:1.8.0_121]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_121]
	at org.glassfish.hk2.utilities.reflection.ReflectionHelper.makeMe(ReflectionHelper.java:1350) ~[hk2-utils-2.4.0-b34.jar:?]
	at org.jvnet.hk2.internal.ClazzCreator.createMe(ClazzCreator.java:271) ~[hk2-locator-2.4.0-b34.jar:?]
	at org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:365) ~[hk2-locator-2.4.0-b34.jar:?]
	at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:471) ~[hk2-locator-2.4.0-b34.jar:?]
	at org.jvnet.hk2.internal.SingletonContext$1.compute(SingletonContext.java:83) ~[hk2-locator-2.4.0-b34.jar:?]
	at org.jvnet.hk2.internal.SingletonContext$1.compute(SingletonContext.java:71) ~[hk2-locator-2.4.0-b34.jar:?]
	at org.glassfish.hk2.utilities.cache.Cache$OriginThreadAwareFuture$1.call(Cache.java:97) ~[hk2-utils-2.4.0-b34.jar:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_121]
	at org.glassfish.hk2.utilities.cache.Cache$OriginThreadAwareFuture.run(Cache.java:154) ~[hk2-utils-2.4.0-b34.jar:?]
	at org.glassfish.hk2.utilities.cache.Cache.compute(Cache.java:199) ~[hk2-utils-2.4.0-b34.jar:?]
	at org.jvnet.hk2.internal.SingletonContext.findOrCreate(SingletonContext.java:122) ~[hk2-locator-2.4.0-b34.jar:?]
	at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2022) ~[hk2-locator-2.4.0-b34.jar:?]
	at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:114) ~[hk2-locator-2.4.0-b34.jar:?]
	at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:88) ~[hk2-locator-2.4.0-b34.jar:?]
	at org.glassfish.jersey.internal.inject.ProviderToService.apply(ProviderToService.java:58) ~[jersey-common-2.22.2.jar:?]
	at org.glassfish.jersey.internal.inject.ProviderToService.apply(ProviderToService.java:54) ~[jersey-common-2.22.2.jar:?]
	at jersey.repackaged.com.google.common.collect.Iterators$8.transform(Iterators.java:799) ~[jersey-guava-2.22.2.jar:?]
	at jersey.repackaged.com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48) ~[jersey-guava-2.22.2.jar:?]
	at java.util.AbstractCollection.addAll(AbstractCollection.java:343) ~[?:1.8.0_121]
	at java.util.LinkedHashSet.<init>(LinkedHashSet.java:169) ~[?:1.8.0_121]
	at jersey.repackaged.com.google.common.collect.Sets.newLinkedHashSet(Sets.java:325) ~[jersey-guava-2.22.2.jar:?]
	at org.glassfish.jersey.internal.inject.Providers.getClasses(Providers.java:392) ~[jersey-common-2.22.2.jar:?]
	at org.glassfish.jersey.internal.inject.Providers.getAllProviders(Providers.java:379) ~[jersey-common-2.22.2.jar:?]
	at org.glassfish.jersey.internal.inject.Providers.getAllProviders(Providers.java:215) ~[jersey-common-2.22.2.jar:?]
	at org.glassfish.jersey.internal.ContextResolverFactory.<init>(ContextResolverFactory.java:102) ~[jersey-common-2.22.2.jar:?]
	at sun.reflect.GeneratedConstructorAccessor41.newInstance(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingConstructorAccessorImpl.__newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_121]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java) ~[?:1.8.0_121]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java) ~[?:1.8.0_121]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_121]
	at org.glassfish.hk2.utilities.reflection.ReflectionHelper.makeMe(ReflectionHelper.java:1350) ~[hk2-utils-2.4.0-b34.jar:?]
	at org.jvnet.hk2.internal.ClazzCreator.createMe(ClazzCreator.java:271) ~[hk2-locator-2.4.0-b34.jar:?]
	at org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:365) ~[hk2-locator-2.4.0-b34.jar:?]
	at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:471) ~[hk2-locator-2.4.0-b34.jar:?]
	at org.jvnet.hk2.internal.SingletonContext$1.compute(SingletonContext.java:83) ~[hk2-locator-2.4.0-b34.jar:?]
	at org.jvnet.hk2.internal.SingletonContext$1.compute(SingletonContext.java:71) ~[hk2-locator-2.4.0-b34.jar:?]
	at org.glassfish.hk2.utilities.cache.Cache$OriginThreadAwareFuture$1.call(Cache.java:97) ~[hk2-utils-2.4.0-b34.jar:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_121]
	at org.glassfish.hk2.utilities.cache.Cache$OriginThreadAwareFuture.run(Cache.java:154) ~[hk2-utils-2.4.0-b34.jar:?]
	at org.glassfish.hk2.utilities.cache.Cache.compute(Cache.java:199) ~[hk2-utils-2.4.0-b34.jar:?]
	at org.jvnet.hk2.internal.SingletonContext.findOrCreate(SingletonContext.java:122) ~[hk2-locator-2.4.0-b34.jar:?]
	at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2022) ~[hk2-locator-2.4.0-b34.jar:?]
	at org.jvnet.hk2.internal.ServiceLocatorImpl.internalGetService(ServiceLocatorImpl.java:765) ~[hk2-locator-2.4.0-b34.jar:?]
	at org.jvnet.hk2.internal.ServiceLocatorImpl.getUnqualifiedService(ServiceLocatorImpl.java:772) ~[hk2-locator-2.4.0-b34.jar:?]
	at org.jvnet.hk2.internal.IterableProviderImpl.get(IterableProviderImpl.java:111) ~[hk2-locator-2.4.0-b34.jar:?]
	at org.glassfish.jersey.internal.JaxrsProviders.getContextResolver(JaxrsProviders.java:111) ~[jersey-common-2.22.2.jar:?]
	at com.fasterxml.jackson.jaxrs.json.JacksonJsonProvider._locateMapperViaProvider(JacksonJsonProvider.java:198) ~[jackson-jaxrs-json-provider-2.6.0.jar:2.6.0]
	at com.fasterxml.jackson.jaxrs.base.ProviderBase.locateMapper(ProviderBase.java:864) ~[jackson-jaxrs-base-2.6.0.jar:2.6.0]
	at com.fasterxml.jackson.jaxrs.base.ProviderBase.readFrom(ProviderBase.java:758) ~[jackson-jaxrs-base-2.6.0.jar:2.6.0]
	at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$TerminalReaderInterceptor.invokeReadFrom(ReaderInterceptorExecutor.java:256) ~[jersey-common-2.22.2.jar:?]
	at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$TerminalReaderInterceptor.aroundReadFrom(ReaderInterceptorExecutor.java:235) ~[jersey-common-2.22.2.jar:?]
	at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor.proceed(ReaderInterceptorExecutor.java:155) ~[jersey-common-2.22.2.jar:?]
	at org.glassfish.jersey.message.internal.MessageBodyFactory.readFrom(MessageBodyFactory.java:1085) ~[jersey-common-2.22.2.jar:?]
	at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:874) ~[jersey-common-2.22.2.jar:?]
	at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:834) ~[jersey-common-2.22.2.jar:?]
	at org.glassfish.jersey.client.ClientResponse.readEntity(ClientResponse.java:368) ~[jersey-client-2.22.2.jar:?]
	at org.glassfish.jersey.client.JerseyInvocation.translate(JerseyInvocation.java:867) ~[jersey-client-2.22.2.jar:?]
	at org.glassfish.jersey.client.JerseyInvocation.access$800(JerseyInvocation.java:92) ~[jersey-client-2.22.2.jar:?]
	at org.glassfish.jersey.client.JerseyInvocation$6.completed(JerseyInvocation.java:836) ~[jersey-client-2.22.2.jar:?]
	at org.glassfish.jersey.client.ClientRuntime.processResponse(ClientRuntime.java:198) ~[jersey-client-2.22.2.jar:?]
	at org.glassfish.jersey.client.ClientRuntime.access$300(ClientRuntime.java:79) ~[jersey-client-2.22.2.jar:?]
	at org.glassfish.jersey.client.ClientRuntime$2.run(ClientRuntime.java:180) ~[jersey-client-2.22.2.jar:?]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271) ~[jersey-common-2.22.2.jar:?]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267) ~[jersey-common-2.22.2.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315) ~[jersey-common-2.22.2.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297) ~[jersey-common-2.22.2.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267) ~[jersey-common-2.22.2.jar:?]
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:340) ~[jersey-common-2.22.2.jar:?]
	at org.glassfish.jersey.client.ClientRuntime$3.run(ClientRuntime.java:210) ~[jersey-client-2.22.2.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_121]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_121]
	... 3 more
```

**Comment by johnflavin** [comment]
Are you able to do anything else? Like, you say listing containers fails; can you list images, pull an image, etc? The reason I ask is that this error is in a place in the code that I would expect every API call would hit. I would be surprised if only this one API call were affected.

**Comment by lamarios** [comment]
Hi, all seems to fail. After digging a bit, i thought it might have been some conflicts with the libraries i am using but even if i exclude all problematic only to use docker-client.

The weird thing is that when i use the same methods but simply in a main method, then it works.

**Comment by mattnworb** [comment]
Are you using some sort of alternate JAX-RS client besides glassfish? I noticed org.jvnet.hk2 classes in the stacktrace; I'm drawing a blank at the moment remembering what that is for today.

**Comment by lamarios** [comment]
These are all the libraries that are having conflict related to docker-client
```
jackson-annotations : 2.5.4 
 jackson-core : 2.6.0  
jackson-databind : 2.6.0 
 jackson-jaxrs-base : 2.6.0 
 jackson-jaxrs-json-provider : 2.6.0
  guava : 19.0
 httpclient : 4.5.2 
 httpcore : 4.4.5 
 javassist : 3.19.0-GA 
 slf4j-api : 1.7.22
```
 except Guava and javassist, all are taken from docker-client, but eventhoug i exclude my 2 more recent versions of those 2 it still doesn't work.

**Comment by lamarios** [comment]
Ok, we can close this. I failed excluding the proper dependencies from other dependencies. It now works fine.
