### ISSUE TITLE
What is meant by Request error: POST unix://localhost:80/containers/e66871b0fcc0c22ccdf710a2f0efb213c21d9c360759cb20d8bce50dfc12824e/start: 500

### ISSUE THREAD

**Issue by ajmalrehman** [spotify/docker-client#715]
## Description
While starting the container i am getting the error Request error: POST unix://localhost:80/containers/e66871b0fcc0c22ccdf710a2f0efb213c21d9c360759cb20d8bce50dfc12824e/start: 500

[Add feature/bug description here]

## How to reproduce
public class RunRubyDocker {

	public String buildRubyDocker(String filename){
		String execOutput = null;
		
		try {
			final DockerClient docker = DefaultDockerClient.fromEnv().build();
			docker.pull("ruby:2.1-onbuild");
			final String[] ports = {"33", "9393"};
			final Map<String, List<PortBinding>> portBindings = new HashMap<>();
			for (String port : ports) {
			    List<PortBinding> hostPorts = new ArrayList<>();
			    hostPorts.add(PortBinding.of("0.0.0.0", port));
			    portBindings.put(port, hostPorts);
			}
			List<PortBinding> randomPort = new ArrayList<>();
			randomPort.add(PortBinding.randomPort("0.0.0.0"));
			portBindings.put("443", randomPort);
			final HostConfig hostConfig = HostConfig.builder().binds("/home/itcostcut/mydockerbuild:/usr/src/app/mydockerbuild").
					portBindings(portBindings).build();
			
	
			
			final ContainerConfig containerConfig = ContainerConfig.builder()
				    .hostConfig(hostConfig)
				    .image("ruby:2.1-onbuild").exposedPorts(ports)
				    .cmd("sh", "-c", "while :; do sleep 1; done")
				    .build();
			final ContainerCreation creation = docker.createContainer(containerConfig);
			final String id = creation.id();

			// Start container
			docker.startContainer(id);
			// Exec command inside running container with attached STDOUT and STDERR
			
			final String[] command = {"bash", "-c", "cd mydockerbuild/ && ruby "+filename};
			System.out.println(command);
			final String execCreation = docker.execCreate(
			    id, command, DockerClient.ExecCreateParam.attachStdout(),
			    DockerClient.ExecCreateParam.attachStderr());
			
			final LogStream output = docker.execStart(execCreation);
			execOutput = output.readFully();
			System.out.println(execOutput);
			// Kill container
			docker.killContainer(id);

			// Remove container
			docker.removeContainer(id);

			// Close the docker client
			docker.close();
		} catch (DockerException | InterruptedException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (DockerCertificateException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		return execOutput;
		
	}
	
}

[Add steps on how to reproduce this issue]

## What do you expect
Everytime when i start my container it should go through without any error

## What happened instead
It thow Exception:com.spotify.docker.client.DockerRequestException: 

## Software:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Fri Mar 24 00:45:26 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Fri Mar 24 00:45:26 2017
 OS/Arch:      linux/amd64
 Experimental: false

## Full backtrace
INFO: Starting container with Id: e66871b0fcc0c22ccdf710a2f0efb213c21d9c360759cb20d8bce50dfc12824e
com.spotify.docker.client.DockerRequestException: Request error: POST unix://localhost:80/containers/e66871b0fcc0c22ccdf710a2f0efb213c21d9c360759cb20d8bce50dfc12824e/start: 500
	at com.spotify.docker.client.DefaultDockerClient.propagate(DefaultDockerClient.java:1306)
	at com.spotify.docker.client.DefaultDockerClient.request(DefaultDockerClient.java:1277)
	at com.spotify.docker.client.DefaultDockerClient.containerAction(DefaultDockerClient.java:456)
	at com.spotify.docker.client.DefaultDockerClient.startContainer(DefaultDockerClient.java:448)
	at com.webexecutor.docker.container.RunRubyDocker.buildRubyDocker(RunRubyDocker.java:50)
	at com.webexecutor.code.compiler.service.ExecutorModeService.startDocker(ExecutorModeService.java:64)
	at com.webecutor.java.controller.ExecutorController.doPost(ExecutorController.java:55)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:650)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:218)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:110)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:506)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:962)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:445)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1115)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: javax.ws.rs.InternalServerErrorException: HTTP 500 Internal Server Error
	at org.glassfish.jersey.client.JerseyInvocation.convertToException(JerseyInvocation.java:1002)
	at org.glassfish.jersey.client.JerseyInvocation.translate(JerseyInvocation.java:799)
	at org.glassfish.jersey.client.JerseyInvocation.access$500(JerseyInvocation.java:91)
	at org.glassfish.jersey.client.JerseyInvocation$5.completed(JerseyInvocation.java:760)
	at org.glassfish.jersey.client.ClientRuntime.processResponse(ClientRuntime.java:197)
	at org.glassfish.jersey.client.ClientRuntime.access$300(ClientRuntime.java:78)
	at org.glassfish.jersey.client.ClientRuntime$2.run(ClientRuntime.java:179)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:340)
	at org.glassfish.jersey.client.ClientRuntime$3.run(ClientRuntime.java:209)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	... 1 more
```text
[Paste full backtrace here]
```

**Comment by albers** [comment]
Looks like your environment variable `DOCKER_HOST` is wrong. In `unix://localhost:80/`, the `unix` part indicates that you want to connect via a local socket, the `localhost:80` part looks like an attempt to connect over TCP. This cannot work.

**Comment by mattnworb** [comment]
> Request error: POST unix://localhost:80/containers/e66871b0fcc0c22ccdf710a2f0efb213c21d9c360759cb20d8bce50dfc12824e/start: 500

This is the docker daemon returning an error in response to the startContainer request you have sent. Check the docker daemon logs for more info.

**Comment by davidxia** [comment]
Just curious. How come `DockerRequestException.repsonseBody` was empty here? It's usually included: https://github.com/spotify/docker-client/blob/master/src/main/java/com/spotify/docker/client/exceptions/DockerRequestException.java#L37

**Comment by davidxia** [comment]
I guess 500 errors don't have response bodies?
