### ISSUE TITLE
No message body reader has been found for class java.util.List, ContentType: application/json

### ISSUE THREAD

**Issue by bitsofinfo** [spotify/docker-client#820]
```
2017-07-07T15:29:46.338062631Z
2017-07-07T15:29:46.338078713Z 	at org.bitsofinfo.docker.discovery.swarm.service.SwarmServiceDiscovery.discoverContainers(SwarmServiceDiscovery.java:254)
2017-07-07T15:29:46.338086903Z 	at org.bitsofinfo.docker.discovery.swarm.service.SwarmServiceDiscovery.discoverSelf(SwarmServiceDiscovery.java:114)
2017-07-07T15:29:46.338094094Z 	at org.bitsofinfo.docker.discovery.swarm.service.SwarmServiceDiscovery.<init>(SwarmServiceDiscovery.java:108)
2017-07-07T15:29:46.338107578Z 	... 28 common frames omitted
2017-07-07T15:29:46.338115969Z Caused by: com.spotify.docker.client.exceptions.DockerRequestException: Request error: GET http://192.168.1.104:2376/networks?filters=%7B%22name%22%3A%5B%22az-
-swarm%22%5D%7D: 200, body: [{"Name":"az-ocd-swarm","Id":"iolun7kgs0ak5kkvyt8mxvf8s","Created":"0001-01-01T00:00:00Z","Scope":"swarm","Driver":"overlay","EnableIPv6":false,"IPAM":{"Driver":"default","Options":null,"Config":[]},"Internal":false,"Attachable":false,"Ingress":false,"ConfigFrom":{"Network":""},"ConfigOnly":false,"Containers":null,"Options":{"com.docker.network.driver.overlay.vxlanid_list":"4105"},"Labels":null}]
2017-07-07T15:29:46.338127555Z
2017-07-07T15:29:46.338194676Z 	at com.spotify.docker.client.DefaultDockerClient.propagate(DefaultDockerClient.java:2423)
2017-07-07T15:29:46.338207261Z 	at com.spotify.docker.client.DefaultDockerClient.request(DefaultDockerClient.java:2352)
2017-07-07T15:29:46.338223242Z 	at com.spotify.docker.client.DefaultDockerClient.listNetworks(DefaultDockerClient.java:2098)
2017-07-07T15:29:46.338239623Z 	at org.bitsofinfo.docker.discovery.swarm.service.SwarmServiceDiscovery.discoverContainers(SwarmServiceDiscovery.java:225)
2017-07-07T15:29:46.338263395Z 	... 31 common frames omitted
2017-07-07T15:29:46.338280974Z Caused by: javax.ws.rs.client.ResponseProcessingException: No message body reader has been found for class java.util.List, ContentType: application/json
2017-07-07T15:29:46.338294958Z 	at org.apache.cxf.jaxrs.impl.ResponseImpl.reportMessageHandlerProblem(ResponseImpl.java:433)
2017-07-07T15:29:46.338305245Z 	at org.apache.cxf.jaxrs.impl.ResponseImpl.doReadEntity(ResponseImpl.java:384)
2017-07-07T15:29:46.338313536Z 	at org.apache.cxf.jaxrs.client.AbstractClient.readBody(AbstractClient.java:512)
2017-07-07T15:29:46.338322026Z 	at org.apache.cxf.jaxrs.client.WebClient.handleResponse(WebClient.java:1173)
2017-07-07T15:29:46.338330116Z 	at org.apache.cxf.jaxrs.client.WebClient.handleAsyncResponse(WebClient.java:1023)
2017-07-07T15:29:46.338337208Z 	at org.apache.cxf.jaxrs.client.WebClient.access$100(WebClient.java:83)
2017-07-07T15:29:46.338350292Z 	at org.apache.cxf.jaxrs.client.WebClient$ClientAsyncResponseInterceptor.handleMessage(WebClient.java:1308)
2017-07-07T15:29:46.338365275Z 	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:307)
2017-07-07T15:29:46.338382055Z 	at org.apache.cxf.jaxrs.client.ClientMessageObserver.onMessage(ClientMessageObserver.java:56)
2017-07-07T15:29:46.338434193Z 	at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.handleResponseInternal(HTTPConduit.java:1644)
2017-07-07T15:29:46.338456967Z 	at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream$1.run(HTTPConduit.java:1150)
2017-07-07T15:29:46.338475545Z 	at org.apache.cxf.workqueue.AutomaticWorkQueueImpl$3.run(AutomaticWorkQueueImpl.java:428)
2017-07-07T15:29:46.338493324Z 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
2017-07-07T15:29:46.338510803Z 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
2017-07-07T15:29:46.338523788Z 	at org.apache.cxf.workqueue.AutomaticWorkQueueImpl$AWQThreadFactory$1.run(AutomaticWorkQueueImpl.java:353)
2017-07-07T15:29:46.338533576Z 	... 1 common frames omitted2017-07-07T15:29:46.338062631Z
2017-07-07T15:29:46.338078713Z 	at org.bitsofinfo.docker.discovery.swarm.service.SwarmServiceDiscovery.discoverContainers(SwarmServiceDiscovery.java:254)
2017-07-07T15:29:46.338086903Z 	at org.bitsofinfo.docker.discovery.swarm.service.SwarmServiceDiscovery.discoverSelf(SwarmServiceDiscovery.java:114)
2017-07-07T15:29:46.338094094Z 	at org.bitsofinfo.docker.discovery.swarm.service.SwarmServiceDiscovery.<init>(SwarmServiceDiscovery.java:108)
2017-07-07T15:29:46.338107578Z 	... 28 common frames omitted
2017-07-07T15:29:46.338115969Z Caused by: com.spotify.docker.client.exceptions.DockerRequestException: Request error: GET http://192.168.1.104:2376/networks?filters=%7B%22name%22%3A%5B%22az-ocd-swarm%22%5D%7D: 200, body: [{"Name":"az-ocd-swarm","Id":"iolun7kgs0ak5kkvyt8mxvf8s","Created":"0001-01-01T00:00:00Z","Scope":"swarm","Driver":"overlay","EnableIPv6":false,"IPAM":{"Driver":"default","Options":null,"Config":[]},"Internal":false,"Attachable":false,"Ingress":false,"ConfigFrom":{"Network":""},"ConfigOnly":false,"Containers":null,"Options":{"com.docker.network.driver.overlay.vxlanid_list":"4105"},"Labels":null}]
2017-07-07T15:29:46.338127555Z
2017-07-07T15:29:46.338194676Z 	at com.spotify.docker.client.DefaultDockerClient.propagate(DefaultDockerClient.java:2423)
2017-07-07T15:29:46.338207261Z 	at com.spotify.docker.client.DefaultDockerClient.request(DefaultDockerClient.java:2352)
2017-07-07T15:29:46.338223242Z 	at com.spotify.docker.client.DefaultDockerClient.listNetworks(DefaultDockerClient.java:2098)
2017-07-07T15:29:46.338239623Z 	at org.bitsofinfo.docker.discovery.swarm.service.SwarmServiceDiscovery.discoverContainers(SwarmServiceDiscovery.java:225)
2017-07-07T15:29:46.338263395Z 	... 31 common frames omitted
2017-07-07T15:29:46.338280974Z Caused by: javax.ws.rs.client.ResponseProcessingException: No message body reader has been found for class java.util.List, ContentType: application/json
2017-07-07T15:29:46.338294958Z 	at org.apache.cxf.jaxrs.impl.ResponseImpl.reportMessageHandlerProblem(ResponseImpl.java:433)
2017-07-07T15:29:46.338305245Z 	at org.apache.cxf.jaxrs.impl.ResponseImpl.doReadEntity(ResponseImpl.java:384)
2017-07-07T15:29:46.338313536Z 	at org.apache.cxf.jaxrs.client.AbstractClient.readBody(AbstractClient.java:512)
2017-07-07T15:29:46.338322026Z 	at org.apache.cxf.jaxrs.client.WebClient.handleResponse(WebClient.java:1173)
2017-07-07T15:29:46.338330116Z 	at org.apache.cxf.jaxrs.client.WebClient.handleAsyncResponse(WebClient.java:1023)
2017-07-07T15:29:46.338337208Z 	at org.apache.cxf.jaxrs.client.WebClient.access$100(WebClient.java:83)
2017-07-07T15:29:46.338350292Z 	at org.apache.cxf.jaxrs.client.WebClient$ClientAsyncResponseInterceptor.handleMessage(WebClient.java:1308)
2017-07-07T15:29:46.338365275Z 	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:307)
2017-07-07T15:29:46.338382055Z 	at org.apache.cxf.jaxrs.client.ClientMessageObserver.onMessage(ClientMessageObserver.java:56)
2017-07-07T15:29:46.338434193Z 	at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.handleResponseInternal(HTTPConduit.java:1644)
2017-07-07T15:29:46.338456967Z 	at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream$1.run(HTTPConduit.java:1150)
2017-07-07T15:29:46.338475545Z 	at org.apache.cxf.workqueue.AutomaticWorkQueueImpl$3.run(AutomaticWorkQueueImpl.java:428)
2017-07-07T15:29:46.338493324Z 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
2017-07-07T15:29:46.338510803Z 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
2017-07-07T15:29:46.338523788Z 	at org.apache.cxf.workqueue.AutomaticWorkQueueImpl$AWQThreadFactory$1.run(AutomaticWorkQueueImpl.java:353)
2017-07-07T15:29:46.338533576Z 	... 1 common frames omitted
```

**Comment by johnflavin** [comment]
Could you provide more information? Summarize the issue you are having. What code were you running that caused this? What were you trying to accomplish? What version of the library are you using? In what environment are you running this?

**Comment by bitsofinfo** [comment]
Version 8.7.3

invoking: `com.spotify.docker.client.DefaultDockerClient.listNetworks(DefaultDockerClient.java:2098)`

Java 8

**Comment by johnflavin** [comment]
How did you build the `DockerClient` instance?

**Comment by bitsofinfo** [comment]
`final DockerClient docker = DefaultDockerClient.fromEnv().build();`

**Comment by mattnworb** [comment]
one thing I noticed in the stacktrace is that the JAXRS implementation here is Apache CXF, which I don't think should be a problem but I don't really know too much about CXF either.

**Comment by bitsofinfo** [comment]
Is there any way to force it to use a specific impl? I just dropped some working code using this lib into this app with a lot of other libs and it started blowing up, not sure where to start

**Comment by johnflavin** [comment]
Bear in mind that I don't know anything about Apache CXF, so I don't know if this will be much help. But it looks like you have to register Jackson as a JSON provider. See https://cxf.apache.org/docs/jax-rs-data-bindings.html#JAX-RSDataBindings-Jackson.

**Comment by bitsofinfo** [comment]
Yeah I've already exhausted all those links, cxf is something I didn't bring in, but bundled by a lower level lib that I have no control over.

Is there no way to specify the jaxrs impl specifically for the DockerClient? would be great!

**Comment by johnflavin** [comment]
Not right now, no. There is an old PR that adds this feature (#340) and a newer one that updates the old one (#691). Neither have been merged, but I don't know why.

**Comment by bitsofinfo** [comment]
using the `classifier: 'shaded'` jar works
