### ISSUE TITLE
NullPointerException: Null ipamOptions

### ISSUE THREAD

**Issue by olegtikhonov** [spotify/docker-client#821]
## Description
[During getting list of tasks i get NPE]
## How to reproduce
[docker version 17.06.0-ce, API version:  1.30]

## What do you expect
[Will return a list of tasks]

## What happened instead
[NPE]

## Software:
- `docker 17.06.0-ce`: [Add the output of `docker version` here, both client and server]
- Spotify's docker-client version: [8.8.0]

## Full backtrace

```text
[Caused by: com.fasterxml.jackson.databind.JsonMappingException: Can not construct instance of com.spotify.docker.client.messages.swarm.NetworkSpec, problem: Null ipamOptions
 at [Source: org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream@2297757e; line: 1, column: 2703] (through reference chain: java.util.ArrayList[0]->com.spotify.docker.client.messages.swarm.Task["NetworksAttachments"]->java.util.ArrayList[0]->com.spotify.docker.client.messages.swarm.NetworkAttachment["Network"]->com.spotify.docker.client.messages.swarm.Network["Spec"])
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:277)
	at com.fasterxml.jackson.databind.DeserializationContext.instantiationException(DeserializationContext.java:1441)
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.wrapAsJsonMappingException(StdValueInstantiator.java:476)
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.rewrapCtorProblem(StdValueInstantiator.java:495)
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromObjectWith(StdValueInstantiator.java:276)
	at com.fasterxml.jackson.databind.deser.ValueInstantiator.createFromObjectWith(ValueInstantiator.java:228)
	at com.fasterxml.jackson.databind.deser.impl.PropertyBasedCreator.build(PropertyBasedCreator.java:138)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:471)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1191)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:314)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:148)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:504)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:511)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:400)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1191)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:314)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:148)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:504)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:511)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:400)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1191)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:314)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:148)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:287)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:259)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:26)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:504)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:511)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:400)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1191)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:314)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:148)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:287)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:259)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:26)
	at com.fasterxml.jackson.databind.ObjectReader._bind(ObjectReader.java:1583)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:964)
	at com.fasterxml.jackson.jaxrs.base.ProviderBase.readFrom(ProviderBase.java:815)
	at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$TerminalReaderInterceptor.invokeReadFrom(ReaderInterceptorExecutor.java:256)
	at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$TerminalReaderInterceptor.aroundReadFrom(ReaderInterceptorExecutor.java:235)
	at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor.proceed(ReaderInterceptorExecutor.java:155)
	at org.glassfish.jersey.message.internal.MessageBodyFactory.readFrom(MessageBodyFactory.java:1085)
	at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:874)
	at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:834)
	at org.glassfish.jersey.client.ClientResponse.readEntity(ClientResponse.java:368)
	at org.glassfish.jersey.client.JerseyInvocation.translate(JerseyInvocation.java:871)
	... 33 more
Caused by: java.lang.NullPointerException: Null ipamOptions
	at com.spotify.docker.client.messages.swarm.AutoValue_NetworkSpec.<init>(AutoValue_NetworkSpec.java:41)
	at com.spotify.docker.client.messages.swarm.NetworkSpec.create(NetworkSpec.java:75)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.fasterxml.jackson.databind.introspect.AnnotatedMethod.call(AnnotatedMethod.java:117)
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromObjectWith(StdValueInstantiator.java:274)
	... 74 more]
```

**Comment by olegtikhonov** [comment]
Having debuged I got output:
`2017-07-10 14:24:24 DEBUG wire:73 - http-outgoing-49 << "[{"ID":"jk9vc0rhxl54xhguqnk6g3wjv","Version":{"Index":109},"CreatedAt":"2017-07-09T13:21:26.541067155Z","UpdatedAt":"2017-07-09T13:21:36.858677501Z","Labels":{},"Spec":{"ContainerSpec":{"Image":"globe:5000/openpaas/pulse:1.0.539@sha256:3fc4c182234ca0a28c984621ac325ca30c39990f52a2562c8207abaabc536544","Labels":{"app.service":"cms","com.docker.stack.namespace":"epic"},"Env":["CM_SERVER_DNS=epic_paas-configuration-manager-ms","CM_SERVER_PORT=8084","CM_SERVER_VERSION=v0.1","JAVA_OPTS=-Dvertx.disableDnsResolver=true -Dcom.sun.management.jmxremote.port=10505 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.rmi.port=10505 -Djava.rmi.server.hostname=127.0.0.1 -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote","SPRING_CONFIG_LOCATION=/var/tmp/config/"],"Privileges":{"CredentialSpec":null,"SELinuxContext":null},"Mounts":[{"Type":"bind","Source":"/var/run/docker.sock","Target":"/var/run/docker.sock"},{"Type":"bind","Source":"/home/paas/config/pulse","Target":"/var/tmp/config"}]},"Resources":{},"RestartPolicy":{"Condition":"on-failure","Delay":20000000000,"MaxAttempts":10},"Placement":{"Platforms":[{"Architecture":"amd64","OS":"linux"}]},"Networks":[{"Target":"jy1t20lkkf6o0wkcptguvlw8z","Aliases":["pulse"]}],"LogDriver":{"Name":"gelf","Options":{"gelf-address":"udp://127.0.0.1:12201","labels":"app.service"}},"ForceUpdate":0},"ServiceID":"0l5yu1ks9zxe4iw5nzk3n7s39","NodeID":"1ygqcypbrli5kbnvufzpmgssa","Status":{"Timestamp":"2017-07-09T13:21:36.751094627Z","State":"running","Message":"started","ContainerStatus":{"ContainerID":"317e81de5303825ae6ad064ed02a6e4f37c540dbf811be63888881c2db757955","PID":27122},"PortStatus":{}},"DesiredState":"running","NetworksAttachments":[{"Network":{"ID":"jy1t20lkkf6o0wkcptguvlw8z","Version":{"Index":31},"CreatedAt":"2017-07-09T13:17:21.105514707Z","UpdatedAt":"2017-07-09T13:17:21.106645619Z","Spec":{"Name":"epic_default","Labels":{"com.docker.stack.namespace":"epic"},"DriverConfiguration":{"Name":"overlay"},"Scope":"swarm"},"DriverState":{"Name":"overlay","Options":{"com.docker.network.driver.overlay.vxlanid_list":"4097"}},"IPAMOptions":{"Driver":{"Name":"default"},"Configs":[{"Subnet":"10.0.0.0/24","Gateway":"10.0.0.1"}]}},"Addresses":["10.0.0.13/24"]}]}][\n]"`

**Comment by omnecon** [comment]
We have discovered a similar issue when processing following response from interface "list networks";

 ... **"IPAM":{"Driver":"","Options":null,"Config":null}** ...

This exception is raised:

_Caused by: com.fasterxml.jackson.databind.JsonMappingException: Can not construct instance of com.spotify.docker.client.messages.Ipam, problem: null
at [Source: org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream@1a41af83; line: 1, column: 195] (through reference chain: java.util.ArrayList[0]->com.spotify.docker.client.messages.Network["IPAM"])_

**Solution**:
In class: com.spotify.docker.client.messages.Ipam the field Driver and Config should be Nullable:

```
  @Nullable
  @JsonProperty("Driver")
  public abstract String driver();

  @Nullable
  @JsonProperty("Config")
  public abstract ImmutableList<IpamConfig> config();
```

I hope someone could apply this minor fix? Thx!

**Comment by johnflavin** [comment]
`driver` does not need to be `Nullable`. In your example response, it is an empty string, which is fine. The problem is that `Config` is null, and the `Ipam.create` method isn't checking that. I'll push a fix.

**Comment by ssullivan** [comment]
We have been having this issue also and have been using Jackson mixins to work around it until the PR gets merged.
