### ISSUE TITLE
Problem with event.next()

### ISSUE THREAD

**Issue by olegtikhonov** [spotify/docker-client#822]
## Description
[During the lookup the event I get InvalidFormatException]
## How to reproduce
[event.next()]
## What do you expect
[Will get event.action and event.actor]
## What happened instead
[Caused by: com.fasterxml.jackson.databind.exc.InvalidFormatException: Can not deserialize value of type com.spotify.docker.client.messages.Event$Type from String "service": value not one of declared Enum instance names: [container, volume, image, daemon, network]]
## Software:
- `docker 17.06.0-ce`: [Add the output of `docker version` here, both client and server]
- Spotify's docker-client version: [Add docker-client version here]
## Full backtrace

```text
[Caused by: com.fasterxml.jackson.databind.exc.InvalidFormatException: Can not deserialize value of type com.spotify.docker.client.messages.Event$Type from String "service": value not one of declared Enum instance names: [container, volume, image, daemon, network]
 at [Source: org.apache.http.conn.EofSensorInputStream@2b355cec; line: 1, column: 9] (through reference chain: com.spotify.docker.client.messages.Event["Type"])
	at com.fasterxml.jackson.databind.exc.InvalidFormatException.from(InvalidFormatException.java:74)
	at com.fasterxml.jackson.databind.DeserializationContext.weirdStringException(DeserializationContext.java:1410)
	at com.fasterxml.jackson.databind.DeserializationContext.handleWeirdStringValue(DeserializationContext.java:926)
	at com.fasterxml.jackson.databind.deser.std.EnumDeserializer._deserializeAltString(EnumDeserializer.java:189)
	at com.fasterxml.jackson.databind.deser.std.EnumDeserializer.deserialize(EnumDeserializer.java:126)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:504)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:511)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:400)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1191)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:314)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:148)
	at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:3770)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2099)
	at com.fasterxml.jackson.core.JsonParser.readValueAs(JsonParser.java:1627)
	at com.spotify.docker.client.EventReader.nextMessage(EventReader.java:58)
	at com.spotify.docker.client.EventStream.computeNext(EventStream.java:45)
	... 14 more]
```

**Comment by johnflavin** [comment]
Can you provide more info about how to reproduce this? It seems clear that, A. docker added swarm events with type `service`, and B. your docker daemon was doing something that produced one of those events. Can you tell me what you were doing to produce that event?

These `service` events aren't documented in docker's [`swagger.yaml`](https://github.com/moby/moby/blob/master/api/swagger.yaml#L5657). I believe you when you say you saw one, I just need some help reproducing the event so I can see it myself before I can work on it.

**Comment by olegtikhonov** [comment]
Sure. What i am doing is creating a service, check if a service is up and running, look up a container, exec into this container, tar some files, and exit.
If you need code example, i can post it tomorrow.
Thanks a lot,
Oleg
Be aware it's docker 17.06.0-ce. In 17.05 was working.

---- On Sun, 09 Jul 2017 11:47:45 -0700 notifications@github.com wrote ----

Can you provide more info about how to reproduce this? It seems clear that, A. docker added swarm events with type service, and B. your docker daemon was doing something that produced one of those events. Can you tell me what you were doing to produce that event?

These service events aren't documented in docker's swagger.yaml. I believe you when you say you saw one, I just need some help reproducing the event so I can see it myself before I can work on it.

**Comment by olegtikhonov** [comment]
From the docker events:
2017-07-10T09:05:52.923785680+03:00 service create ezyk8pyl4h2wyd6jzkj7rno9z (name=secretBackupService)
2017-07-10T09:05:52.924606543+03:00 service update ezyk8pyl4h2wyd6jzkj7rno9z (name=secretBackupService)
2017-07-10T09:05:55.470294686+03:00 image pull tutum/curl:latest (name=tutum/curl)
2017-07-10T09:05:55.585513408+03:00 container create 8891f769b7cbd856d3deeffec7dce2061d8aaf869052b92c9bf53c66b61b4227 (com.docker.swarm.node.id=1ygqcypbrli5kbnvufzpmgssa, com.docker.swarm.service.id=ezyk8pyl4h2wyd6jzkj7rno9z, com.docker.swarm.service.name=secretBackupService, com.docker.swarm.task=, com.docker.swarm.task.id=8ax1ccmstxr89rqauqnb6t7rz, com.docker.swarm.task.name=secretBackupService.1.8ax1ccmstxr89rqauqnb6t7rz, image=tutum/curl:latest, name=secretBackupService.1.8ax1ccmstxr89rqauqnb6t7rz)
2017-07-10T09:05:55.734295044+03:00 network connect jy1t20lkkf6o0wkcptguvlw8z (container=8891f769b7cbd856d3deeffec7dce2061d8aaf869052b92c9bf53c66b61b4227, name=epic_default, type=overlay)
2017-07-10T09:05:56.275005065+03:00 container start 8891f769b7cbd856d3deeffec7dce2061d8aaf869052b92c9bf53c66b61b4227 (com.docker.swarm.node.id=1ygqcypbrli5kbnvufzpmgssa, com.docker.swarm.service.id=ezyk8pyl4h2wyd6jzkj7rno9z, com.docker.swarm.service.name=secretBackupService, com.docker.swarm.task=, com.docker.swarm.task.id=8ax1ccmstxr89rqauqnb6t7rz, com.docker.swarm.task.name=secretBackupService.1.8ax1ccmstxr89rqauqnb6t7rz, image=tutum/curl:latest, name=secretBackupService.1.8ax1ccmstxr89rqauqnb6t7rz)


`	private void checkEvents(EventStream es) {
		int countDown = config.getRetryPolicyMaxAttempt();
		while (countDown-- > 0) {
			Event event = es.next();
			if (event.actor().attributes().containsKey(KEY_DOCKER_SWARM_SERVICE_NAME) && event.actor().attributes().get(KEY_DOCKER_SWARM_SERVICE_NAME).contains(SECRET_BACKUP_SERVICE) && event.action().equals(ACTIONS.start.name())) {
				log.info(event.action() + ", " + event.actor());
				break;
			}
		}
	}`

**Comment by johnflavin** [comment]
Ok, I think I see what you're doing here. You are trying to pull out the container start event, correct? You can do a workaround until we get the `service` events to parse correctly: when you get the `EventStream`, don't get the full stream, filter it to just the type of events you want.
```java
EventStream es = dockerClient.events(EventsParam.type(Event.Type.CONTAINER), EventParams.event(ACTIONS.start.name()));
```
That will return a stream with only container start events. If you're interested in a different event instead, tailor to suit your needs. 

That should get you around this bug, I think, because docker won't send you the events that are not being correctly parsed. And as a bonus it will save a tiny amount of bandwidth and CPU cycles.

**Comment by olegtikhonov** [comment]
Thank man !!!

**Comment by olegtikhonov** [comment]
FYI,
they updates its swagger about 8 hours ago. Services are in.
