### ISSUE TITLE
Running docker client using jar throws 'No generator was provided'

### ISSUE THREAD

**Issue by ahab94** [spotify/docker-client#833]
## Description
I am running docker client in my using a jar file it throws the following error.

```
java.lang.RuntimeException: java.lang.ClassNotFoundException: Provider org.glassfish.jersey.internal.RuntimeDelegateImpl could not be instantiated: java.lang.IllegalStateException: No generator was provided and there is no default generator registered
        at javax.ws.rs.ext.RuntimeDelegate.findDelegate(RuntimeDelegate.java:152)
        at javax.ws.rs.ext.RuntimeDelegate.getInstance(RuntimeDelegate.java:120)
        at javax.ws.rs.core.UriBuilder.newInstance(UriBuilder.java:95)
        at javax.ws.rs.core.UriBuilder.fromUri(UriBuilder.java:106)
        at org.glassfish.jersey.client.JerseyWebTarget.<init>(JerseyWebTarget.java:81)
        at org.glassfish.jersey.client.JerseyClient.target(JerseyClient.java:297)
        at org.glassfish.jersey.client.JerseyClient.target(JerseyClient.java:76)
        at com.spotify.docker.client.DefaultDockerClient.ping(DefaultDockerClient.java:494)
Caused by: java.lang.IllegalStateException: No generator was provided and there is no default generator registered
        at org.glassfish.hk2.internal.ServiceLocatorFactoryImpl.internalCreate(ServiceLocatorFactoryImpl.java:308)
        at org.glassfish.hk2.internal.ServiceLocatorFactoryImpl.create(ServiceLocatorFactoryImpl.java:293)
        at org.glassfish.jersey.internal.inject.Injections._createLocator(Injections.java:138)
        at org.glassfish.jersey.internal.inject.Injections.createLocator(Injections.java:109)
        at org.glassfish.jersey.internal.RuntimeDelegateImpl.<init>(RuntimeDelegateImpl.java:63)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at java.lang.Class.newInstance(Class.java:442)
        at javax.ws.rs.ext.FactoryFinder.newInstance(FactoryFinder.java:118)
```
Is there any specific dependency i might be missing?

Docker-Client version : 8.8.1

**Comment by davidxia** [comment]
Can you attach the output of `mvn dependency:tree`?

**Comment by ahab94** [comment]
That issues was resolved, in my case i was using sbt and in the process of assembly the services files were being omitted causing this issue due to bad merge strategy.

**Comment by TedBear42** [comment]
How did you fix the SBT merge strategy?  I'm running into the same problem

**Comment by ahab94** [comment]
@TedBear42 Hi I used the following merge strategy
```
assemblyMergeStrategy in assembly := {
	case PathList("META-INF", xs @ _*) =>
		(xs map {_.toLowerCase}) match {
			case "services" :: xs =>
				MergeStrategy.filterDistinctLines
			case _ => MergeStrategy.discard
		}
	case "reference.conf" => MergeStrategy.concat
	case x => MergeStrategy.first
}
```
The problem was reference.conf files were being discarded.

**Comment by bellemare** [comment]
@ahab94 - Totally just solved my problem too, same issue. Thank you - you helped another lost soul.

**Comment by ahab94** [comment]
Glad it helped :)
