### ISSUE TITLE
Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:2.17:check (validate) on project docker-client: You have 6 Checkstyle violations.

### ISSUE THREAD

**Issue by AbdelNaby** [spotify/docker-client#863]
## Description

I am using Ubuntu 16.04, Netbeans 8.1, and Docker (Version:17.06.0-ce, API version: 1.30). This is what I did to get this exception:
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:2.17:check (checkstyle) on project docker-java: You have 3 Checkstyle violations.
[log.txt](https://github.com/spotify/docker-client/files/1209165/log.txt)

## How to reproduce

    1. Cloned the docker-client in the Netbeans (https://github.com/spotify/docker-client.git)
    2. Created a package under Source Packages and created a main Java class print a "Hello" as a test
    3. In the terminal I had executed "mvn clean install -X"

## What do you expect

I need to create and run docker images using Java code.

## What happened instead
The attached exception is displayed and I can't fix it. Please help me I am new to docker and github and I don't know how to use docker-java.

## Software:

- `docker version`: 
- Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:23:31 2017
 OS/Arch:      linux/amd64

- Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:19:04 2017
 OS/Arch:      linux/amd64
 Experimental: false

- Spotify's docker-client version: 8.8.5-SNAPSHOT

## Full backtrace
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:2.17:check (validate) on project docker-client: You have 6 Checkstyle violations. -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:2.17:check (validate) on project docker-client: You have 6 Checkstyle violations.
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoFailureException: You have 6 Checkstyle violations.
	at org.apache.maven.plugin.checkstyle.CheckstyleViolationCheckMojo.execute(CheckstyleViolationCheckMojo.java:588)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 20 more
[log.txt](https://github.com/spotify/docker-client/files/1209179/log.txt)

**Comment by mattnworb** [comment]
the Maven output from the checkstyle plugin lists exactly what the warnings/problems are:

```
[WARNING] src/main/java/newpackage/NewMain.java:[16] (whitespace) EmptyLineSeparator: 'package' should be separated from previous statement.
[WARNING] src/main/java/newpackage/NewMain.java:[18] (javadoc) SummaryJavadoc: First sentence of Javadoc is incomplete (period is missing) or not present.
[WARNING] src/main/java/newpackage/NewMain.java:[24] (javadoc) SummaryJavadoc: First sentence of Javadoc is incomplete (period is missing) or not present.
[WARNING] src/main/java/newpackage/NewMain.java:[27] (indentation) Indentation: 'method def modifier' have incorrect indentation level 4, expected level should be 2.
[WARNING] src/main/java/newpackage/NewMain.java:[29] (indentation) Indentation: 'method def' child have incorrect indentation level 8, expected level should be 4.
[WARNING] src/main/java/newpackage/NewMain.java:[30] (indentation) Indentation: 'method def rcurly' have incorrect indentation level 4, expected level should be 2.
```

For simple experimentation purposes where you don't care if the new code you add matches the project's style rules, you can just [skip checkstyle by adding `-Dcheckstyle.skip` to your `mvn` command`](https://maven.apache.org/plugins/maven-checkstyle-plugin/checkstyle-mojo.html#skip).

**Comment by Manikandanbrema** [comment]
Execution default of goal org.apache.maven.plugins:maven-checkstyle-plugin:2.17:check failed: 2147483647
