### ISSUE TITLE
ava.lang.NoClassDefFoundError: com/spotify/docker/client/DefaultDockerClient

### ISSUE THREAD

**Issue by AbdelNaby** [spotify/docker-client#879]
## Description
This single line of code:
DockerClient docker = new DefaultDockerClient("unix:///var/run/docker.sock");

Throws this exception:
Exception in thread "main" java.lang.NoClassDefFoundError: com/spotify/docker/client/DefaultDockerClient
    at org.koshkosh.javabrains.App.main(App.java:17)
Caused by: java.lang.ClassNotFoundException: com.spotify.docker.client.DefaultDockerClient
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 1 more

## How to reproduce

A simple java desktop application with a main that contains only this single line of code:
DockerClient docker = new DefaultDockerClient("unix:///var/run/docker.sock");

## What do you expect

Build success

## What happened instead

The code compiles fine, but at run-time, it comes up with this error:

Exception in thread "main" java.lang.NoClassDefFoundError: com/spotify/docker/client/DefaultDockerClient
    at org.koshkosh.javabrains.App.main(App.java:17)
Caused by: java.lang.ClassNotFoundException: com.spotify.docker.client.DefaultDockerClient
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 1 more

## Software:

- `docker version`: 
Client:
 Version:      17.04.0-ce
 API version:  1.28
 Go version:   go1.7.5
 Git commit:   4845c56
 Built:        Wed Apr  5 19:28:09 2017
 OS/Arch:      linux/amd64
Server:
 Version:      17.04.0-ce
 API version:  1.28 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   4845c56
 Built:        Wed Apr  5 19:28:09 2017
 OS/Arch:      linux/amd64
 Experimental: false

- Spotify's docker-client version: 8.9.0

## Full backtrace

Exception in thread "main" java.lang.NoClassDefFoundError: com/spotify/docker/client/DefaultDockerClient
	at org.koshkosh.javabrains.App.main(App.java:17)
Caused by: java.lang.ClassNotFoundException: com.spotify.docker.client.DefaultDockerClient
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 1 more

**Comment by safrazhanas** [comment]
Hi AbdelNaby,

How did you compile the program? is it with an IDE? 
How did you run the program? is it with commandline?

If you build the project using the IDE, you should be able to run through it.

**Comment by davidxia** [comment]
Closing due to inactivity. Also pretty sure this is environmental.
