### ISSUE TITLE
Client throws RedirectionException if trying to start already started container

### ISSUE THREAD

**Issue by longtimeago** [spotify/docker-client#889]
## Description

Client throws RedirectionException if trying to start already started container

## How to reproduce

Start container twice

## What do you expect

I would expect `DockerClient.start()` to be idempotent operation (just as Docker daemon) - do nothing if container is already started (ignore 304 response)

## What happened instead

`javax.ws.rs.RedirectionException: HTTP 304 Not Modified` is thrown

## Software:

```
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:10:54 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:10:54 2017
 OS/Arch:      linux/amd64
 Experimental: true
```
- Spotify's docker-client version: [8.9.0]

## Full backtrace

```text
00:24:10 Sep 12 11:22:09 Caused by: com.spotify.docker.client.exceptions.DockerRequestException: Request error: POST unix://localhost:80/containers/03911ce36347033f07d72a856912307bee1ffadf098463427aa4e92d1f638a38/start: 304, body:
00:24:10 Sep 12 11:22:09        at com.spotify.docker.client.DefaultDockerClient.propagate(DefaultDockerClient.java:2649)
00:24:10 Sep 12 11:22:09        at com.spotify.docker.client.DefaultDockerClient.request(DefaultDockerClient.java:2610)
00:24:10 Sep 12 11:22:09        at com.spotify.docker.client.DefaultDockerClient.containerAction(DefaultDockerClient.java:688)
00:24:10 Sep 12 11:22:09        at com.spotify.docker.client.DefaultDockerClient.containerAction(DefaultDockerClient.java:673)
00:24:10 Sep 12 11:22:09        at com.spotify.docker.client.DefaultDockerClient.startContainer(DefaultDockerClient.java:668)
00:24:10 Sep 12 11:22:09        ... 50 more
00:24:10 Sep 12 11:22:09 Caused by: javax.ws.rs.RedirectionException: HTTP 304 Not Modified
00:24:10 Sep 12 11:22:09        at org.glassfish.jersey.client.JerseyInvocation.createExceptionForFamily(JerseyInvocation.java:1053)
00:24:10 Sep 12 11:22:09        at org.glassfish.jersey.client.JerseyInvocation.convertToException(JerseyInvocation.java:1039)
00:24:10 Sep 12 11:22:09        at org.glassfish.jersey.client.JerseyInvocation.translate(JerseyInvocation.java:819)
00:24:10 Sep 12 11:22:09        at org.glassfish.jersey.client.JerseyInvocation.access$700(JerseyInvocation.java:92)
00:24:10 Sep 12 11:22:09        at org.glassfish.jersey.client.JerseyInvocation$5.completed(JerseyInvocation.java:776)
00:24:10 Sep 12 11:22:09        at org.glassfish.jersey.client.ClientRuntime.processResponse(ClientRuntime.java:196)
00:24:10 Sep 12 11:22:09        at org.glassfish.jersey.client.ClientRuntime.access$300(ClientRuntime.java:74)
00:24:10 Sep 12 11:22:09        at org.glassfish.jersey.client.ClientRuntime$2$1$1.run(ClientRuntime.java:166)
00:24:10 Sep 12 11:22:09        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
00:24:10 Sep 12 11:22:09        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
00:24:10 Sep 12 11:22:09        at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
00:24:10 Sep 12 11:22:09        at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
00:24:10 Sep 12 11:22:09        at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
00:24:10 Sep 12 11:22:09        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:340)
00:24:10 Sep 12 11:22:09        at org.glassfish.jersey.client.ClientRuntime$2$1.response(ClientRuntime.java:164)
00:24:10 Sep 12 11:22:09        at org.glassfish.jersey.apache.connector.ApacheConnector$1.run(ApacheConnector.java:491)
00:24:10 Sep 12 11:22:09        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
00:24:10 Sep 12 11:22:09        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
00:24:10 Sep 12 11:22:09        at jersey.repackaged.com.google.common.util.concurrent.MoreExecutors$DirectExecutorService.execute(MoreExecutors.java:299)
00:24:10 Sep 12 11:22:09        at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112)
00:24:10 Sep 12 11:22:09        at jersey.repackaged.com.google.common.util.concurrent.AbstractListeningExecutorService.submit(AbstractListeningExecutorService.java:50)
00:24:10 Sep 12 11:22:09        at jersey.repackaged.com.google.common.util.concurrent.AbstractListeningExecutorService.submit(AbstractListeningExecutorService.java:37)
00:24:10 Sep 12 11:22:09        at org.glassfish.jersey.apache.connector.ApacheConnector.apply(ApacheConnector.java:487)
00:24:10 Sep 12 11:22:09        at org.glassfish.jersey.client.ClientRuntime$2.run(ClientRuntime.java:180)
00:24:10 Sep 12 11:22:09        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
00:24:10 Sep 12 11:22:09        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
00:24:10 Sep 12 11:22:09        at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
00:24:10 Sep 12 11:22:09        at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
00:24:10 Sep 12 11:22:09        at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
00:24:10 Sep 12 11:22:09        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:340)
00:24:10 Sep 12 11:22:09        at org.glassfish.jersey.client.ClientRuntime$3.run(ClientRuntime.java:208)
00:24:10 Sep 12 11:22:09        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
00:24:10 Sep 12 11:22:09        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
00:24:10 Sep 12 11:22:09        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
00:24:10 Sep 12 11:22:09        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
00:24:10 Sep 12 11:22:09        at java.lang.Thread.run(Thread.java:748)
```

**Comment by johnflavin** [comment]
Good find. I had never thought about that operation and I didn’t know that the docker CLI ignored the response. But I agree. I think that `3xx` responses in general should not cause exceptions to be thrown, but they currently do.
