### ISSUE TITLE
Moving container from a node to another one in runtime

### ISSUE THREAD

**Issue by ViniciusDeAndrade** [spotify/docker-client#932]
## Description
Hello.
I am trying to move a container from a node to another one, during runtime.
I have a skeleton of the code. See (mainly the method **move**)

```
package control;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.LinkedList;
import java.util.List;
import java.util.Map;

import com.google.common.collect.ImmutableList;
import com.spotify.docker.client.DockerClient;
import com.spotify.docker.client.exceptions.DockerException;
import com.spotify.docker.client.messages.ServiceCreateResponse;
import com.spotify.docker.client.messages.swarm.EndpointSpec;
import com.spotify.docker.client.messages.swarm.EndpointSpec.Mode;
import com.spotify.docker.client.messages.swarm.Node;
import com.spotify.docker.client.messages.swarm.Placement;
import com.spotify.docker.client.messages.swarm.PortConfig;
import com.spotify.docker.client.messages.swarm.Service;
import com.spotify.docker.client.messages.swarm.ServiceSpec;
import com.spotify.docker.client.messages.swarm.Task;
import com.spotify.docker.client.messages.swarm.TaskSpec;

import entities.ServAndNode;

public class Control{
	//the key is the service id
	private Map<String,ServAndNode> relation = new HashMap<String, ServAndNode>();



	public Map<String, ServAndNode> getRelation(){
		return this.relation;
	}

	public static void move(DockerClient docker ,  String servID) throws DockerException, InterruptedException {
		// https://docs.docker.com/engine/swarm/services/#placement-constraints
		// placement constraints set where the service should be deployed
		
		List<String> constraints = getConstraints(docker);
				
		Service service = getService(docker, servID);
			
		/*
		 * here, we configure the task template
		 */
		Placement place = Placement.create(constraints);
		TaskSpec taskSpec = TaskSpec.builder()
				.containerSpec(service.spec().taskTemplate().containerSpec())
				.networks(service.spec().networks())
				.placement(place)
				.restartPolicy(service.spec().taskTemplate().restartPolicy())
				.build();		
		
		/*
		 * here we are getting the EndpointSpec
		 */
		//modificar essa lista?
		//List<PortConfig> ports = service.endpoint().ports().asList();
		Mode mode = service.endpoint().spec().mode();		
		EndpointSpec endPoint = EndpointSpec.builder()
				//.ports(service.endpoint().ports()) // ports
				.mode(mode)				
				.build();
		/*
		 * now, lets deal with the spec
		 */
		String serviceName = "bd";
		ServiceSpec spec = ServiceSpec.builder()
				.updateConfig(service.spec().updateConfig())
				.labels(service.spec().labels())
				.name(serviceName)
				.taskTemplate(taskSpec)
				.endpointSpec(endPoint)
				.mode(service.spec().mode())
				.build();
		
		ServiceCreateResponse newServiceResponse = docker.createService(spec);
				
		// clone svc.spec() but changing 
		// svc.spec().taskTemplate().placement() by
		// Placement.create(constraints); 
		
		//service id, service version and the spec of the new service		
		docker.updateService(newServiceResponse.id(), service.version().index()+1 , spec);
		
		
	}

	public void setRelation(DockerClient docker) throws DockerException, InterruptedException {
		List<Task> tasks = docker.listTasks();
		ServAndNode servAndNode;
		for(Task task : tasks) {
			//here I am setting the service id, the node id, the service name and the node name
			servAndNode = new  ServAndNode(task.serviceId(), task.nodeId(), 
					this.getServiceName(docker, task.serviceId()) , this.getNodeName(docker, task.nodeId()));
			this.relation.put(task.serviceId(), servAndNode);
		}
	}

	private static List<Placement> placementConstraints(DockerClient docker) throws DockerException, InterruptedException {
		List<Task> list = docker.listTasks();
		List<Placement> local = new ArrayList<Placement>();
		for(Task t : list) {
			local.add(t.spec().placement());
		}
		return local;
	}

	private static List<String> getConstraints(DockerClient docker) throws DockerException, InterruptedException{
		List<Placement> placements = placementConstraints(docker);
		String rules [] = new String [placements.size()]; 
		List<String> constraints = new ArrayList<String>();
		for(int i = 0; i < placements.size() ; i++) {
			if(placements.get(i).constraints() != null)
				rules[i] = placements.get(i).constraints().toString();
			else
				//mexi aqui!!!!!				
				//rules[i] = "[node.hostname == slave";
				rules[i] = "null";
			constraints.add(rules[i]);
		}
		return constraints;

	}


	private String getNodeName(DockerClient docker, String nodeID) throws DockerException, InterruptedException {
		List<Node> list = docker.listNodes();
		for(Node n : list) 
			if(n.id().equals(nodeID))
				return n.description().hostname();		
		return null;
	}

	private static Service getService(DockerClient docker, String serviceID) throws DockerException, InterruptedException {
		List<Service> list = docker.listServices();
		for(Service s : list) 
			if(s.id().equals(serviceID))
				return s;
		return null;
	}
	private String getServiceName(DockerClient docker, String serviceID) throws DockerException, InterruptedException {
		List<Service> list = docker.listServices();
		for(Service s : list) 
			if(s.id().equals(serviceID))
				return s.spec().name();		
		return null;
	}

}
```
I have a mongo DB running on a node called **vinicius** . I want to migrate it to a node called **slave**
How Can I fix this code to do what I want?
See the errors and the main class:

```
package main;

import com.spotify.docker.client.DefaultDockerClient;
import com.spotify.docker.client.DockerClient;
import com.spotify.docker.client.exceptions.DockerCertificateException;
import com.spotify.docker.client.exceptions.DockerException;

import control.Control;
import entities.ServAndNode;

public class Test {

	public static void main(String[] args) throws DockerCertificateException, DockerException, InterruptedException {
		// TODO Auto-generated method stub

		DockerClient docker = DefaultDockerClient.fromEnv().build();
		// [servID=9gokanuqk1nse5f0z24iu9b3m, nodeID=k74wi8f89rzxzro4smmq5gyxk ,servName=app_mongodb, nodeName=vinicius-VPCEG17FB]
		String node1 = "slave";
		
		
		Control control = new Control();
		control.setRelation(docker);
		//get the keys
		ServAndNode info = control.getRelation().get("9gokanuqk1nse5f0z24iu9b3m");
				
		control.move(docker, info.getServID());
		
		System.out.println(control.getRelation().values());
		
	}

}

```

```

SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" com.spotify.docker.client.exceptions.DockerRequestException: Request error: POST unix://localhost:80/services/create: 500, body: {"message":"rpc error: code = Unknown desc = key '[node.hostname' is invalid"}

	at com.spotify.docker.client.DefaultDockerClient.propagate(DefaultDockerClient.java:2691)
	at com.spotify.docker.client.DefaultDockerClient.request(DefaultDockerClient.java:2641)
	at com.spotify.docker.client.DefaultDockerClient.createService(DefaultDockerClient.java:1837)
	at com.spotify.docker.client.DefaultDockerClient.createService(DefaultDockerClient.java:1826)
	at control.Control.move(Control.java:76)
	at main.Test.main(Test.java:26)
Caused by: javax.ws.rs.InternalServerErrorException: HTTP 500 Internal Server Error
	at org.glassfish.jersey.client.JerseyInvocation.convertToException(JerseyInvocation.java:1020)
	at org.glassfish.jersey.client.JerseyInvocation.translate(JerseyInvocation.java:816)
	at org.glassfish.jersey.client.JerseyInvocation.access$700(JerseyInvocation.java:92)
	at org.glassfish.jersey.client.JerseyInvocation$5.completed(JerseyInvocation.java:773)
	at org.glassfish.jersey.client.ClientRuntime.processResponse(ClientRuntime.java:198)
	at org.glassfish.jersey.client.ClientRuntime.access$300(ClientRuntime.java:79)
	at org.glassfish.jersey.client.ClientRuntime$2.run(ClientRuntime.java:180)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:340)
	at org.glassfish.jersey.client.ClientRuntime$3.run(ClientRuntime.java:210)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by ViniciusDeAndrade** [comment]
Maybe I found the problem. But I still need some help

changing the method _placementConstraints_ to : 

```
private static List<Placement> placementConstraints(DockerClient docker) throws DockerException, InterruptedException {
		List<Task> list = docker.listTasks();
		List<Placement> local = new ArrayList<Placement>();
		for(Task t : list) {
			if(t.spec().placement() == null)
				t.spec().placement().constraints().add("slave");
			System.out.println(t.spec().placement());
			local.add(t.spec().placement());
		}
		return local;
	}
```
I realized the most of all placement are null. But how Can I set this?

![this was the output](https://user-images.githubusercontent.com/4364432/33078330-11e4be64-ceb1-11e7-9a31-9cf2393e2a1f.png)

**Comment by johnflavin** [comment]
I'm not sure what is going wrong. This is a lot to digest. 

Are you able to do what you want to do using the docker CLI? If you are able to do that, it might help you and us understand how to translate to the API calls.

**Comment by johnflavin** [comment]
As a side note, I don't think you need `Service getService(DockerClient docker, String serviceID)`. We have `Service DockerClient.inspectService(String serviceId)`.

**Comment by ViniciusDeAndrade** [comment]
I see.
In fact, I really did not tryed to do that with CLI. 
Yet, if the java client can get some data from the running containers, I think it do not need to be considered. 
By the way, I need to know I can create a Placement with my nodes and how to set it correctly on the ServiceSpec

**Comment by ViniciusDeAndrade** [comment]
Let make it simple?
How can I implement a way to move a running container from one node to another one?

I got a very small template, [and you can see it here](https://github.com/ViniciusDeAndrade/swarm-runtime/blob/master/swarm-runtime/src/main/java/control/Control2.java), on the last method called **move**

**Comment by johnflavin** [comment]
I think what you’re doing is on the right track. You have a running service. You need to issue an `updateService` call to that service's ID, using a `ServiceSpec` on which you have set the placement constraint `node.hostname == whatever`. That is what your code appears to do, so I think you’re probably almost there.

I do see some problems with the `placementConstraints` method you posted in your [comment](https://github.com/spotify/docker-client/issues/932#issuecomment-346047371) above.
```java
if(t.spec().placement() == null)
	t.spec().placement().constraints().add("slave");
```
1. You’re checking that `t.spec().placement() == null`, then doing things with `t.spec().placement()`. That seems guaranteed to throw a NPE. You should, I think, check instead that `t.spec().placement() != null`. Or, if `t.spec().placement() == null`, you should add your desired constraint to a new empty list.
2. The `List` that gets returned from `t.spec().placement().constraints()` is an `ImmutableList`. You will not be able to `add` anything to it. Indeed, you can see in the screenshot you posted that your IDE has struck through your invocation of the `add` method because it knows you can't use this. If you want to add something to this list, you need to first copy it to a mutable list, then add what you want.
3. The String `"slave"` is not a constraint. The constraint would need to be `"node.hostname == slave"`.

Try fixing those things and see what happens.

**Comment by ViniciusDeAndrade** [comment]
I will try to do what you sugest. See below 2 screenshots to get an ideia of how this is  working
Since from now, thank you for your support

![mong](https://user-images.githubusercontent.com/4364432/33130379-ec3f4d0c-cf71-11e7-9632-250b2ef50cad.png)

![screenshot](https://user-images.githubusercontent.com/4364432/33130342-ca628d16-cf71-11e7-82c2-61c36fcf1d4e.png)

**Comment by davidxia** [comment]
I’m going to close since this issue seems a bit out of the realm of docker client which is just a java library to interact with the remote docker API. If you find a bug with the docker client’s interaction or a missing API call or functionality I can reopen. But it seems like the issue so far is what API methods to call. The methods in this client map one to one to the remote API so once you figure out what docker CLI commands to run or what API endpoints to call, you should be able to easily translate to the methods in this library.
