### ISSUE TITLE
docker-client couldn't find local image

### ISSUE THREAD

**Issue by RohitBarnwal** [spotify/docker-client#980]
I am using docker-client plugin to launch docker container build by dockerfile-maven plugin
When I run mvn verify, integration test throws following error
This test method should be run
com.spotify.docker.client.exceptions.ImageNotFoundException: Image not found: rohitbarnwal7/presto_log_updated:0.0.1
	at com.spotify.docker.client.DefaultDockerClient.pull(DefaultDockerClient.java:1268)
	at com.spotify.docker.client.DefaultDockerClient.pull(DefaultDockerClient.java:1235)
	at com.spotify.docker.client.DefaultDockerClient.pull(DefaultDockerClient.java:1229)
	at IntegrationTestIT.checkForQueryInFile(IntegrationTestIT.java:48)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1191)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)
	at org.testng.TestNG.run(TestNG.java:1024)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:62)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:141)
	at org.apache.maven.surefire.Surefire.run(Surefire.java:180)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.booter.SurefireBooter.runSuitesInProcess(SurefireBooter.java:350)
	at org.apache.maven.surefire.booter.SurefireBooter.main(SurefireBooter.java:1021)
Caused by: com.spotify.docker.client.exceptions.DockerRequestException: Request error: POST unix://localhost:80/images/create?fromImage=rohitbarnwal7%2Fpresto_log_updated&tag=0.0.1: 404, body: {"message":"pull access denied for rohitbarnwal7/presto_log_updated, repository does not exist or may require 'docker login'"}

	at com.spotify.docker.client.DefaultDockerClient.propagate(DefaultDockerClient.java:2702)
	at com.spotify.docker.client.DefaultDockerClient.request(DefaultDockerClient.java:2641)
	at com.spotify.docker.client.DefaultDockerClient.pull(DefaultDockerClient.java:1258)
	... 33 more
Caused by: javax.ws.rs.NotFoundException: HTTP 404 Not Found
	at org.glassfish.jersey.client.JerseyInvocation.convertToException(JerseyInvocation.java:1008)
	at org.glassfish.jersey.client.JerseyInvocation.translate(JerseyInvocation.java:816)
	at org.glassfish.jersey.client.JerseyInvocation.access$700(JerseyInvocation.java:92)
	at org.glassfish.jersey.client.JerseyInvocation$5.completed(JerseyInvocation.java:773)
	at org.glassfish.jersey.client.ClientRuntime.processResponse(ClientRuntime.java:198)
	at org.glassfish.jersey.client.ClientRuntime.access$300(ClientRuntime.java:79)
	at org.glassfish.jersey.client.ClientRuntime$2.run(ClientRuntime.java:180)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:340)
	at org.glassfish.jersey.client.ClientRuntime$3.run(ClientRuntime.java:210)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 9.927 sec

Line 48 of IntegrationTestIT.java:

            docker.pull("rohitbarnwal7/presto_log_updated:0.0.1");

Any help here please?

**Comment by mattnworb** [comment]
Sounds like there is a mismatch between the versions used of the various Jackson libraries on your project's classpath: https://github.com/FasterXML/jackson-annotations/issues/119

**Comment by RohitBarnwal** [comment]
I have different issue, I no more have mismatch issue.

**Comment by mattnworb** [comment]
If the docker daemon / docker-client reports a 404 not found, then as the error message says either the image does not exist in Docker Hub or you need to authenticate to pull the private image:

```
$ docker pull rohitbarnwal7/presto_log_updated:0.0.1
Error response from daemon: pull access denied for rohitbarnwal7/presto_log_updated, repository does not exist or may require 'docker login'
```

**Comment by RohitBarnwal** [comment]
Is there any way to pick the local image from my host machine. 
Docker images

docker images
REPOSITORY                         TAG                 IMAGE ID            CREATED             SIZE
rohitbarnwal7/presto_log_updated   0.0.1               eb8add1b658c        About an hour ago   2.03GB
openjdk                            8                   7c57090325cc        8 weeks ago         737MB

**Comment by johnflavin** [comment]
If you do a `docker pull`, it will always try to pull from the remote server. It needs to check if there are updates to the image.

If you know the image is there locally, and can't be found on a remote server, why is your test trying to pull it? Maybe it would be better for your test to do something like `assume(someMethodWhereYouCheckIfTheImageExists, is(true));`. If the image isn't there for some reason, the test would not fail but would just be skipped. Or include the image's `Dockerfile` in your test resources and build it before running any tests; that way you can be 100% sure it is there.

**Comment by RohitBarnwal** [comment]
Yes, that resolved my case. Thanks.
