### ISSUE TITLE
Default DOCKER_HOST does not work on localhost if proxy is set

### ISSUE THREAD

**Issue by stromnet** [spotify/docker-client#982]
## Description

After upgrading from 8.10.0 (well actually earlier but in this version it works) to 8.11.0 I can no longer connect to local docker instance if system-wide HTTP proxy is configured. 

If I *do* set `.useProxy(false)` it works, but for default docker installation with localhost access, I think it make sense that it would work out of the box (the few situations where a proxy is in use for localhost probably not be the default case to adjust for).

Perhaps solved if #978 is fixed? In my case the OS has nonProxyHosts `localhost`.

## How to reproduce

Using 8.11.1, and a default DockerClient: 
```
DefaultDockerClient
                    .fromEnv()
                    .build();
```

To set proxy, either configure (on OSX at least) global system proxy, or run with `mvn ... -Dhttp.proxyHost=proxy.example.com -Dhttp.proxyPort=808`

## What do you expect

With default docker environment with no custom DOCKER_HOST, just running docker locally, it should work.

## What happened instead

```2018-02-12 08:34:44:157 [jersey-client-async-executor-0] INFO org.apache.http.impl.execchain.RetryExec - I/O exception (org.apache.http.NoHttpResponseException) caught when processing request to {}->http://myproxy.example.com:808->unix://localhost:80: The target server failed to respond
2018-02-12 08:34:44:158 [jersey-client-async-executor-0] INFO org.apache.http.impl.execchain.RetryExec - Retrying request to {}->http://myproxy.example.com:808->unix://localhost:80
...
org.apache.http.NoHttpResponseException: localhost:80 failed to respond
```

Not sure where `localhost:80` comes from, `DOCKER_HOST` is not set so it ought to resolve `defaultDockerEndpoint` to either `localhost:2375` or `unix:///var/run/docker.sock` (the later in my case, since I'm running Mac)

## Software:

Docker version 17.12.0-ce, build c97c6d6 (Mac)
docker-client 8.11.1

## Full backtrace

```text
2018-02-12 08:37:47:129 [main] ERROR com.xxx.component.test.core.TestEnvironment - Failed to delete network XXXXX
com.xxx.component.test.exceptions.DockerClientWrapperException: Failed to delete network XXXXX
	at com.xxx.component.test.core.DockerClientWrapperImpl.deleteNetwork(DockerClientWrapperImpl.java:256)
	at com.xxx.component.test.core.TestEnvironment.deleteNetworkQuietly(TestEnvironment.java:203)
	at com.xxx.component.test.core.TestEnvironment.tearDown(TestEnvironment.java:184)
	at com.xxx.component.test.junit.DockerRule$1.evaluate(DockerRule.java:86)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:367)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:274)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:161)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
Caused by: com.spotify.docker.client.exceptions.DockerException: java.util.concurrent.ExecutionException: javax.ws.rs.ProcessingException: org.apache.http.NoHttpResponseException: localhost:80 failed to respond
	at com.spotify.docker.client.DefaultDockerClient.propagate(DefaultDockerClient.java:2710)
	at com.spotify.docker.client.DefaultDockerClient.request(DefaultDockerClient.java:2663)
	at com.spotify.docker.client.DefaultDockerClient.removeNetwork(DefaultDockerClient.java:2415)
	at com.xxx.component.test.core.DockerClientWrapperImpl.deleteNetwork(DockerClientWrapperImpl.java:252)
	... 12 more
Caused by: java.util.concurrent.ExecutionException: javax.ws.rs.ProcessingException: org.apache.http.NoHttpResponseException: localhost:80 failed to respond
	at jersey.repackaged.com.google.common.util.concurrent.AbstractFuture$Sync.getValue(AbstractFuture.java:299)
	at jersey.repackaged.com.google.common.util.concurrent.AbstractFuture$Sync.get(AbstractFuture.java:286)
	at jersey.repackaged.com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:116)
	at com.spotify.docker.client.DefaultDockerClient.request(DefaultDockerClient.java:2661)
	... 14 more
Caused by: javax.ws.rs.ProcessingException: org.apache.http.NoHttpResponseException: localhost:80 failed to respond
	at org.glassfish.jersey.apache.connector.ApacheConnector.apply(ApacheConnector.java:481)
	at org.glassfish.jersey.apache.connector.ApacheConnector$1.run(ApacheConnector.java:491)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at jersey.repackaged.com.google.common.util.concurrent.MoreExecutors$DirectExecutorService.execute(MoreExecutors.java:299)
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112)
	at jersey.repackaged.com.google.common.util.concurrent.AbstractListeningExecutorService.submit(AbstractListeningExecutorService.java:50)
	at jersey.repackaged.com.google.common.util.concurrent.AbstractListeningExecutorService.submit(AbstractListeningExecutorService.java:37)
	at org.glassfish.jersey.apache.connector.ApacheConnector.apply(ApacheConnector.java:487)
	at org.glassfish.jersey.client.ClientRuntime$2.run(ClientRuntime.java:180)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:340)
	at org.glassfish.jersey.client.ClientRuntime$3.run(ClientRuntime.java:208)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.http.NoHttpResponseException: localhost:80 failed to respond
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:143)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57)
	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)
	at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163)
	at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:167)
	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273)
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:271)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:71)
	at org.glassfish.jersey.apache.connector.ApacheConnector.apply(ApacheConnector.java:435)
	... 21 more
```

**Comment by mattnworb** [comment]
Thanks for the detailed description / steps to reproduce. I agree that it sounds like addressing #978 would fix this as well.
